import { readdirSync, writeFileSync } from "node:fs";
import * as path from "node:path";

import { SCREENSHOT_DIR } from "../fixtures/env";

// build-gallery scans docs/screenshots/*.png and emits a Markdown
// gallery README so visitors can preview the UI on GitHub without
// cloning. Filenames follow NN-name.png; numeric prefix orders them.
//
// Title map turns "01-login" → "Login". Anything missing falls back to
// title-cased filename.

const TITLES: Record<string, { title: string; caption: string; section: string }> = {
    "01-login": {
        title: "Login",
        caption: "JWT-gated entry point. Same flow on web and desktop.",
        section: "Auth",
    },
    "02-projects-landing": {
        title: "Projects landing",
        caption: "Tile grid of every project the user can see. Click to drill in.",
        section: "Auth",
    },
    "03-sidebar": {
        title: "Project sidebar",
        caption: "Linear-style flat nav: project switcher + 6 first-class destinations + user menu.",
        section: "Shell",
    },
    "04-project-overview": {
        title: "Project overview dashboard",
        caption: "4 KPIs · sessions over 24h · top hosts · recent activity. Primary actions live in the page header.",
        section: "Project pages",
    },
    "05-listeners-list": {
        title: "Listeners list",
        caption: "Always-visible \"+ New listener\" in the page header.",
        section: "Project pages",
    },
    "06-listener-detail": {
        title: "Listener detail",
        caption: "Definition list of endpoint metadata + Stop action.",
        section: "Project pages",
    },
    "07-listener-create-modal": {
        title: "Create-listener modal",
        caption: "Bind host + port; modal is reachable from header, empty state, or quick actions.",
        section: "Project pages",
    },
    "08-hosts-empty": {
        title: "Hosts (empty)",
        caption: "Cross-host list. Empty state guides you to the listener page since hosts only appear after an agent connects.",
        section: "Project pages",
    },
    "09-sessions-empty": {
        title: "Sessions (empty)",
        caption: "Cross-host live + historical sessions, with Live/All filter chips.",
        section: "Project pages",
    },
    "10-dispatch": {
        title: "Dispatch",
        caption: "Run a command across every flagged live session in the project.",
        section: "Project pages",
    },
    "11-members": {
        title: "Project members",
        caption: "ACL editor with role pills (admin / operator / viewer).",
        section: "Project pages",
    },
    "12-admin-users": {
        title: "Admin · users",
        caption: "Global user CRUD reachable from the user menu.",
        section: "Admin",
    },
    "13-project-switcher-open": {
        title: "Project switcher",
        caption: "Sidebar dropdown: jump between projects without leaving the current view category.",
        section: "Shell",
    },
    "14-projects-landing-multi": {
        title: "Projects landing (multi)",
        caption: "Same landing as above with two projects seeded.",
        section: "Shell",
    },
};

interface Shot {
    file: string;
    key: string;
    order: number;
    title: string;
    caption: string;
    section: string;
}

function loadShots(): Shot[] {
    const files = readdirSync(SCREENSHOT_DIR).filter((f) => f.endsWith(".png"));
    return files
        .map((file) => {
            const key = file.replace(/\.png$/, "");
            const m = file.match(/^(\d+)/);
            const order = m ? Number(m[1]) : 999;
            const meta = TITLES[key] ?? {
                title: key.replace(/^\d+-/, "").replace(/-/g, " "),
                caption: "",
                section: "Misc",
            };
            return { file, key, order, ...meta };
        })
        .sort((a, b) => a.order - b.order);
}

function build(): string {
    const shots = loadShots();
    const sections = new Map<string, Shot[]>();
    for (const s of shots) {
        const arr = sections.get(s.section) ?? [];
        arr.push(s);
        sections.set(s.section, arr);
    }

    const lines: string[] = [];
    lines.push("# Platypus UI screenshots");
    lines.push("");
    lines.push(
        "Auto-generated by the Playwright e2e suite — see " +
            "[`e2e/`](../../e2e/) " +
            "for the source. Re-run with `make screenshots` from the repo root.",
    );
    lines.push("");

    const order = ["Auth", "Shell", "Project pages", "Admin", "Misc"];
    for (const sec of order) {
        const items = sections.get(sec);
        if (!items || items.length === 0) continue;
        lines.push(`## ${sec}`);
        lines.push("");
        for (const s of items) {
            lines.push(`### ${s.title}`);
            lines.push("");
            if (s.caption) {
                lines.push(s.caption);
                lines.push("");
            }
            lines.push(`<img src="${s.file}" alt="${s.title}" width="900">`);
            lines.push("");
        }
    }
    return lines.join("\n");
}

const out = build();
const outPath = path.join(SCREENSHOT_DIR, "README.md");
writeFileSync(outPath, out, "utf8");
console.log(`wrote ${outPath} (${out.split("\n").length} lines)`);
