listeners:
  - bind_host: 127.0.0.1
    bind_port: 7070
    type: restful
  - bind_host: 127.0.0.1
    bind_port: 8080
    type: plain_shell
  - bind_host: 127.0.0.1
    bind_port: 9090
    type: encrypted_shell
