// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: common.proto

package v2pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamType identifies how the peer should route a newly accepted
// yamux stream. The initiator MUST send a StreamHeader with the
// correct type as the first protobuf message on the stream; the
// receiver MUST reply with StreamAccept or StreamReject before any
// service-specific frame flows.
type StreamType int32

const (
	StreamType_STREAM_TYPE_UNSPECIFIED StreamType = 0
	// Bidirectional PTY session. server->agent.
	// Service-specific frames after header use a 1-byte opcode prefix
	// (see internal/protocol/v2/process): 0=stdin, 1=stdout, 2=stderr,
	// 3=resize, 4=exit.
	StreamType_STREAM_TYPE_PROCESS_OPEN StreamType = 1
	// Local-to-remote forwarding (pull). server->agent.
	// Payload after header is raw TCP bytes, bidirectional.
	StreamType_STREAM_TYPE_TUNNEL_PULL StreamType = 2
	// Remote-to-local forwarding (push). agent->server.
	// Agent accepted an inbound TCP conn; server dials a local target.
	StreamType_STREAM_TYPE_TUNNEL_PUSH StreamType = 3
	// Dynamic SOCKS5 proxy control. server->agent.
	// Agent starts/stops a local SOCKS5 listener on behalf of server.
	StreamType_STREAM_TYPE_SOCKS5_CTL StreamType = 4
	// Streaming file read. server->agent (agent is file source).
	StreamType_STREAM_TYPE_FILE_READ StreamType = 5
	// Streaming file write. server->agent (agent is file sink).
	StreamType_STREAM_TYPE_FILE_WRITE StreamType = 6
	// One-shot RPCs. Request message first, response message back,
	// stream closes immediately after. Which RPC is in the metadata
	// field of StreamHeader.
	StreamType_STREAM_TYPE_RPC StreamType = 7
	// Async events from agent->server. Opened by agent on demand
	// (process_exited, tunnel_closed, sys_metrics, etc.).
	StreamType_STREAM_TYPE_EVENT StreamType = 8
)

// Enum value maps for StreamType.
var (
	StreamType_name = map[int32]string{
		0: "STREAM_TYPE_UNSPECIFIED",
		1: "STREAM_TYPE_PROCESS_OPEN",
		2: "STREAM_TYPE_TUNNEL_PULL",
		3: "STREAM_TYPE_TUNNEL_PUSH",
		4: "STREAM_TYPE_SOCKS5_CTL",
		5: "STREAM_TYPE_FILE_READ",
		6: "STREAM_TYPE_FILE_WRITE",
		7: "STREAM_TYPE_RPC",
		8: "STREAM_TYPE_EVENT",
	}
	StreamType_value = map[string]int32{
		"STREAM_TYPE_UNSPECIFIED":  0,
		"STREAM_TYPE_PROCESS_OPEN": 1,
		"STREAM_TYPE_TUNNEL_PULL":  2,
		"STREAM_TYPE_TUNNEL_PUSH":  3,
		"STREAM_TYPE_SOCKS5_CTL":   4,
		"STREAM_TYPE_FILE_READ":    5,
		"STREAM_TYPE_FILE_WRITE":   6,
		"STREAM_TYPE_RPC":          7,
		"STREAM_TYPE_EVENT":        8,
	}
)

func (x StreamType) Enum() *StreamType {
	p := new(StreamType)
	*p = x
	return p
}

func (x StreamType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (StreamType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x StreamType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamType.Descriptor instead.
func (StreamType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// StreamHeader is the first protobuf message on every new yamux
// stream. It tells the receiver how to dispatch the rest of the
// stream. `metadata` carries a service-specific marshalled message
// (e.g. ProcessOpenRequest for STREAM_TYPE_PROCESS_OPEN).
type StreamHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type StreamType `protobuf:"varint,1,opt,name=type,proto3,enum=platypus.v2.StreamType" json:"type,omitempty"`
	// Service-specific request, marshalled. The schema is decided by
	// `type`: e.g. ProcessOpenRequest, TunnelPullRequest, RpcRequest.
	// The receiver must attempt to unmarshal and reject on parse error.
	Metadata []byte `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Correlation id for logging; opaque to the protocol. The server
	// will echo this in any resulting Event.correlation_id so
	// operators can trace a stream end-to-end.
	CorrelationId string `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
}

func (x *StreamHeader) Reset() {
	*x = StreamHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamHeader) ProtoMessage() {}

func (x *StreamHeader) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamHeader.ProtoReflect.Descriptor instead.
func (*StreamHeader) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *StreamHeader) GetType() StreamType {
	if x != nil {
		return x.Type
	}
	return StreamType_STREAM_TYPE_UNSPECIFIED
}

func (x *StreamHeader) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StreamHeader) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// StreamAccept is the receiver's positive acknowledgement. Sent
// right after the first valid StreamHeader was parsed and the
// service-specific handler is ready to consume frames.
type StreamAccept struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StreamAccept) Reset() {
	*x = StreamAccept{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAccept) ProtoMessage() {}

func (x *StreamAccept) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAccept.ProtoReflect.Descriptor instead.
func (*StreamAccept) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

// StreamReject is the receiver's negative acknowledgement. The
// sender must close the stream immediately after reading it; no
// service-specific frames have flowed.
type StreamReject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Machine-readable error kind. Values reserved:
	//
	//	"unsupported_type", "malformed_metadata", "unauthorized",
	//	"resource_exhausted", "internal".
	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StreamReject) Reset() {
	*x = StreamReject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamReject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamReject) ProtoMessage() {}

func (x *StreamReject) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamReject.ProtoReflect.Descriptor instead.
func (*StreamReject) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *StreamReject) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StreamReject) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

var file_common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x70, 0x6c, 0x61, 0x74, 0x79, 0x70, 0x75, 0x73, 0x2e, 0x76, 0x32, 0x22, 0x7e, 0x0a, 0x0c, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x6c, 0x61, 0x74,
	0x79, 0x70, 0x75, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f,
	0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x22, 0x3c, 0x0a, 0x0c, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x80, 0x02, 0x0a, 0x0a, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x53, 0x54, 0x52, 0x45,
	0x41, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x4f, 0x50, 0x45,
	0x4e, 0x10, 0x01, 0x12, 0x1b, 0x0a, 0x17, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x54, 0x55, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x50, 0x55, 0x4c, 0x4c, 0x10, 0x02,
	0x12, 0x1b, 0x0a, 0x17, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x54, 0x55, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x50, 0x55, 0x53, 0x48, 0x10, 0x03, 0x12, 0x1a, 0x0a,
	0x16, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x4f, 0x43,
	0x4b, 0x53, 0x35, 0x5f, 0x43, 0x54, 0x4c, 0x10, 0x04, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x54, 0x52,
	0x45, 0x41, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x52, 0x45,
	0x41, 0x44, 0x10, 0x05, 0x12, 0x1a, 0x0a, 0x16, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x57, 0x52, 0x49, 0x54, 0x45, 0x10, 0x06,
	0x12, 0x13, 0x0a, 0x0f, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x52, 0x50, 0x43, 0x10, 0x07, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x10, 0x08, 0x42, 0x32, 0x5a, 0x30,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x57, 0x61, 0x6e, 0x67, 0x59,
	0x69, 0x68, 0x61, 0x6e, 0x67, 0x2f, 0x50, 0x6c, 0x61, 0x74, 0x79, 0x70, 0x75, 0x73, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x32, 0x3b, 0x76, 0x32, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData = file_common_proto_rawDesc
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_rawDescData)
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_proto_goTypes = []interface{}{
	(StreamType)(0),      // 0: platypus.v2.StreamType
	(*StreamHeader)(nil), // 1: platypus.v2.StreamHeader
	(*StreamAccept)(nil), // 2: platypus.v2.StreamAccept
	(*StreamReject)(nil), // 3: platypus.v2.StreamReject
}
var file_common_proto_depIdxs = []int32{
	0, // 0: platypus.v2.StreamHeader.type:type_name -> platypus.v2.StreamType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamAccept); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamReject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_rawDesc = nil
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
