// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: common.proto

package v2pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamType identifies how the peer should route a newly accepted
// yamux stream. The initiator MUST send a StreamHeader with the
// correct type as the first protobuf message on the stream; the
// receiver MUST reply with StreamAccept or StreamReject before any
// service-specific frame flows.
type StreamType int32

const (
	StreamType_STREAM_TYPE_UNSPECIFIED StreamType = 0
	// Bidirectional PTY session. server->agent.
	// Service-specific frames after header use a 1-byte opcode prefix
	// (see internal/protocol/v2/process): 0=stdin, 1=stdout, 2=stderr,
	// 3=resize, 4=exit.
	StreamType_STREAM_TYPE_PROCESS_OPEN StreamType = 1
	// Local-to-remote forwarding (pull). server->agent.
	// Payload after header is raw TCP bytes, bidirectional.
	StreamType_STREAM_TYPE_TUNNEL_PULL StreamType = 2
	// Remote-to-local forwarding (push). agent->server.
	// Agent accepted an inbound TCP conn; server dials a local target.
	StreamType_STREAM_TYPE_TUNNEL_PUSH StreamType = 3
	// Dynamic SOCKS5 proxy control. server->agent.
	// Agent starts/stops a local SOCKS5 listener on behalf of server.
	StreamType_STREAM_TYPE_SOCKS5_CTL StreamType = 4
	// Streaming file read. server->agent (agent is file source).
	StreamType_STREAM_TYPE_FILE_READ StreamType = 5
	// Streaming file write. server->agent (agent is file sink).
	StreamType_STREAM_TYPE_FILE_WRITE StreamType = 6
	// One-shot RPCs. Request message first, response message back,
	// stream closes immediately after. Which RPC is in the metadata
	// field of StreamHeader.
	StreamType_STREAM_TYPE_RPC StreamType = 7
	// Async events from agent->server. Opened by agent on demand
	// (process_exited, tunnel_closed, sys_metrics, etc.).
	StreamType_STREAM_TYPE_EVENT StreamType = 8
	// Walks the requested paths and reports counts (files, total
	// bytes) without transferring any payload. Used to size a
	// progress bar before opening STREAM_TYPE_FILE_ARCHIVE.
	// server->agent.
	StreamType_STREAM_TYPE_FILE_SCAN StreamType = 9
	// Streaming archive build. The agent walks the given paths,
	// packs them into the requested archive format (tar / tar.gz /
	// zip), and streams the bytes back as FileChunk frames. Saves
	// the per-chunk HTTP roundtrip the legacy
	// read-offset-by-offset path pays. server->agent.
	StreamType_STREAM_TYPE_FILE_ARCHIVE StreamType = 10
	// server->agent. Command-only; the agent is told which manifest
	// version to install on which channel and goes off to fetch the
	// signed binary from the distributor over HTTPS. Header metadata
	// is AgentUpgradeRequest. The stream body carries UpgradeProgress
	// events from agent->server until the agent either reports
	// success (and exits with EX_TEMPFAIL so the supervisor restarts
	// it) or reports a terminal failure.
	//
	// Trust model: the agent verifies the manifest's detached
	// Ed25519 signature against a public key baked into the agent
	// binary at build time (internal/agent.SigningPublicKey, set by
	// -ldflags). mTLS to the distributor is incidental — the
	// signature is the source of trust, not the transport.
	StreamType_STREAM_TYPE_AGENT_UPGRADE StreamType = 11
	// server->agent. Plugin lifecycle management: install, uninstall,
	// list, enable/disable, get logs. Header metadata is
	// PluginMgmtRequest. For install the stream stays open and carries
	// PluginInstallChunk frames (inline source) or
	// PluginInstallProgress frames (URL source) until a terminal
	// PHASE_INSTALLED / PHASE_FAILED frame closes it. For other ops
	// the agent writes a single PluginMgmtResponse and closes.
	//
	// Trust model: the binary is verified per-plugin against a minisign
	// Ed25519 publisher key delivered in PluginInstallRequest, not the
	// agent's bundled SigningPublicKey. The bundled key only protects
	// the agent's own self-update path; plugins are a separate trust
	// domain so rotating one doesn't compromise the other.
	StreamType_STREAM_TYPE_PLUGIN_MGMT StreamType = 12
)

// Enum value maps for StreamType.
var (
	StreamType_name = map[int32]string{
		0:  "STREAM_TYPE_UNSPECIFIED",
		1:  "STREAM_TYPE_PROCESS_OPEN",
		2:  "STREAM_TYPE_TUNNEL_PULL",
		3:  "STREAM_TYPE_TUNNEL_PUSH",
		4:  "STREAM_TYPE_SOCKS5_CTL",
		5:  "STREAM_TYPE_FILE_READ",
		6:  "STREAM_TYPE_FILE_WRITE",
		7:  "STREAM_TYPE_RPC",
		8:  "STREAM_TYPE_EVENT",
		9:  "STREAM_TYPE_FILE_SCAN",
		10: "STREAM_TYPE_FILE_ARCHIVE",
		11: "STREAM_TYPE_AGENT_UPGRADE",
		12: "STREAM_TYPE_PLUGIN_MGMT",
	}
	StreamType_value = map[string]int32{
		"STREAM_TYPE_UNSPECIFIED":   0,
		"STREAM_TYPE_PROCESS_OPEN":  1,
		"STREAM_TYPE_TUNNEL_PULL":   2,
		"STREAM_TYPE_TUNNEL_PUSH":   3,
		"STREAM_TYPE_SOCKS5_CTL":    4,
		"STREAM_TYPE_FILE_READ":     5,
		"STREAM_TYPE_FILE_WRITE":    6,
		"STREAM_TYPE_RPC":           7,
		"STREAM_TYPE_EVENT":         8,
		"STREAM_TYPE_FILE_SCAN":     9,
		"STREAM_TYPE_FILE_ARCHIVE":  10,
		"STREAM_TYPE_AGENT_UPGRADE": 11,
		"STREAM_TYPE_PLUGIN_MGMT":   12,
	}
)

func (x StreamType) Enum() *StreamType {
	p := new(StreamType)
	*p = x
	return p
}

func (x StreamType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (StreamType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x StreamType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamType.Descriptor instead.
func (StreamType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// StreamHeader is the first protobuf message on every new yamux
// stream. It tells the receiver how to dispatch the rest of the
// stream. `metadata` carries a service-specific marshalled message
// (e.g. ProcessOpenRequest for STREAM_TYPE_PROCESS_OPEN).
type StreamHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  StreamType             `protobuf:"varint,1,opt,name=type,proto3,enum=platypus.v2.StreamType" json:"type,omitempty"`
	// Service-specific request, marshalled. The schema is decided by
	// `type`: e.g. ProcessOpenRequest, TunnelPullRequest, RpcRequest.
	// The receiver must attempt to unmarshal and reject on parse error.
	Metadata []byte `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Correlation id for logging; opaque to the protocol. The server
	// will echo this in any resulting Event.correlation_id so
	// operators can trace a stream end-to-end.
	CorrelationId string `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Per-link session id, generated server-side when a v2 agent is
	// registered with the link service. Stable for the lifetime of the
	// yamux session and identical on every header the server emits for
	// that link, so operators can group all RPCs / streams that flowed
	// over a single agent connection. Empty on agent->server initiated
	// streams unless the agent has stashed the value from a prior
	// server-initiated stream. Opaque to the protocol; logging only.
	LinkSessionId string `protobuf:"bytes,4,opt,name=link_session_id,json=linkSessionId,proto3" json:"link_session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamHeader) Reset() {
	*x = StreamHeader{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamHeader) ProtoMessage() {}

func (x *StreamHeader) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamHeader.ProtoReflect.Descriptor instead.
func (*StreamHeader) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *StreamHeader) GetType() StreamType {
	if x != nil {
		return x.Type
	}
	return StreamType_STREAM_TYPE_UNSPECIFIED
}

func (x *StreamHeader) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StreamHeader) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *StreamHeader) GetLinkSessionId() string {
	if x != nil {
		return x.LinkSessionId
	}
	return ""
}

// StreamAccept is the receiver's positive acknowledgement. Sent
// right after the first valid StreamHeader was parsed and the
// service-specific handler is ready to consume frames.
type StreamAccept struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAccept) Reset() {
	*x = StreamAccept{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAccept) ProtoMessage() {}

func (x *StreamAccept) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAccept.ProtoReflect.Descriptor instead.
func (*StreamAccept) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

// StreamReject is the receiver's negative acknowledgement. The
// sender must close the stream immediately after reading it; no
// service-specific frames have flowed.
type StreamReject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Machine-readable error kind. Values reserved:
	//
	//	"unsupported_type", "malformed_metadata", "unauthorized",
	//	"resource_exhausted", "internal".
	Code          string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamReject) Reset() {
	*x = StreamReject{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamReject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamReject) ProtoMessage() {}

func (x *StreamReject) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamReject.ProtoReflect.Descriptor instead.
func (*StreamReject) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *StreamReject) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StreamReject) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\vplatypus.v2\"\xa6\x01\n" +
	"\fStreamHeader\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.platypus.v2.StreamTypeR\x04type\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\fR\bmetadata\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\x12&\n" +
	"\x0flink_session_id\x18\x04 \x01(\tR\rlinkSessionId\"\x0e\n" +
	"\fStreamAccept\"<\n" +
	"\fStreamReject\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xf5\x02\n" +
	"\n" +
	"StreamType\x12\x1b\n" +
	"\x17STREAM_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18STREAM_TYPE_PROCESS_OPEN\x10\x01\x12\x1b\n" +
	"\x17STREAM_TYPE_TUNNEL_PULL\x10\x02\x12\x1b\n" +
	"\x17STREAM_TYPE_TUNNEL_PUSH\x10\x03\x12\x1a\n" +
	"\x16STREAM_TYPE_SOCKS5_CTL\x10\x04\x12\x19\n" +
	"\x15STREAM_TYPE_FILE_READ\x10\x05\x12\x1a\n" +
	"\x16STREAM_TYPE_FILE_WRITE\x10\x06\x12\x13\n" +
	"\x0fSTREAM_TYPE_RPC\x10\a\x12\x15\n" +
	"\x11STREAM_TYPE_EVENT\x10\b\x12\x19\n" +
	"\x15STREAM_TYPE_FILE_SCAN\x10\t\x12\x1c\n" +
	"\x18STREAM_TYPE_FILE_ARCHIVE\x10\n" +
	"\x12\x1d\n" +
	"\x19STREAM_TYPE_AGENT_UPGRADE\x10\v\x12\x1b\n" +
	"\x17STREAM_TYPE_PLUGIN_MGMT\x10\fB2Z0github.com/WangYihang/Platypus/pkg/proto/v2;v2pbb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_proto_goTypes = []any{
	(StreamType)(0),      // 0: platypus.v2.StreamType
	(*StreamHeader)(nil), // 1: platypus.v2.StreamHeader
	(*StreamAccept)(nil), // 2: platypus.v2.StreamAccept
	(*StreamReject)(nil), // 3: platypus.v2.StreamReject
}
var file_common_proto_depIdxs = []int32{
	0, // 0: platypus.v2.StreamHeader.type:type_name -> platypus.v2.StreamType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
