// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: enroll.proto

package v2pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One of `pat` or mTLS (out-of-band, from the TLS layer) proves
	// who the caller is. When both are empty, server rejects.
	Pat string `protobuf:"bytes,1,opt,name=pat,proto3" json:"pat,omitempty"`
	// PEM-encoded PKCS#10 certificate signing request. The subject
	// is ignored; server rewrites it with the final agent_id and
	// project id.
	CsrPem []byte `protobuf:"bytes,2,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	// Optional agent-reported identifying info (stamped into the
	// cert SAN / audit log). The server trusts PAT-bound project
	// over agent-reported fields.
	Hostname      string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	MachineId     string `protobuf:"bytes,4,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	AgentVersion  string `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_enroll_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enroll_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_enroll_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetPat() string {
	if x != nil {
		return x.Pat
	}
	return ""
}

func (x *EnrollRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

func (x *EnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EnrollRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *EnrollRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type EnrollResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PEM-encoded agent leaf certificate, signed by the project CA.
	CertPem []byte `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	// PEM-encoded chain of issuer certs ending at the project root.
	// Agents must store this and use it as ClientCAs when they
	// later want to verify peer certs (e.g. in mesh).
	CaPem []byte `protobuf:"bytes,2,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	// Stable agent id the server bound the cert to. Also appears in
	// the cert CN.
	AgentId string `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Project id; also appears in the cert SAN.
	ProjectId string `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Unix seconds at which the cert expires. Agents should schedule
	// a renewal before this.
	CertExpiresUnix int64 `protobuf:"varint,5,opt,name=cert_expires_unix,json=certExpiresUnix,proto3" json:"cert_expires_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_enroll_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enroll_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_enroll_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetCertPem() []byte {
	if x != nil {
		return x.CertPem
	}
	return nil
}

func (x *EnrollResponse) GetCaPem() []byte {
	if x != nil {
		return x.CaPem
	}
	return nil
}

func (x *EnrollResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EnrollResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *EnrollResponse) GetCertExpiresUnix() int64 {
	if x != nil {
		return x.CertExpiresUnix
	}
	return 0
}

var File_enroll_proto protoreflect.FileDescriptor

const file_enroll_proto_rawDesc = "" +
	"\n" +
	"\fenroll.proto\x12\vplatypus.v2\"\x9a\x01\n" +
	"\rEnrollRequest\x12\x10\n" +
	"\x03pat\x18\x01 \x01(\tR\x03pat\x12\x17\n" +
	"\acsr_pem\x18\x02 \x01(\fR\x06csrPem\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x04 \x01(\tR\tmachineId\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\"\xa8\x01\n" +
	"\x0eEnrollResponse\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\fR\acertPem\x12\x15\n" +
	"\x06ca_pem\x18\x02 \x01(\fR\x05caPem\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tR\tprojectId\x12*\n" +
	"\x11cert_expires_unix\x18\x05 \x01(\x03R\x0fcertExpiresUnixB2Z0github.com/WangYihang/Platypus/pkg/proto/v2;v2pbb\x06proto3"

var (
	file_enroll_proto_rawDescOnce sync.Once
	file_enroll_proto_rawDescData []byte
)

func file_enroll_proto_rawDescGZIP() []byte {
	file_enroll_proto_rawDescOnce.Do(func() {
		file_enroll_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enroll_proto_rawDesc), len(file_enroll_proto_rawDesc)))
	})
	return file_enroll_proto_rawDescData
}

var file_enroll_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_enroll_proto_goTypes = []any{
	(*EnrollRequest)(nil),  // 0: platypus.v2.EnrollRequest
	(*EnrollResponse)(nil), // 1: platypus.v2.EnrollResponse
}
var file_enroll_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enroll_proto_init() }
func file_enroll_proto_init() {
	if File_enroll_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enroll_proto_rawDesc), len(file_enroll_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enroll_proto_goTypes,
		DependencyIndexes: file_enroll_proto_depIdxs,
		MessageInfos:      file_enroll_proto_msgTypes,
	}.Build()
	File_enroll_proto = out.File
	file_enroll_proto_goTypes = nil
	file_enroll_proto_depIdxs = nil
}
