// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: host_services.proto

package v2pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostServices_Log_FullMethodName          = "/platypus.v2.HostServices/Log"
	HostServices_KVGet_FullMethodName        = "/platypus.v2.HostServices/KVGet"
	HostServices_KVPut_FullMethodName        = "/platypus.v2.HostServices/KVPut"
	HostServices_FSRead_FullMethodName       = "/platypus.v2.HostServices/FSRead"
	HostServices_FSReadRange_FullMethodName  = "/platypus.v2.HostServices/FSReadRange"
	HostServices_FSListDir_FullMethodName    = "/platypus.v2.HostServices/FSListDir"
	HostServices_FSStat_FullMethodName       = "/platypus.v2.HostServices/FSStat"
	HostServices_FSWrite_FullMethodName      = "/platypus.v2.HostServices/FSWrite"
	HostServices_FSWriteRange_FullMethodName = "/platypus.v2.HostServices/FSWriteRange"
	HostServices_FSMkdir_FullMethodName      = "/platypus.v2.HostServices/FSMkdir"
	HostServices_FSChmod_FullMethodName      = "/platypus.v2.HostServices/FSChmod"
	HostServices_FSDelete_FullMethodName     = "/platypus.v2.HostServices/FSDelete"
	HostServices_FSRename_FullMethodName     = "/platypus.v2.HostServices/FSRename"
	HostServices_Exec_FullMethodName         = "/platypus.v2.HostServices/Exec"
	HostServices_HTTP_FullMethodName         = "/platypus.v2.HostServices/HTTP"
	HostServices_Uname_FullMethodName        = "/platypus.v2.HostServices/Uname"
	HostServices_NetDial_FullMethodName      = "/platypus.v2.HostServices/NetDial"
	HostServices_NetRelay_FullMethodName     = "/platypus.v2.HostServices/NetRelay"
	HostServices_NetClose_FullMethodName     = "/platypus.v2.HostServices/NetClose"
	HostServices_ProcessSpawn_FullMethodName = "/platypus.v2.HostServices/ProcessSpawn"
	HostServices_ProcessRelay_FullMethodName = "/platypus.v2.HostServices/ProcessRelay"
	HostServices_ProcessKill_FullMethodName  = "/platypus.v2.HostServices/ProcessKill"
)

// HostServicesClient is the client API for HostServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HostServices is the gRPC service the agent exposes for out-of-process
// plugins to call back. The plugin dials it on the Unix socket whose
// path is passed in env var PLATYPUS_HOST_SOCKET. Every method enforces
// the calling plugin's granted capabilities at the agent boundary; a
// denied call returns status PERMISSION_DENIED with the message
// "capability_denied: <cap-id>".
//
// Authentication: the host socket is dialed only by the spawned plugin
// process (Unix peer credentials prove uid; the agent rejects any
// connection from a uid other than the plugin's). No bearer tokens.
//
// Wire shapes are the gRPC counterpart of the wasm host_* JSON
// envelopes; one method per wasm host fn family. Agent-side
// implementations share the same pure-Go core as the wasm host fns
// — see internal/agent/plugin/host_*.go.
type HostServicesClient interface {
	// Logging
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Per-plugin key/value (cap: kv)
	KVGet(ctx context.Context, in *KVGetRequest, opts ...grpc.CallOption) (*KVGetResponse, error)
	KVPut(ctx context.Context, in *KVPutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Filesystem read (cap: fs.read)
	FSRead(ctx context.Context, in *FSReadHostRequest, opts ...grpc.CallOption) (*FSReadHostResponse, error)
	FSReadRange(ctx context.Context, in *FSReadRangeHostRequest, opts ...grpc.CallOption) (*FSReadHostResponse, error)
	FSListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error)
	FSStat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
	// Filesystem write (cap: fs.write)
	FSWrite(ctx context.Context, in *FSWriteHostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	FSWriteRange(ctx context.Context, in *FSWriteRangeHostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	FSMkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*MkdirResponse, error)
	FSChmod(ctx context.Context, in *ChmodRequest, opts ...grpc.CallOption) (*ChmodResponse, error)
	FSDelete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	FSRename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*RenameResponse, error)
	// Synchronous command execution (cap: exec). Reuses ExecRequest/
	// Response from rpc.proto so wasm and process runtimes report
	// identical shapes.
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	// Outbound HTTP (cap: net.http)
	HTTP(ctx context.Context, in *HostHTTPRequest, opts ...grpc.CallOption) (*HostHTTPResponse, error)
	// Host snapshot (cap: sysinfo)
	Uname(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HostUnameResponse, error)
	// Outbound TCP dial + bidirectional byte relay (cap: net.dial).
	// Client opens NetRelay after NetDial returns a handle; the first
	// outbound chunk the client sends MUST carry the handle id, and
	// subsequent chunks may have handle=0 (already established). The
	// server splices bytes between the dialed conn and the gRPC stream.
	NetDial(ctx context.Context, in *NetDialHostRequest, opts ...grpc.CallOption) (*NetDialHostResponse, error)
	NetRelay(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NetRelayChunk, NetRelayChunk], error)
	NetClose(ctx context.Context, in *NetCloseHostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Streaming process spawn + relay (cap: process). Same handle-id
	// rule as NetRelay. Plugins send stdin / resize chunks; the agent
	// returns stdout / stderr / exit chunks.
	ProcessSpawn(ctx context.Context, in *ProcessSpawnHostRequest, opts ...grpc.CallOption) (*ProcessSpawnHostResponse, error)
	ProcessRelay(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProcessRelayChunk, ProcessRelayChunk], error)
	ProcessKill(ctx context.Context, in *ProcessKillHostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type hostServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewHostServicesClient(cc grpc.ClientConnInterface) HostServicesClient {
	return &hostServicesClient{cc}
}

func (c *hostServicesClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, HostServices_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) KVGet(ctx context.Context, in *KVGetRequest, opts ...grpc.CallOption) (*KVGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KVGetResponse)
	err := c.cc.Invoke(ctx, HostServices_KVGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) KVPut(ctx context.Context, in *KVPutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, HostServices_KVPut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) FSRead(ctx context.Context, in *FSReadHostRequest, opts ...grpc.CallOption) (*FSReadHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FSReadHostResponse)
	err := c.cc.Invoke(ctx, HostServices_FSRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) FSReadRange(ctx context.Context, in *FSReadRangeHostRequest, opts ...grpc.CallOption) (*FSReadHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FSReadHostResponse)
	err := c.cc.Invoke(ctx, HostServices_FSReadRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) FSListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDirResponse)
	err := c.cc.Invoke(ctx, HostServices_FSListDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) FSStat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, HostServices_FSStat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) FSWrite(ctx context.Context, in *FSWriteHostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, HostServices_FSWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) FSWriteRange(ctx context.Context, in *FSWriteRangeHostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, HostServices_FSWriteRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) FSMkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*MkdirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MkdirResponse)
	err := c.cc.Invoke(ctx, HostServices_FSMkdir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) FSChmod(ctx context.Context, in *ChmodRequest, opts ...grpc.CallOption) (*ChmodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChmodResponse)
	err := c.cc.Invoke(ctx, HostServices_FSChmod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) FSDelete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, HostServices_FSDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) FSRename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*RenameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameResponse)
	err := c.cc.Invoke(ctx, HostServices_FSRename_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, HostServices_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) HTTP(ctx context.Context, in *HostHTTPRequest, opts ...grpc.CallOption) (*HostHTTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostHTTPResponse)
	err := c.cc.Invoke(ctx, HostServices_HTTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) Uname(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HostUnameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostUnameResponse)
	err := c.cc.Invoke(ctx, HostServices_Uname_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) NetDial(ctx context.Context, in *NetDialHostRequest, opts ...grpc.CallOption) (*NetDialHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetDialHostResponse)
	err := c.cc.Invoke(ctx, HostServices_NetDial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) NetRelay(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NetRelayChunk, NetRelayChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HostServices_ServiceDesc.Streams[0], HostServices_NetRelay_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NetRelayChunk, NetRelayChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostServices_NetRelayClient = grpc.BidiStreamingClient[NetRelayChunk, NetRelayChunk]

func (c *hostServicesClient) NetClose(ctx context.Context, in *NetCloseHostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, HostServices_NetClose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) ProcessSpawn(ctx context.Context, in *ProcessSpawnHostRequest, opts ...grpc.CallOption) (*ProcessSpawnHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessSpawnHostResponse)
	err := c.cc.Invoke(ctx, HostServices_ProcessSpawn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) ProcessRelay(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProcessRelayChunk, ProcessRelayChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HostServices_ServiceDesc.Streams[1], HostServices_ProcessRelay_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProcessRelayChunk, ProcessRelayChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostServices_ProcessRelayClient = grpc.BidiStreamingClient[ProcessRelayChunk, ProcessRelayChunk]

func (c *hostServicesClient) ProcessKill(ctx context.Context, in *ProcessKillHostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, HostServices_ProcessKill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServicesServer is the server API for HostServices service.
// All implementations must embed UnimplementedHostServicesServer
// for forward compatibility.
//
// HostServices is the gRPC service the agent exposes for out-of-process
// plugins to call back. The plugin dials it on the Unix socket whose
// path is passed in env var PLATYPUS_HOST_SOCKET. Every method enforces
// the calling plugin's granted capabilities at the agent boundary; a
// denied call returns status PERMISSION_DENIED with the message
// "capability_denied: <cap-id>".
//
// Authentication: the host socket is dialed only by the spawned plugin
// process (Unix peer credentials prove uid; the agent rejects any
// connection from a uid other than the plugin's). No bearer tokens.
//
// Wire shapes are the gRPC counterpart of the wasm host_* JSON
// envelopes; one method per wasm host fn family. Agent-side
// implementations share the same pure-Go core as the wasm host fns
// — see internal/agent/plugin/host_*.go.
type HostServicesServer interface {
	// Logging
	Log(context.Context, *LogRequest) (*emptypb.Empty, error)
	// Per-plugin key/value (cap: kv)
	KVGet(context.Context, *KVGetRequest) (*KVGetResponse, error)
	KVPut(context.Context, *KVPutRequest) (*emptypb.Empty, error)
	// Filesystem read (cap: fs.read)
	FSRead(context.Context, *FSReadHostRequest) (*FSReadHostResponse, error)
	FSReadRange(context.Context, *FSReadRangeHostRequest) (*FSReadHostResponse, error)
	FSListDir(context.Context, *ListDirRequest) (*ListDirResponse, error)
	FSStat(context.Context, *StatRequest) (*StatResponse, error)
	// Filesystem write (cap: fs.write)
	FSWrite(context.Context, *FSWriteHostRequest) (*emptypb.Empty, error)
	FSWriteRange(context.Context, *FSWriteRangeHostRequest) (*emptypb.Empty, error)
	FSMkdir(context.Context, *MkdirRequest) (*MkdirResponse, error)
	FSChmod(context.Context, *ChmodRequest) (*ChmodResponse, error)
	FSDelete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	FSRename(context.Context, *RenameRequest) (*RenameResponse, error)
	// Synchronous command execution (cap: exec). Reuses ExecRequest/
	// Response from rpc.proto so wasm and process runtimes report
	// identical shapes.
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	// Outbound HTTP (cap: net.http)
	HTTP(context.Context, *HostHTTPRequest) (*HostHTTPResponse, error)
	// Host snapshot (cap: sysinfo)
	Uname(context.Context, *emptypb.Empty) (*HostUnameResponse, error)
	// Outbound TCP dial + bidirectional byte relay (cap: net.dial).
	// Client opens NetRelay after NetDial returns a handle; the first
	// outbound chunk the client sends MUST carry the handle id, and
	// subsequent chunks may have handle=0 (already established). The
	// server splices bytes between the dialed conn and the gRPC stream.
	NetDial(context.Context, *NetDialHostRequest) (*NetDialHostResponse, error)
	NetRelay(grpc.BidiStreamingServer[NetRelayChunk, NetRelayChunk]) error
	NetClose(context.Context, *NetCloseHostRequest) (*emptypb.Empty, error)
	// Streaming process spawn + relay (cap: process). Same handle-id
	// rule as NetRelay. Plugins send stdin / resize chunks; the agent
	// returns stdout / stderr / exit chunks.
	ProcessSpawn(context.Context, *ProcessSpawnHostRequest) (*ProcessSpawnHostResponse, error)
	ProcessRelay(grpc.BidiStreamingServer[ProcessRelayChunk, ProcessRelayChunk]) error
	ProcessKill(context.Context, *ProcessKillHostRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedHostServicesServer()
}

// UnimplementedHostServicesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostServicesServer struct{}

func (UnimplementedHostServicesServer) Log(context.Context, *LogRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedHostServicesServer) KVGet(context.Context, *KVGetRequest) (*KVGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KVGet not implemented")
}
func (UnimplementedHostServicesServer) KVPut(context.Context, *KVPutRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method KVPut not implemented")
}
func (UnimplementedHostServicesServer) FSRead(context.Context, *FSReadHostRequest) (*FSReadHostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FSRead not implemented")
}
func (UnimplementedHostServicesServer) FSReadRange(context.Context, *FSReadRangeHostRequest) (*FSReadHostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FSReadRange not implemented")
}
func (UnimplementedHostServicesServer) FSListDir(context.Context, *ListDirRequest) (*ListDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FSListDir not implemented")
}
func (UnimplementedHostServicesServer) FSStat(context.Context, *StatRequest) (*StatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FSStat not implemented")
}
func (UnimplementedHostServicesServer) FSWrite(context.Context, *FSWriteHostRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method FSWrite not implemented")
}
func (UnimplementedHostServicesServer) FSWriteRange(context.Context, *FSWriteRangeHostRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method FSWriteRange not implemented")
}
func (UnimplementedHostServicesServer) FSMkdir(context.Context, *MkdirRequest) (*MkdirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FSMkdir not implemented")
}
func (UnimplementedHostServicesServer) FSChmod(context.Context, *ChmodRequest) (*ChmodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FSChmod not implemented")
}
func (UnimplementedHostServicesServer) FSDelete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FSDelete not implemented")
}
func (UnimplementedHostServicesServer) FSRename(context.Context, *RenameRequest) (*RenameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FSRename not implemented")
}
func (UnimplementedHostServicesServer) Exec(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedHostServicesServer) HTTP(context.Context, *HostHTTPRequest) (*HostHTTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HTTP not implemented")
}
func (UnimplementedHostServicesServer) Uname(context.Context, *emptypb.Empty) (*HostUnameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Uname not implemented")
}
func (UnimplementedHostServicesServer) NetDial(context.Context, *NetDialHostRequest) (*NetDialHostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NetDial not implemented")
}
func (UnimplementedHostServicesServer) NetRelay(grpc.BidiStreamingServer[NetRelayChunk, NetRelayChunk]) error {
	return status.Error(codes.Unimplemented, "method NetRelay not implemented")
}
func (UnimplementedHostServicesServer) NetClose(context.Context, *NetCloseHostRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method NetClose not implemented")
}
func (UnimplementedHostServicesServer) ProcessSpawn(context.Context, *ProcessSpawnHostRequest) (*ProcessSpawnHostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessSpawn not implemented")
}
func (UnimplementedHostServicesServer) ProcessRelay(grpc.BidiStreamingServer[ProcessRelayChunk, ProcessRelayChunk]) error {
	return status.Error(codes.Unimplemented, "method ProcessRelay not implemented")
}
func (UnimplementedHostServicesServer) ProcessKill(context.Context, *ProcessKillHostRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessKill not implemented")
}
func (UnimplementedHostServicesServer) mustEmbedUnimplementedHostServicesServer() {}
func (UnimplementedHostServicesServer) testEmbeddedByValue()                      {}

// UnsafeHostServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServicesServer will
// result in compilation errors.
type UnsafeHostServicesServer interface {
	mustEmbedUnimplementedHostServicesServer()
}

func RegisterHostServicesServer(s grpc.ServiceRegistrar, srv HostServicesServer) {
	// If the following call panics, it indicates UnimplementedHostServicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostServices_ServiceDesc, srv)
}

func _HostServices_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_KVGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).KVGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_KVGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).KVGet(ctx, req.(*KVGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_KVPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).KVPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_KVPut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).KVPut(ctx, req.(*KVPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_FSRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FSReadHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).FSRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_FSRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).FSRead(ctx, req.(*FSReadHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_FSReadRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FSReadRangeHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).FSReadRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_FSReadRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).FSReadRange(ctx, req.(*FSReadRangeHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_FSListDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).FSListDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_FSListDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).FSListDir(ctx, req.(*ListDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_FSStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).FSStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_FSStat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).FSStat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_FSWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FSWriteHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).FSWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_FSWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).FSWrite(ctx, req.(*FSWriteHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_FSWriteRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FSWriteRangeHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).FSWriteRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_FSWriteRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).FSWriteRange(ctx, req.(*FSWriteRangeHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_FSMkdir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MkdirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).FSMkdir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_FSMkdir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).FSMkdir(ctx, req.(*MkdirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_FSChmod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChmodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).FSChmod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_FSChmod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).FSChmod(ctx, req.(*ChmodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_FSDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).FSDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_FSDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).FSDelete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_FSRename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).FSRename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_FSRename_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).FSRename(ctx, req.(*RenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_HTTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostHTTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).HTTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_HTTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).HTTP(ctx, req.(*HostHTTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_Uname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).Uname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_Uname_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).Uname(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_NetDial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetDialHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).NetDial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_NetDial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).NetDial(ctx, req.(*NetDialHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_NetRelay_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HostServicesServer).NetRelay(&grpc.GenericServerStream[NetRelayChunk, NetRelayChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostServices_NetRelayServer = grpc.BidiStreamingServer[NetRelayChunk, NetRelayChunk]

func _HostServices_NetClose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetCloseHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).NetClose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_NetClose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).NetClose(ctx, req.(*NetCloseHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_ProcessSpawn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessSpawnHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).ProcessSpawn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_ProcessSpawn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).ProcessSpawn(ctx, req.(*ProcessSpawnHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_ProcessRelay_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HostServicesServer).ProcessRelay(&grpc.GenericServerStream[ProcessRelayChunk, ProcessRelayChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostServices_ProcessRelayServer = grpc.BidiStreamingServer[ProcessRelayChunk, ProcessRelayChunk]

func _HostServices_ProcessKill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessKillHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).ProcessKill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_ProcessKill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).ProcessKill(ctx, req.(*ProcessKillHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostServices_ServiceDesc is the grpc.ServiceDesc for HostServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platypus.v2.HostServices",
	HandlerType: (*HostServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Log",
			Handler:    _HostServices_Log_Handler,
		},
		{
			MethodName: "KVGet",
			Handler:    _HostServices_KVGet_Handler,
		},
		{
			MethodName: "KVPut",
			Handler:    _HostServices_KVPut_Handler,
		},
		{
			MethodName: "FSRead",
			Handler:    _HostServices_FSRead_Handler,
		},
		{
			MethodName: "FSReadRange",
			Handler:    _HostServices_FSReadRange_Handler,
		},
		{
			MethodName: "FSListDir",
			Handler:    _HostServices_FSListDir_Handler,
		},
		{
			MethodName: "FSStat",
			Handler:    _HostServices_FSStat_Handler,
		},
		{
			MethodName: "FSWrite",
			Handler:    _HostServices_FSWrite_Handler,
		},
		{
			MethodName: "FSWriteRange",
			Handler:    _HostServices_FSWriteRange_Handler,
		},
		{
			MethodName: "FSMkdir",
			Handler:    _HostServices_FSMkdir_Handler,
		},
		{
			MethodName: "FSChmod",
			Handler:    _HostServices_FSChmod_Handler,
		},
		{
			MethodName: "FSDelete",
			Handler:    _HostServices_FSDelete_Handler,
		},
		{
			MethodName: "FSRename",
			Handler:    _HostServices_FSRename_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _HostServices_Exec_Handler,
		},
		{
			MethodName: "HTTP",
			Handler:    _HostServices_HTTP_Handler,
		},
		{
			MethodName: "Uname",
			Handler:    _HostServices_Uname_Handler,
		},
		{
			MethodName: "NetDial",
			Handler:    _HostServices_NetDial_Handler,
		},
		{
			MethodName: "NetClose",
			Handler:    _HostServices_NetClose_Handler,
		},
		{
			MethodName: "ProcessSpawn",
			Handler:    _HostServices_ProcessSpawn_Handler,
		},
		{
			MethodName: "ProcessKill",
			Handler:    _HostServices_ProcessKill_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "NetRelay",
			Handler:       _HostServices_NetRelay_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ProcessRelay",
			Handler:       _HostServices_ProcessRelay_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "host_services.proto",
}
