// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: mesh.proto

package v2pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MeshStreamKind int32

const (
	MeshStreamKind_MESH_STREAM_KIND_UNSPECIFIED      MeshStreamKind = 0
	MeshStreamKind_MESH_STREAM_KIND_BOOTSTRAP_SERVER MeshStreamKind = 1
)

// Enum value maps for MeshStreamKind.
var (
	MeshStreamKind_name = map[int32]string{
		0: "MESH_STREAM_KIND_UNSPECIFIED",
		1: "MESH_STREAM_KIND_BOOTSTRAP_SERVER",
	}
	MeshStreamKind_value = map[string]int32{
		"MESH_STREAM_KIND_UNSPECIFIED":      0,
		"MESH_STREAM_KIND_BOOTSTRAP_SERVER": 1,
	}
)

func (x MeshStreamKind) Enum() *MeshStreamKind {
	p := new(MeshStreamKind)
	*p = x
	return p
}

func (x MeshStreamKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MeshStreamKind) Descriptor() protoreflect.EnumDescriptor {
	return file_mesh_proto_enumTypes[0].Descriptor()
}

func (MeshStreamKind) Type() protoreflect.EnumType {
	return &file_mesh_proto_enumTypes[0]
}

func (x MeshStreamKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MeshStreamKind.Descriptor instead.
func (MeshStreamKind) EnumDescriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{0}
}

// MeshEnvelope is the top-level mesh frame. One envelope per send.
type MeshEnvelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Version   uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                     // mesh protocol version (current = 1)
	RequestId string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // UUID for request/response correlation
	Timestamp int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // unix nanoseconds
	// Routing fields. target_node empty means "for the immediate
	// peer on this link"; otherwise the receiver forwards along its
	// routing table toward that node, decrementing ttl.
	SourceNode string `protobuf:"bytes,4,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	TargetNode string `protobuf:"bytes,5,opt,name=target_node,json=targetNode,proto3" json:"target_node,omitempty"`
	Ttl        uint32 `protobuf:"varint,6,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*MeshEnvelope_Hello
	//	*MeshEnvelope_HelloAck
	//	*MeshEnvelope_HelloFinish
	//	*MeshEnvelope_Keepalive
	//	*MeshEnvelope_PeerAnnounce
	//	*MeshEnvelope_PeerDelta
	//	*MeshEnvelope_Lsa
	//	*MeshEnvelope_Unreachable
	//	*MeshEnvelope_StreamOpen
	//	*MeshEnvelope_StreamOpenAck
	//	*MeshEnvelope_StreamData
	//	*MeshEnvelope_StreamClose
	//	*MeshEnvelope_Opaque
	Payload       isMeshEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshEnvelope) Reset() {
	*x = MeshEnvelope{}
	mi := &file_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshEnvelope) ProtoMessage() {}

func (x *MeshEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshEnvelope.ProtoReflect.Descriptor instead.
func (*MeshEnvelope) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *MeshEnvelope) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MeshEnvelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MeshEnvelope) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MeshEnvelope) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

func (x *MeshEnvelope) GetTargetNode() string {
	if x != nil {
		return x.TargetNode
	}
	return ""
}

func (x *MeshEnvelope) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *MeshEnvelope) GetPayload() isMeshEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MeshEnvelope) GetHello() *MeshHello {
	if x != nil {
		if x, ok := x.Payload.(*MeshEnvelope_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *MeshEnvelope) GetHelloAck() *MeshHelloAck {
	if x != nil {
		if x, ok := x.Payload.(*MeshEnvelope_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *MeshEnvelope) GetHelloFinish() *MeshHelloFinish {
	if x != nil {
		if x, ok := x.Payload.(*MeshEnvelope_HelloFinish); ok {
			return x.HelloFinish
		}
	}
	return nil
}

func (x *MeshEnvelope) GetKeepalive() *MeshKeepalive {
	if x != nil {
		if x, ok := x.Payload.(*MeshEnvelope_Keepalive); ok {
			return x.Keepalive
		}
	}
	return nil
}

func (x *MeshEnvelope) GetPeerAnnounce() *MeshPeerAnnounce {
	if x != nil {
		if x, ok := x.Payload.(*MeshEnvelope_PeerAnnounce); ok {
			return x.PeerAnnounce
		}
	}
	return nil
}

func (x *MeshEnvelope) GetPeerDelta() *MeshPeerDelta {
	if x != nil {
		if x, ok := x.Payload.(*MeshEnvelope_PeerDelta); ok {
			return x.PeerDelta
		}
	}
	return nil
}

func (x *MeshEnvelope) GetLsa() *MeshLSA {
	if x != nil {
		if x, ok := x.Payload.(*MeshEnvelope_Lsa); ok {
			return x.Lsa
		}
	}
	return nil
}

func (x *MeshEnvelope) GetUnreachable() *MeshUnreachable {
	if x != nil {
		if x, ok := x.Payload.(*MeshEnvelope_Unreachable); ok {
			return x.Unreachable
		}
	}
	return nil
}

func (x *MeshEnvelope) GetStreamOpen() *MeshStreamOpen {
	if x != nil {
		if x, ok := x.Payload.(*MeshEnvelope_StreamOpen); ok {
			return x.StreamOpen
		}
	}
	return nil
}

func (x *MeshEnvelope) GetStreamOpenAck() *MeshStreamOpenAck {
	if x != nil {
		if x, ok := x.Payload.(*MeshEnvelope_StreamOpenAck); ok {
			return x.StreamOpenAck
		}
	}
	return nil
}

func (x *MeshEnvelope) GetStreamData() *MeshStreamData {
	if x != nil {
		if x, ok := x.Payload.(*MeshEnvelope_StreamData); ok {
			return x.StreamData
		}
	}
	return nil
}

func (x *MeshEnvelope) GetStreamClose() *MeshStreamClose {
	if x != nil {
		if x, ok := x.Payload.(*MeshEnvelope_StreamClose); ok {
			return x.StreamClose
		}
	}
	return nil
}

func (x *MeshEnvelope) GetOpaque() []byte {
	if x != nil {
		if x, ok := x.Payload.(*MeshEnvelope_Opaque); ok {
			return x.Opaque
		}
	}
	return nil
}

type isMeshEnvelope_Payload interface {
	isMeshEnvelope_Payload()
}

type MeshEnvelope_Hello struct {
	// Link handshake + keepalive (handshake is Noise_XXpsk3;
	// Hello / HelloAck / HelloFinish are the three Noise messages
	// plus each carries an application payload after the session
	// key is established).
	Hello *MeshHello `protobuf:"bytes,10,opt,name=hello,proto3,oneof"`
}

type MeshEnvelope_HelloAck struct {
	HelloAck *MeshHelloAck `protobuf:"bytes,11,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type MeshEnvelope_HelloFinish struct {
	HelloFinish *MeshHelloFinish `protobuf:"bytes,13,opt,name=hello_finish,json=helloFinish,proto3,oneof"`
}

type MeshEnvelope_Keepalive struct {
	Keepalive *MeshKeepalive `protobuf:"bytes,12,opt,name=keepalive,proto3,oneof"`
}

type MeshEnvelope_PeerAnnounce struct {
	// Peer-table gossip
	PeerAnnounce *MeshPeerAnnounce `protobuf:"bytes,20,opt,name=peer_announce,json=peerAnnounce,proto3,oneof"`
}

type MeshEnvelope_PeerDelta struct {
	PeerDelta *MeshPeerDelta `protobuf:"bytes,21,opt,name=peer_delta,json=peerDelta,proto3,oneof"`
}

type MeshEnvelope_Lsa struct {
	// Link-state routing
	Lsa *MeshLSA `protobuf:"bytes,30,opt,name=lsa,proto3,oneof"`
}

type MeshEnvelope_Unreachable struct {
	Unreachable *MeshUnreachable `protobuf:"bytes,31,opt,name=unreachable,proto3,oneof"`
}

type MeshEnvelope_StreamOpen struct {
	// Multiplexed byte streams for bootstrap
	StreamOpen *MeshStreamOpen `protobuf:"bytes,40,opt,name=stream_open,json=streamOpen,proto3,oneof"`
}

type MeshEnvelope_StreamOpenAck struct {
	StreamOpenAck *MeshStreamOpenAck `protobuf:"bytes,41,opt,name=stream_open_ack,json=streamOpenAck,proto3,oneof"`
}

type MeshEnvelope_StreamData struct {
	StreamData *MeshStreamData `protobuf:"bytes,42,opt,name=stream_data,json=streamData,proto3,oneof"`
}

type MeshEnvelope_StreamClose struct {
	StreamClose *MeshStreamClose `protobuf:"bytes,43,opt,name=stream_close,json=streamClose,proto3,oneof"`
}

type MeshEnvelope_Opaque struct {
	// Opaque payload: reserved for non-mesh-control data that still
	// wants to ride the routing layer (end-to-end app messages,
	// routing-reachability tests). The node dispatcher hands these
	// off to the application-level PayloadHandler rather than
	// interpreting them.
	Opaque []byte `protobuf:"bytes,50,opt,name=opaque,proto3,oneof"`
}

func (*MeshEnvelope_Hello) isMeshEnvelope_Payload() {}

func (*MeshEnvelope_HelloAck) isMeshEnvelope_Payload() {}

func (*MeshEnvelope_HelloFinish) isMeshEnvelope_Payload() {}

func (*MeshEnvelope_Keepalive) isMeshEnvelope_Payload() {}

func (*MeshEnvelope_PeerAnnounce) isMeshEnvelope_Payload() {}

func (*MeshEnvelope_PeerDelta) isMeshEnvelope_Payload() {}

func (*MeshEnvelope_Lsa) isMeshEnvelope_Payload() {}

func (*MeshEnvelope_Unreachable) isMeshEnvelope_Payload() {}

func (*MeshEnvelope_StreamOpen) isMeshEnvelope_Payload() {}

func (*MeshEnvelope_StreamOpenAck) isMeshEnvelope_Payload() {}

func (*MeshEnvelope_StreamData) isMeshEnvelope_Payload() {}

func (*MeshEnvelope_StreamClose) isMeshEnvelope_Payload() {}

func (*MeshEnvelope_Opaque) isMeshEnvelope_Payload() {}

// NodeInfo is the minimal peer-table record: enough to attempt a
// connection plus the pubkey so recipients can re-derive + verify
// the node_id locally.
//
// Two identity modes coexist on the wire:
//
//   - self-certifying (legacy): node_id = DeriveNodeID(pubkey),
//     cert_pem empty. Receiver verifies via the hash relation.
//
//   - cert-bound     (v2):      node_id = the "platypus://agent/<id>"
//     SAN from cert_pem, and pubkey matches cert_pem's public key.
//     Receiver verifies the cert against a trusted project-CA pool
//     and reads the SAN.
//
// Both modes carry the same pubkey so LSA/gossip signatures verify
// identically; the only difference is where node_id comes from.
type NodeInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                                // cert-bound: SAN id; legacy: base32(sha256(pubkey))[:32]
	Pubkey           []byte                 `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`                                              // 32-byte Ed25519 public key
	Addresses        []string               `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`                                        // host:port entries the node listens on
	LastSeen         int64                  `protobuf:"varint,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`                         // unix seconds — observer's wall clock
	Role             string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`                                                  // "agent", "server", ...
	BootstrapService bool                   `protobuf:"varint,6,opt,name=bootstrap_service,json=bootstrapService,proto3" json:"bootstrap_service,omitempty"` // true if node accepts bootstrap streams
	CertPem          []byte                 `protobuf:"bytes,7,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`                             // project-CA-signed leaf; empty = legacy self-cert
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_mesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *NodeInfo) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *NodeInfo) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *NodeInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *NodeInfo) GetBootstrapService() bool {
	if x != nil {
		return x.BootstrapService
	}
	return false
}

func (x *NodeInfo) GetCertPem() []byte {
	if x != nil {
		return x.CertPem
	}
	return nil
}

// HandshakePayload is the application data wrapped inside the
// Noise handshake from HelloAck onward. It is encrypted + MAC'd
// by the Noise session.
type HandshakePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Ed25519Pubkey []byte                 `protobuf:"bytes,2,opt,name=ed25519_pubkey,json=ed25519Pubkey,proto3" json:"ed25519_pubkey,omitempty"` // must hash to node_id via DeriveNodeID
	Protocol      uint32                 `protobuf:"varint,3,opt,name=protocol,proto3" json:"protocol,omitempty"`                               // mesh protocol version (current = 1)
	Addresses     []string               `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`                              // advertised listen addresses
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakePayload) Reset() {
	*x = HandshakePayload{}
	mi := &file_mesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakePayload) ProtoMessage() {}

func (x *HandshakePayload) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakePayload.ProtoReflect.Descriptor instead.
func (*HandshakePayload) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakePayload) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HandshakePayload) GetEd25519Pubkey() []byte {
	if x != nil {
		return x.Ed25519Pubkey
	}
	return nil
}

func (x *HandshakePayload) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *HandshakePayload) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

// MeshHello = Noise message 1 (initiator → responder). Just the
// initiator's ephemeral; no payload.
type MeshHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoiseMsg      []byte                 `protobuf:"bytes,1,opt,name=noise_msg,json=noiseMsg,proto3" json:"noise_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshHello) Reset() {
	*x = MeshHello{}
	mi := &file_mesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshHello) ProtoMessage() {}

func (x *MeshHello) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshHello.ProtoReflect.Descriptor instead.
func (*MeshHello) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{3}
}

func (x *MeshHello) GetNoiseMsg() []byte {
	if x != nil {
		return x.NoiseMsg
	}
	return nil
}

// MeshHelloAck = Noise message 2 (responder → initiator). Carries
// the responder's ephemeral + static + a HandshakePayload
// advertising the responder's NodeID/Ed25519 pubkey/addresses.
type MeshHelloAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoiseMsg      []byte                 `protobuf:"bytes,1,opt,name=noise_msg,json=noiseMsg,proto3" json:"noise_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshHelloAck) Reset() {
	*x = MeshHelloAck{}
	mi := &file_mesh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshHelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshHelloAck) ProtoMessage() {}

func (x *MeshHelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshHelloAck.ProtoReflect.Descriptor instead.
func (*MeshHelloAck) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{4}
}

func (x *MeshHelloAck) GetNoiseMsg() []byte {
	if x != nil {
		return x.NoiseMsg
	}
	return nil
}

// MeshHelloFinish = Noise message 3 (initiator → responder).
// Carries the initiator's static + its HandshakePayload + finalises
// the PSK mix. After this, both sides hold paired CipherStates;
// mesh traffic continues in plaintext on the underlying TLS link.
type MeshHelloFinish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoiseMsg      []byte                 `protobuf:"bytes,1,opt,name=noise_msg,json=noiseMsg,proto3" json:"noise_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshHelloFinish) Reset() {
	*x = MeshHelloFinish{}
	mi := &file_mesh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshHelloFinish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshHelloFinish) ProtoMessage() {}

func (x *MeshHelloFinish) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshHelloFinish.ProtoReflect.Descriptor instead.
func (*MeshHelloFinish) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{5}
}

func (x *MeshHelloFinish) GetNoiseMsg() []byte {
	if x != nil {
		return x.NoiseMsg
	}
	return nil
}

// MeshKeepalive is a periodic heartbeat. Either side may send one;
// links with no traffic for ~90s are torn down. It doubles as the
// traffic-counter piggyback so the topology aggregator can light
// up edge weights and derive throughput via successive-tick deltas.
type MeshKeepalive struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SentAt           int64                  `protobuf:"varint,1,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"` // unix nanos, for RTT measurement
	LifetimeBytesIn  uint64                 `protobuf:"varint,2,opt,name=lifetime_bytes_in,json=lifetimeBytesIn,proto3" json:"lifetime_bytes_in,omitempty"`
	LifetimeBytesOut uint64                 `protobuf:"varint,3,opt,name=lifetime_bytes_out,json=lifetimeBytesOut,proto3" json:"lifetime_bytes_out,omitempty"`
	LifetimeMsgsIn   uint64                 `protobuf:"varint,4,opt,name=lifetime_msgs_in,json=lifetimeMsgsIn,proto3" json:"lifetime_msgs_in,omitempty"`
	LifetimeMsgsOut  uint64                 `protobuf:"varint,5,opt,name=lifetime_msgs_out,json=lifetimeMsgsOut,proto3" json:"lifetime_msgs_out,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MeshKeepalive) Reset() {
	*x = MeshKeepalive{}
	mi := &file_mesh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshKeepalive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshKeepalive) ProtoMessage() {}

func (x *MeshKeepalive) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshKeepalive.ProtoReflect.Descriptor instead.
func (*MeshKeepalive) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{6}
}

func (x *MeshKeepalive) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

func (x *MeshKeepalive) GetLifetimeBytesIn() uint64 {
	if x != nil {
		return x.LifetimeBytesIn
	}
	return 0
}

func (x *MeshKeepalive) GetLifetimeBytesOut() uint64 {
	if x != nil {
		return x.LifetimeBytesOut
	}
	return 0
}

func (x *MeshKeepalive) GetLifetimeMsgsIn() uint64 {
	if x != nil {
		return x.LifetimeMsgsIn
	}
	return 0
}

func (x *MeshKeepalive) GetLifetimeMsgsOut() uint64 {
	if x != nil {
		return x.LifetimeMsgsOut
	}
	return 0
}

// MeshPeerAnnounce: sent once per direction after a handshake
// completes, carrying the sender's full known-peer table so the
// other side can quickly learn the wider mesh. Signed by the
// sender (origin_node_id) so the receiver can reject a forged
// announce from a relay that compromised an upstream link.
//
// origin_cert_pem is the sender's project-CA-signed leaf cert
// (when the sender runs in cert-bound mode). Receivers with a
// TrustedCAs pool configured chain this against the pool and
// read the SAN to verify origin_node_id; receivers without a
// pool (and legacy senders without the field) fall back to the
// DeriveNodeID(pubkey) == origin_node_id check.
type MeshPeerAnnounce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	OriginNodeId  string                 `protobuf:"bytes,2,opt,name=origin_node_id,json=originNodeId,proto3" json:"origin_node_id,omitempty"`
	Pubkey        []byte                 `protobuf:"bytes,3,opt,name=pubkey,proto3" json:"pubkey,omitempty"`                                      // must match origin_node_id (legacy) or cert SPKI
	Sig           []byte                 `protobuf:"bytes,4,opt,name=sig,proto3" json:"sig,omitempty"`                                            // Ed25519_sign(priv, canonical(announce without sig))
	OriginCertPem []byte                 `protobuf:"bytes,5,opt,name=origin_cert_pem,json=originCertPem,proto3" json:"origin_cert_pem,omitempty"` // project-CA-signed leaf; empty = legacy self-cert
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshPeerAnnounce) Reset() {
	*x = MeshPeerAnnounce{}
	mi := &file_mesh_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshPeerAnnounce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshPeerAnnounce) ProtoMessage() {}

func (x *MeshPeerAnnounce) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshPeerAnnounce.ProtoReflect.Descriptor instead.
func (*MeshPeerAnnounce) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{7}
}

func (x *MeshPeerAnnounce) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *MeshPeerAnnounce) GetOriginNodeId() string {
	if x != nil {
		return x.OriginNodeId
	}
	return ""
}

func (x *MeshPeerAnnounce) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *MeshPeerAnnounce) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *MeshPeerAnnounce) GetOriginCertPem() []byte {
	if x != nil {
		return x.OriginCertPem
	}
	return nil
}

// MeshPeerDelta: incremental update broadcast to every directly-
// connected neighbour when the sender's known-peer set changes.
// seq is monotonic per origin_node_id so receivers deduplicate
// across flooding paths. Signed by origin so floods can't be
// forged by intermediate hops. See MeshPeerAnnounce for the
// cert-mode vs. legacy semantics of origin_cert_pem.
type MeshPeerDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginNodeId  string                 `protobuf:"bytes,1,opt,name=origin_node_id,json=originNodeId,proto3" json:"origin_node_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Added         []*NodeInfo            `protobuf:"bytes,3,rep,name=added,proto3" json:"added,omitempty"`
	RemovedIds    []string               `protobuf:"bytes,4,rep,name=removed_ids,json=removedIds,proto3" json:"removed_ids,omitempty"`
	Ttl           uint32                 `protobuf:"varint,5,opt,name=ttl,proto3" json:"ttl,omitempty"`                                           // flood TTL, distinct from envelope.ttl
	Pubkey        []byte                 `protobuf:"bytes,6,opt,name=pubkey,proto3" json:"pubkey,omitempty"`                                      // must match origin_node_id (legacy) or cert SPKI
	Sig           []byte                 `protobuf:"bytes,7,opt,name=sig,proto3" json:"sig,omitempty"`                                            // Ed25519_sign(priv, canonical(delta without sig + ttl))
	OriginCertPem []byte                 `protobuf:"bytes,8,opt,name=origin_cert_pem,json=originCertPem,proto3" json:"origin_cert_pem,omitempty"` // project-CA-signed leaf; empty = legacy self-cert
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshPeerDelta) Reset() {
	*x = MeshPeerDelta{}
	mi := &file_mesh_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshPeerDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshPeerDelta) ProtoMessage() {}

func (x *MeshPeerDelta) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshPeerDelta.ProtoReflect.Descriptor instead.
func (*MeshPeerDelta) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{8}
}

func (x *MeshPeerDelta) GetOriginNodeId() string {
	if x != nil {
		return x.OriginNodeId
	}
	return ""
}

func (x *MeshPeerDelta) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MeshPeerDelta) GetAdded() []*NodeInfo {
	if x != nil {
		return x.Added
	}
	return nil
}

func (x *MeshPeerDelta) GetRemovedIds() []string {
	if x != nil {
		return x.RemovedIds
	}
	return nil
}

func (x *MeshPeerDelta) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *MeshPeerDelta) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *MeshPeerDelta) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *MeshPeerDelta) GetOriginCertPem() []byte {
	if x != nil {
		return x.OriginCertPem
	}
	return nil
}

// MeshLSA: link-state advertisement. Each node periodically (and on
// adjacency change) signs and floods a description of its directly
// connected neighbours. Only the node identified by origin_node_id
// can produce a valid signature; receivers discard duplicates by
// (origin_node_id, seq).
type MeshLSA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginNodeId  string                 `protobuf:"bytes,1,opt,name=origin_node_id,json=originNodeId,proto3" json:"origin_node_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`                              // monotonic per origin
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // unix seconds
	Links         []*MeshLSA_Link        `protobuf:"bytes,4,rep,name=links,proto3" json:"links,omitempty"`
	Pubkey        []byte                 `protobuf:"bytes,5,opt,name=pubkey,proto3" json:"pubkey,omitempty"` // must match origin_node_id (legacy) or cert SPKI
	Sig           []byte                 `protobuf:"bytes,6,opt,name=sig,proto3" json:"sig,omitempty"`       // Ed25519_sign(priv, canonical(lsa without sig))
	FloodTtl      uint32                 `protobuf:"varint,7,opt,name=flood_ttl,json=floodTtl,proto3" json:"flood_ttl,omitempty"`
	OriginCertPem []byte                 `protobuf:"bytes,8,opt,name=origin_cert_pem,json=originCertPem,proto3" json:"origin_cert_pem,omitempty"` // project-CA-signed leaf; empty = legacy self-cert
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshLSA) Reset() {
	*x = MeshLSA{}
	mi := &file_mesh_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshLSA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshLSA) ProtoMessage() {}

func (x *MeshLSA) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshLSA.ProtoReflect.Descriptor instead.
func (*MeshLSA) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{9}
}

func (x *MeshLSA) GetOriginNodeId() string {
	if x != nil {
		return x.OriginNodeId
	}
	return ""
}

func (x *MeshLSA) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MeshLSA) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *MeshLSA) GetLinks() []*MeshLSA_Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *MeshLSA) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *MeshLSA) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *MeshLSA) GetFloodTtl() uint32 {
	if x != nil {
		return x.FloodTtl
	}
	return 0
}

func (x *MeshLSA) GetOriginCertPem() []byte {
	if x != nil {
		return x.OriginCertPem
	}
	return nil
}

// MeshUnreachable: sent back along the reverse path when a
// forwarding node has no route for an envelope's target_node.
type MeshUnreachable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetNode    string                 `protobuf:"bytes,1,opt,name=target_node,json=targetNode,proto3" json:"target_node,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshUnreachable) Reset() {
	*x = MeshUnreachable{}
	mi := &file_mesh_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshUnreachable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshUnreachable) ProtoMessage() {}

func (x *MeshUnreachable) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshUnreachable.ProtoReflect.Descriptor instead.
func (*MeshUnreachable) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{10}
}

func (x *MeshUnreachable) GetTargetNode() string {
	if x != nil {
		return x.TargetNode
	}
	return ""
}

func (x *MeshUnreachable) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type MeshStreamOpen struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InitiatorNodeId string                 `protobuf:"bytes,1,opt,name=initiator_node_id,json=initiatorNodeId,proto3" json:"initiator_node_id,omitempty"`
	StreamId        uint64                 `protobuf:"varint,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	TargetNodeId    string                 `protobuf:"bytes,3,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	Kind            MeshStreamKind         `protobuf:"varint,4,opt,name=kind,proto3,enum=platypus.v2.MeshStreamKind" json:"kind,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MeshStreamOpen) Reset() {
	*x = MeshStreamOpen{}
	mi := &file_mesh_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshStreamOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshStreamOpen) ProtoMessage() {}

func (x *MeshStreamOpen) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshStreamOpen.ProtoReflect.Descriptor instead.
func (*MeshStreamOpen) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{11}
}

func (x *MeshStreamOpen) GetInitiatorNodeId() string {
	if x != nil {
		return x.InitiatorNodeId
	}
	return ""
}

func (x *MeshStreamOpen) GetStreamId() uint64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *MeshStreamOpen) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *MeshStreamOpen) GetKind() MeshStreamKind {
	if x != nil {
		return x.Kind
	}
	return MeshStreamKind_MESH_STREAM_KIND_UNSPECIFIED
}

type MeshStreamOpenAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InitiatorNodeId string                 `protobuf:"bytes,1,opt,name=initiator_node_id,json=initiatorNodeId,proto3" json:"initiator_node_id,omitempty"`
	StreamId        uint64                 `protobuf:"varint,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Ok              bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	Error           string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MeshStreamOpenAck) Reset() {
	*x = MeshStreamOpenAck{}
	mi := &file_mesh_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshStreamOpenAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshStreamOpenAck) ProtoMessage() {}

func (x *MeshStreamOpenAck) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshStreamOpenAck.ProtoReflect.Descriptor instead.
func (*MeshStreamOpenAck) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{12}
}

func (x *MeshStreamOpenAck) GetInitiatorNodeId() string {
	if x != nil {
		return x.InitiatorNodeId
	}
	return ""
}

func (x *MeshStreamOpenAck) GetStreamId() uint64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *MeshStreamOpenAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *MeshStreamOpenAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MeshStreamData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InitiatorNodeId string                 `protobuf:"bytes,1,opt,name=initiator_node_id,json=initiatorNodeId,proto3" json:"initiator_node_id,omitempty"`
	StreamId        uint64                 `protobuf:"varint,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Chunk           []byte                 `protobuf:"bytes,3,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Eof             bool                   `protobuf:"varint,4,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MeshStreamData) Reset() {
	*x = MeshStreamData{}
	mi := &file_mesh_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshStreamData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshStreamData) ProtoMessage() {}

func (x *MeshStreamData) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshStreamData.ProtoReflect.Descriptor instead.
func (*MeshStreamData) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{13}
}

func (x *MeshStreamData) GetInitiatorNodeId() string {
	if x != nil {
		return x.InitiatorNodeId
	}
	return ""
}

func (x *MeshStreamData) GetStreamId() uint64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *MeshStreamData) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *MeshStreamData) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type MeshStreamClose struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InitiatorNodeId string                 `protobuf:"bytes,1,opt,name=initiator_node_id,json=initiatorNodeId,proto3" json:"initiator_node_id,omitempty"`
	StreamId        uint64                 `protobuf:"varint,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MeshStreamClose) Reset() {
	*x = MeshStreamClose{}
	mi := &file_mesh_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshStreamClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshStreamClose) ProtoMessage() {}

func (x *MeshStreamClose) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshStreamClose.ProtoReflect.Descriptor instead.
func (*MeshStreamClose) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{14}
}

func (x *MeshStreamClose) GetInitiatorNodeId() string {
	if x != nil {
		return x.InitiatorNodeId
	}
	return ""
}

func (x *MeshStreamClose) GetStreamId() uint64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *MeshStreamClose) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type MeshLSA_Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // neighbour's node_id
	Cost          uint32                 `protobuf:"varint,2,opt,name=cost,proto3" json:"cost,omitempty"`                  // abstract cost (1 by default; RTT-based later)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshLSA_Link) Reset() {
	*x = MeshLSA_Link{}
	mi := &file_mesh_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshLSA_Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshLSA_Link) ProtoMessage() {}

func (x *MeshLSA_Link) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshLSA_Link.ProtoReflect.Descriptor instead.
func (*MeshLSA_Link) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{9, 0}
}

func (x *MeshLSA_Link) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MeshLSA_Link) GetCost() uint32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

var File_mesh_proto protoreflect.FileDescriptor

const file_mesh_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"mesh.proto\x12\vplatypus.v2\"\xc3\a\n" +
	"\fMeshEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vsource_node\x18\x04 \x01(\tR\n" +
	"sourceNode\x12\x1f\n" +
	"\vtarget_node\x18\x05 \x01(\tR\n" +
	"targetNode\x12\x10\n" +
	"\x03ttl\x18\x06 \x01(\rR\x03ttl\x12.\n" +
	"\x05hello\x18\n" +
	" \x01(\v2\x16.platypus.v2.MeshHelloH\x00R\x05hello\x128\n" +
	"\thello_ack\x18\v \x01(\v2\x19.platypus.v2.MeshHelloAckH\x00R\bhelloAck\x12A\n" +
	"\fhello_finish\x18\r \x01(\v2\x1c.platypus.v2.MeshHelloFinishH\x00R\vhelloFinish\x12:\n" +
	"\tkeepalive\x18\f \x01(\v2\x1a.platypus.v2.MeshKeepaliveH\x00R\tkeepalive\x12D\n" +
	"\rpeer_announce\x18\x14 \x01(\v2\x1d.platypus.v2.MeshPeerAnnounceH\x00R\fpeerAnnounce\x12;\n" +
	"\n" +
	"peer_delta\x18\x15 \x01(\v2\x1a.platypus.v2.MeshPeerDeltaH\x00R\tpeerDelta\x12(\n" +
	"\x03lsa\x18\x1e \x01(\v2\x14.platypus.v2.MeshLSAH\x00R\x03lsa\x12@\n" +
	"\vunreachable\x18\x1f \x01(\v2\x1c.platypus.v2.MeshUnreachableH\x00R\vunreachable\x12>\n" +
	"\vstream_open\x18( \x01(\v2\x1b.platypus.v2.MeshStreamOpenH\x00R\n" +
	"streamOpen\x12H\n" +
	"\x0fstream_open_ack\x18) \x01(\v2\x1e.platypus.v2.MeshStreamOpenAckH\x00R\rstreamOpenAck\x12>\n" +
	"\vstream_data\x18* \x01(\v2\x1b.platypus.v2.MeshStreamDataH\x00R\n" +
	"streamData\x12A\n" +
	"\fstream_close\x18+ \x01(\v2\x1c.platypus.v2.MeshStreamCloseH\x00R\vstreamClose\x12\x18\n" +
	"\x06opaque\x182 \x01(\fH\x00R\x06opaqueB\t\n" +
	"\apayload\"\xd2\x01\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06pubkey\x18\x02 \x01(\fR\x06pubkey\x12\x1c\n" +
	"\taddresses\x18\x03 \x03(\tR\taddresses\x12\x1b\n" +
	"\tlast_seen\x18\x04 \x01(\x03R\blastSeen\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12+\n" +
	"\x11bootstrap_service\x18\x06 \x01(\bR\x10bootstrapService\x12\x19\n" +
	"\bcert_pem\x18\a \x01(\fR\acertPem\"\x8c\x01\n" +
	"\x10HandshakePayload\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12%\n" +
	"\x0eed25519_pubkey\x18\x02 \x01(\fR\red25519Pubkey\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\rR\bprotocol\x12\x1c\n" +
	"\taddresses\x18\x04 \x03(\tR\taddresses\"(\n" +
	"\tMeshHello\x12\x1b\n" +
	"\tnoise_msg\x18\x01 \x01(\fR\bnoiseMsg\"+\n" +
	"\fMeshHelloAck\x12\x1b\n" +
	"\tnoise_msg\x18\x01 \x01(\fR\bnoiseMsg\".\n" +
	"\x0fMeshHelloFinish\x12\x1b\n" +
	"\tnoise_msg\x18\x01 \x01(\fR\bnoiseMsg\"\xd8\x01\n" +
	"\rMeshKeepalive\x12\x17\n" +
	"\asent_at\x18\x01 \x01(\x03R\x06sentAt\x12*\n" +
	"\x11lifetime_bytes_in\x18\x02 \x01(\x04R\x0flifetimeBytesIn\x12,\n" +
	"\x12lifetime_bytes_out\x18\x03 \x01(\x04R\x10lifetimeBytesOut\x12(\n" +
	"\x10lifetime_msgs_in\x18\x04 \x01(\x04R\x0elifetimeMsgsIn\x12*\n" +
	"\x11lifetime_msgs_out\x18\x05 \x01(\x04R\x0flifetimeMsgsOut\"\xb7\x01\n" +
	"\x10MeshPeerAnnounce\x12+\n" +
	"\x05nodes\x18\x01 \x03(\v2\x15.platypus.v2.NodeInfoR\x05nodes\x12$\n" +
	"\x0eorigin_node_id\x18\x02 \x01(\tR\foriginNodeId\x12\x16\n" +
	"\x06pubkey\x18\x03 \x01(\fR\x06pubkey\x12\x10\n" +
	"\x03sig\x18\x04 \x01(\fR\x03sig\x12&\n" +
	"\x0forigin_cert_pem\x18\x05 \x01(\fR\roriginCertPem\"\xf9\x01\n" +
	"\rMeshPeerDelta\x12$\n" +
	"\x0eorigin_node_id\x18\x01 \x01(\tR\foriginNodeId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12+\n" +
	"\x05added\x18\x03 \x03(\v2\x15.platypus.v2.NodeInfoR\x05added\x12\x1f\n" +
	"\vremoved_ids\x18\x04 \x03(\tR\n" +
	"removedIds\x12\x10\n" +
	"\x03ttl\x18\x05 \x01(\rR\x03ttl\x12\x16\n" +
	"\x06pubkey\x18\x06 \x01(\fR\x06pubkey\x12\x10\n" +
	"\x03sig\x18\a \x01(\fR\x03sig\x12&\n" +
	"\x0forigin_cert_pem\x18\b \x01(\fR\roriginCertPem\"\xb5\x02\n" +
	"\aMeshLSA\x12$\n" +
	"\x0eorigin_node_id\x18\x01 \x01(\tR\foriginNodeId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12/\n" +
	"\x05links\x18\x04 \x03(\v2\x19.platypus.v2.MeshLSA.LinkR\x05links\x12\x16\n" +
	"\x06pubkey\x18\x05 \x01(\fR\x06pubkey\x12\x10\n" +
	"\x03sig\x18\x06 \x01(\fR\x03sig\x12\x1b\n" +
	"\tflood_ttl\x18\a \x01(\rR\bfloodTtl\x12&\n" +
	"\x0forigin_cert_pem\x18\b \x01(\fR\roriginCertPem\x1a3\n" +
	"\x04Link\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04cost\x18\x02 \x01(\rR\x04cost\"J\n" +
	"\x0fMeshUnreachable\x12\x1f\n" +
	"\vtarget_node\x18\x01 \x01(\tR\n" +
	"targetNode\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xb0\x01\n" +
	"\x0eMeshStreamOpen\x12*\n" +
	"\x11initiator_node_id\x18\x01 \x01(\tR\x0finitiatorNodeId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\x04R\bstreamId\x12$\n" +
	"\x0etarget_node_id\x18\x03 \x01(\tR\ftargetNodeId\x12/\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x1b.platypus.v2.MeshStreamKindR\x04kind\"\x82\x01\n" +
	"\x11MeshStreamOpenAck\x12*\n" +
	"\x11initiator_node_id\x18\x01 \x01(\tR\x0finitiatorNodeId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\x04R\bstreamId\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x81\x01\n" +
	"\x0eMeshStreamData\x12*\n" +
	"\x11initiator_node_id\x18\x01 \x01(\tR\x0finitiatorNodeId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\x04R\bstreamId\x12\x14\n" +
	"\x05chunk\x18\x03 \x01(\fR\x05chunk\x12\x10\n" +
	"\x03eof\x18\x04 \x01(\bR\x03eof\"r\n" +
	"\x0fMeshStreamClose\x12*\n" +
	"\x11initiator_node_id\x18\x01 \x01(\tR\x0finitiatorNodeId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\x04R\bstreamId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason*Y\n" +
	"\x0eMeshStreamKind\x12 \n" +
	"\x1cMESH_STREAM_KIND_UNSPECIFIED\x10\x00\x12%\n" +
	"!MESH_STREAM_KIND_BOOTSTRAP_SERVER\x10\x01B2Z0github.com/WangYihang/Platypus/pkg/proto/v2;v2pbb\x06proto3"

var (
	file_mesh_proto_rawDescOnce sync.Once
	file_mesh_proto_rawDescData []byte
)

func file_mesh_proto_rawDescGZIP() []byte {
	file_mesh_proto_rawDescOnce.Do(func() {
		file_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mesh_proto_rawDesc), len(file_mesh_proto_rawDesc)))
	})
	return file_mesh_proto_rawDescData
}

var file_mesh_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_mesh_proto_goTypes = []any{
	(MeshStreamKind)(0),       // 0: platypus.v2.MeshStreamKind
	(*MeshEnvelope)(nil),      // 1: platypus.v2.MeshEnvelope
	(*NodeInfo)(nil),          // 2: platypus.v2.NodeInfo
	(*HandshakePayload)(nil),  // 3: platypus.v2.HandshakePayload
	(*MeshHello)(nil),         // 4: platypus.v2.MeshHello
	(*MeshHelloAck)(nil),      // 5: platypus.v2.MeshHelloAck
	(*MeshHelloFinish)(nil),   // 6: platypus.v2.MeshHelloFinish
	(*MeshKeepalive)(nil),     // 7: platypus.v2.MeshKeepalive
	(*MeshPeerAnnounce)(nil),  // 8: platypus.v2.MeshPeerAnnounce
	(*MeshPeerDelta)(nil),     // 9: platypus.v2.MeshPeerDelta
	(*MeshLSA)(nil),           // 10: platypus.v2.MeshLSA
	(*MeshUnreachable)(nil),   // 11: platypus.v2.MeshUnreachable
	(*MeshStreamOpen)(nil),    // 12: platypus.v2.MeshStreamOpen
	(*MeshStreamOpenAck)(nil), // 13: platypus.v2.MeshStreamOpenAck
	(*MeshStreamData)(nil),    // 14: platypus.v2.MeshStreamData
	(*MeshStreamClose)(nil),   // 15: platypus.v2.MeshStreamClose
	(*MeshLSA_Link)(nil),      // 16: platypus.v2.MeshLSA.Link
}
var file_mesh_proto_depIdxs = []int32{
	4,  // 0: platypus.v2.MeshEnvelope.hello:type_name -> platypus.v2.MeshHello
	5,  // 1: platypus.v2.MeshEnvelope.hello_ack:type_name -> platypus.v2.MeshHelloAck
	6,  // 2: platypus.v2.MeshEnvelope.hello_finish:type_name -> platypus.v2.MeshHelloFinish
	7,  // 3: platypus.v2.MeshEnvelope.keepalive:type_name -> platypus.v2.MeshKeepalive
	8,  // 4: platypus.v2.MeshEnvelope.peer_announce:type_name -> platypus.v2.MeshPeerAnnounce
	9,  // 5: platypus.v2.MeshEnvelope.peer_delta:type_name -> platypus.v2.MeshPeerDelta
	10, // 6: platypus.v2.MeshEnvelope.lsa:type_name -> platypus.v2.MeshLSA
	11, // 7: platypus.v2.MeshEnvelope.unreachable:type_name -> platypus.v2.MeshUnreachable
	12, // 8: platypus.v2.MeshEnvelope.stream_open:type_name -> platypus.v2.MeshStreamOpen
	13, // 9: platypus.v2.MeshEnvelope.stream_open_ack:type_name -> platypus.v2.MeshStreamOpenAck
	14, // 10: platypus.v2.MeshEnvelope.stream_data:type_name -> platypus.v2.MeshStreamData
	15, // 11: platypus.v2.MeshEnvelope.stream_close:type_name -> platypus.v2.MeshStreamClose
	2,  // 12: platypus.v2.MeshPeerAnnounce.nodes:type_name -> platypus.v2.NodeInfo
	2,  // 13: platypus.v2.MeshPeerDelta.added:type_name -> platypus.v2.NodeInfo
	16, // 14: platypus.v2.MeshLSA.links:type_name -> platypus.v2.MeshLSA.Link
	0,  // 15: platypus.v2.MeshStreamOpen.kind:type_name -> platypus.v2.MeshStreamKind
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_mesh_proto_init() }
func file_mesh_proto_init() {
	if File_mesh_proto != nil {
		return
	}
	file_mesh_proto_msgTypes[0].OneofWrappers = []any{
		(*MeshEnvelope_Hello)(nil),
		(*MeshEnvelope_HelloAck)(nil),
		(*MeshEnvelope_HelloFinish)(nil),
		(*MeshEnvelope_Keepalive)(nil),
		(*MeshEnvelope_PeerAnnounce)(nil),
		(*MeshEnvelope_PeerDelta)(nil),
		(*MeshEnvelope_Lsa)(nil),
		(*MeshEnvelope_Unreachable)(nil),
		(*MeshEnvelope_StreamOpen)(nil),
		(*MeshEnvelope_StreamOpenAck)(nil),
		(*MeshEnvelope_StreamData)(nil),
		(*MeshEnvelope_StreamClose)(nil),
		(*MeshEnvelope_Opaque)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mesh_proto_rawDesc), len(file_mesh_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mesh_proto_goTypes,
		DependencyIndexes: file_mesh_proto_depIdxs,
		EnumInfos:         file_mesh_proto_enumTypes,
		MessageInfos:      file_mesh_proto_msgTypes,
	}.Build()
	File_mesh_proto = out.File
	file_mesh_proto_goTypes = nil
	file_mesh_proto_depIdxs = nil
}
