// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: process_plugin.proto

package v2pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PluginHealthResponse identifies the running plugin so the agent can
// detect a swapped binary. ready=false means "alive but not yet
// serving" — the agent retries Health() up to the launch timeout
// before declaring failure.
type PluginHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Ready         bool                   `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginHealthResponse) Reset() {
	*x = PluginHealthResponse{}
	mi := &file_process_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginHealthResponse) ProtoMessage() {}

func (x *PluginHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_process_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginHealthResponse.ProtoReflect.Descriptor instead.
func (*PluginHealthResponse) Descriptor() ([]byte, []int) {
	return file_process_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *PluginHealthResponse) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginHealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginHealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

// PluginStreamMessage wraps the bidirectional Stream traffic. Exactly
// one of {open, frame} is set per message. open is valid ONLY as the
// very first inbound message; sending it again returns INVALID_ARGUMENT.
type PluginStreamMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*PluginStreamMessage_Open
	//	*PluginStreamMessage_Frame
	Body          isPluginStreamMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginStreamMessage) Reset() {
	*x = PluginStreamMessage{}
	mi := &file_process_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginStreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStreamMessage) ProtoMessage() {}

func (x *PluginStreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_process_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStreamMessage.ProtoReflect.Descriptor instead.
func (*PluginStreamMessage) Descriptor() ([]byte, []int) {
	return file_process_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginStreamMessage) GetBody() isPluginStreamMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PluginStreamMessage) GetOpen() *PluginStreamOpen {
	if x != nil {
		if x, ok := x.Body.(*PluginStreamMessage_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *PluginStreamMessage) GetFrame() *PluginStreamFrame {
	if x != nil {
		if x, ok := x.Body.(*PluginStreamMessage_Frame); ok {
			return x.Frame
		}
	}
	return nil
}

type isPluginStreamMessage_Body interface {
	isPluginStreamMessage_Body()
}

type PluginStreamMessage_Open struct {
	Open *PluginStreamOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type PluginStreamMessage_Frame struct {
	Frame *PluginStreamFrame `protobuf:"bytes,2,opt,name=frame,proto3,oneof"`
}

func (*PluginStreamMessage_Open) isPluginStreamMessage_Body() {}

func (*PluginStreamMessage_Frame) isPluginStreamMessage_Body() {}

// PluginStreamOpen is the first-message header on Stream(). Identifies
// which named stream from the manifest the agent is opening, and
// carries the typed request payload (e.g. a marshalled FileReadRequest
// for a file-read stream).
type PluginStreamOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamName    string                 `protobuf:"bytes,1,opt,name=stream_name,json=streamName,proto3" json:"stream_name,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	TimeoutMs     uint64                 `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginStreamOpen) Reset() {
	*x = PluginStreamOpen{}
	mi := &file_process_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginStreamOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStreamOpen) ProtoMessage() {}

func (x *PluginStreamOpen) ProtoReflect() protoreflect.Message {
	mi := &file_process_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStreamOpen.ProtoReflect.Descriptor instead.
func (*PluginStreamOpen) Descriptor() ([]byte, []int) {
	return file_process_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *PluginStreamOpen) GetStreamName() string {
	if x != nil {
		return x.StreamName
	}
	return ""
}

func (x *PluginStreamOpen) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PluginStreamOpen) GetTimeoutMs() uint64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

var File_process_plugin_proto protoreflect.FileDescriptor

const file_process_plugin_proto_rawDesc = "" +
	"\n" +
	"\x14process_plugin.proto\x12\vplatypus.v2\x1a\x1bgoogle/protobuf/empty.proto\x1a\fplugin.proto\"c\n" +
	"\x14PluginHealthResponse\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05ready\x18\x03 \x01(\bR\x05ready\"\x8a\x01\n" +
	"\x13PluginStreamMessage\x123\n" +
	"\x04open\x18\x01 \x01(\v2\x1d.platypus.v2.PluginStreamOpenH\x00R\x04open\x126\n" +
	"\x05frame\x18\x02 \x01(\v2\x1e.platypus.v2.PluginStreamFrameH\x00R\x05frameB\x06\n" +
	"\x04body\"l\n" +
	"\x10PluginStreamOpen\x12\x1f\n" +
	"\vstream_name\x18\x01 \x01(\tR\n" +
	"streamName\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x04R\ttimeoutMs2\xab\x02\n" +
	"\rPluginRuntime\x12C\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a!.platypus.v2.PluginHealthResponse\x12G\n" +
	"\x04Call\x12\x1e.platypus.v2.PluginCallRequest\x1a\x1f.platypus.v2.PluginCallResponse\x12P\n" +
	"\x06Stream\x12 .platypus.v2.PluginStreamMessage\x1a .platypus.v2.PluginStreamMessage(\x010\x01\x12:\n" +
	"\bShutdown\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB2Z0github.com/WangYihang/Platypus/pkg/proto/v2;v2pbb\x06proto3"

var (
	file_process_plugin_proto_rawDescOnce sync.Once
	file_process_plugin_proto_rawDescData []byte
)

func file_process_plugin_proto_rawDescGZIP() []byte {
	file_process_plugin_proto_rawDescOnce.Do(func() {
		file_process_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_process_plugin_proto_rawDesc), len(file_process_plugin_proto_rawDesc)))
	})
	return file_process_plugin_proto_rawDescData
}

var file_process_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_process_plugin_proto_goTypes = []any{
	(*PluginHealthResponse)(nil), // 0: platypus.v2.PluginHealthResponse
	(*PluginStreamMessage)(nil),  // 1: platypus.v2.PluginStreamMessage
	(*PluginStreamOpen)(nil),     // 2: platypus.v2.PluginStreamOpen
	(*PluginStreamFrame)(nil),    // 3: platypus.v2.PluginStreamFrame
	(*emptypb.Empty)(nil),        // 4: google.protobuf.Empty
	(*PluginCallRequest)(nil),    // 5: platypus.v2.PluginCallRequest
	(*PluginCallResponse)(nil),   // 6: platypus.v2.PluginCallResponse
}
var file_process_plugin_proto_depIdxs = []int32{
	2, // 0: platypus.v2.PluginStreamMessage.open:type_name -> platypus.v2.PluginStreamOpen
	3, // 1: platypus.v2.PluginStreamMessage.frame:type_name -> platypus.v2.PluginStreamFrame
	4, // 2: platypus.v2.PluginRuntime.Health:input_type -> google.protobuf.Empty
	5, // 3: platypus.v2.PluginRuntime.Call:input_type -> platypus.v2.PluginCallRequest
	1, // 4: platypus.v2.PluginRuntime.Stream:input_type -> platypus.v2.PluginStreamMessage
	4, // 5: platypus.v2.PluginRuntime.Shutdown:input_type -> google.protobuf.Empty
	0, // 6: platypus.v2.PluginRuntime.Health:output_type -> platypus.v2.PluginHealthResponse
	6, // 7: platypus.v2.PluginRuntime.Call:output_type -> platypus.v2.PluginCallResponse
	1, // 8: platypus.v2.PluginRuntime.Stream:output_type -> platypus.v2.PluginStreamMessage
	4, // 9: platypus.v2.PluginRuntime.Shutdown:output_type -> google.protobuf.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_process_plugin_proto_init() }
func file_process_plugin_proto_init() {
	if File_process_plugin_proto != nil {
		return
	}
	file_plugin_proto_init()
	file_process_plugin_proto_msgTypes[1].OneofWrappers = []any{
		(*PluginStreamMessage_Open)(nil),
		(*PluginStreamMessage_Frame)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_process_plugin_proto_rawDesc), len(file_process_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_process_plugin_proto_goTypes,
		DependencyIndexes: file_process_plugin_proto_depIdxs,
		MessageInfos:      file_process_plugin_proto_msgTypes,
	}.Build()
	File_process_plugin_proto = out.File
	file_process_plugin_proto_goTypes = nil
	file_process_plugin_proto_depIdxs = nil
}
