// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: rpc.proto

package v2pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RpcRequest is the StreamHeader.metadata for STREAM_TYPE_RPC.
// The agent reads exactly one RpcRequest, sends exactly one
// RpcResponse, then closes the stream. Timeouts are delivered via
// context cancellation on both sides; the stream itself has no
// keepalive (short-lived by construction).
type RpcRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RpcRequest_Exec
	//	*RpcRequest_ListDir
	//	*RpcRequest_Stat
	//	*RpcRequest_Delete
	//	*RpcRequest_Rename
	//	*RpcRequest_Mkdir
	//	*RpcRequest_Chmod
	//	*RpcRequest_SysInfo
	//	*RpcRequest_ProcessList
	//	*RpcRequest_SecurityScan
	//	*RpcRequest_ListSecurityChecks
	//	*RpcRequest_ConfigAudit
	//	*RpcRequest_ListConfigAuditors
	//	*RpcRequest_PluginCall
	Payload       isRpcRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcRequest) Reset() {
	*x = RpcRequest{}
	mi := &file_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRequest) ProtoMessage() {}

func (x *RpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRequest.ProtoReflect.Descriptor instead.
func (*RpcRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *RpcRequest) GetPayload() isRpcRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RpcRequest) GetExec() *ExecRequest {
	if x != nil {
		if x, ok := x.Payload.(*RpcRequest_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *RpcRequest) GetListDir() *ListDirRequest {
	if x != nil {
		if x, ok := x.Payload.(*RpcRequest_ListDir); ok {
			return x.ListDir
		}
	}
	return nil
}

func (x *RpcRequest) GetStat() *StatRequest {
	if x != nil {
		if x, ok := x.Payload.(*RpcRequest_Stat); ok {
			return x.Stat
		}
	}
	return nil
}

func (x *RpcRequest) GetDelete() *DeleteRequest {
	if x != nil {
		if x, ok := x.Payload.(*RpcRequest_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *RpcRequest) GetRename() *RenameRequest {
	if x != nil {
		if x, ok := x.Payload.(*RpcRequest_Rename); ok {
			return x.Rename
		}
	}
	return nil
}

func (x *RpcRequest) GetMkdir() *MkdirRequest {
	if x != nil {
		if x, ok := x.Payload.(*RpcRequest_Mkdir); ok {
			return x.Mkdir
		}
	}
	return nil
}

func (x *RpcRequest) GetChmod() *ChmodRequest {
	if x != nil {
		if x, ok := x.Payload.(*RpcRequest_Chmod); ok {
			return x.Chmod
		}
	}
	return nil
}

func (x *RpcRequest) GetSysInfo() *SysInfoRequest {
	if x != nil {
		if x, ok := x.Payload.(*RpcRequest_SysInfo); ok {
			return x.SysInfo
		}
	}
	return nil
}

func (x *RpcRequest) GetProcessList() *ProcessListRequest {
	if x != nil {
		if x, ok := x.Payload.(*RpcRequest_ProcessList); ok {
			return x.ProcessList
		}
	}
	return nil
}

func (x *RpcRequest) GetSecurityScan() *SecurityScanRequest {
	if x != nil {
		if x, ok := x.Payload.(*RpcRequest_SecurityScan); ok {
			return x.SecurityScan
		}
	}
	return nil
}

func (x *RpcRequest) GetListSecurityChecks() *ListSecurityChecksRequest {
	if x != nil {
		if x, ok := x.Payload.(*RpcRequest_ListSecurityChecks); ok {
			return x.ListSecurityChecks
		}
	}
	return nil
}

func (x *RpcRequest) GetConfigAudit() *ConfigAuditRequest {
	if x != nil {
		if x, ok := x.Payload.(*RpcRequest_ConfigAudit); ok {
			return x.ConfigAudit
		}
	}
	return nil
}

func (x *RpcRequest) GetListConfigAuditors() *ListConfigAuditorsRequest {
	if x != nil {
		if x, ok := x.Payload.(*RpcRequest_ListConfigAuditors); ok {
			return x.ListConfigAuditors
		}
	}
	return nil
}

func (x *RpcRequest) GetPluginCall() *PluginCallRequest {
	if x != nil {
		if x, ok := x.Payload.(*RpcRequest_PluginCall); ok {
			return x.PluginCall
		}
	}
	return nil
}

type isRpcRequest_Payload interface {
	isRpcRequest_Payload()
}

type RpcRequest_Exec struct {
	Exec *ExecRequest `protobuf:"bytes,10,opt,name=exec,proto3,oneof"`
}

type RpcRequest_ListDir struct {
	ListDir *ListDirRequest `protobuf:"bytes,20,opt,name=list_dir,json=listDir,proto3,oneof"`
}

type RpcRequest_Stat struct {
	Stat *StatRequest `protobuf:"bytes,21,opt,name=stat,proto3,oneof"`
}

type RpcRequest_Delete struct {
	Delete *DeleteRequest `protobuf:"bytes,22,opt,name=delete,proto3,oneof"`
}

type RpcRequest_Rename struct {
	Rename *RenameRequest `protobuf:"bytes,23,opt,name=rename,proto3,oneof"`
}

type RpcRequest_Mkdir struct {
	Mkdir *MkdirRequest `protobuf:"bytes,24,opt,name=mkdir,proto3,oneof"`
}

type RpcRequest_Chmod struct {
	Chmod *ChmodRequest `protobuf:"bytes,25,opt,name=chmod,proto3,oneof"`
}

type RpcRequest_SysInfo struct {
	SysInfo *SysInfoRequest `protobuf:"bytes,30,opt,name=sys_info,json=sysInfo,proto3,oneof"`
}

type RpcRequest_ProcessList struct {
	ProcessList *ProcessListRequest `protobuf:"bytes,31,opt,name=process_list,json=processList,proto3,oneof"`
}

type RpcRequest_SecurityScan struct {
	SecurityScan *SecurityScanRequest `protobuf:"bytes,32,opt,name=security_scan,json=securityScan,proto3,oneof"`
}

type RpcRequest_ListSecurityChecks struct {
	ListSecurityChecks *ListSecurityChecksRequest `protobuf:"bytes,33,opt,name=list_security_checks,json=listSecurityChecks,proto3,oneof"`
}

type RpcRequest_ConfigAudit struct {
	ConfigAudit *ConfigAuditRequest `protobuf:"bytes,34,opt,name=config_audit,json=configAudit,proto3,oneof"`
}

type RpcRequest_ListConfigAuditors struct {
	ListConfigAuditors *ListConfigAuditorsRequest `protobuf:"bytes,35,opt,name=list_config_auditors,json=listConfigAuditors,proto3,oneof"`
}

type RpcRequest_PluginCall struct {
	// Plugin call: agent looks up plugin_id in its registry and
	// dispatches to the wasm export named PluginCallRequest.method.
	// One oneof arm covers every plugin so adding a new plugin
	// never requires a proto / dispatch / wiring change. Defined in
	// plugin.proto.
	PluginCall *PluginCallRequest `protobuf:"bytes,100,opt,name=plugin_call,json=pluginCall,proto3,oneof"`
}

func (*RpcRequest_Exec) isRpcRequest_Payload() {}

func (*RpcRequest_ListDir) isRpcRequest_Payload() {}

func (*RpcRequest_Stat) isRpcRequest_Payload() {}

func (*RpcRequest_Delete) isRpcRequest_Payload() {}

func (*RpcRequest_Rename) isRpcRequest_Payload() {}

func (*RpcRequest_Mkdir) isRpcRequest_Payload() {}

func (*RpcRequest_Chmod) isRpcRequest_Payload() {}

func (*RpcRequest_SysInfo) isRpcRequest_Payload() {}

func (*RpcRequest_ProcessList) isRpcRequest_Payload() {}

func (*RpcRequest_SecurityScan) isRpcRequest_Payload() {}

func (*RpcRequest_ListSecurityChecks) isRpcRequest_Payload() {}

func (*RpcRequest_ConfigAudit) isRpcRequest_Payload() {}

func (*RpcRequest_ListConfigAuditors) isRpcRequest_Payload() {}

func (*RpcRequest_PluginCall) isRpcRequest_Payload() {}

type RpcResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Populated on transport- or framework-level errors (e.g. unknown
	// request type, agent-side panic recovered). Service-level
	// failures go in the per-payload `error` fields.
	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RpcResponse_Exec
	//	*RpcResponse_ListDir
	//	*RpcResponse_Stat
	//	*RpcResponse_Delete
	//	*RpcResponse_Rename
	//	*RpcResponse_Mkdir
	//	*RpcResponse_Chmod
	//	*RpcResponse_SysInfo
	//	*RpcResponse_ProcessList
	//	*RpcResponse_SecurityScan
	//	*RpcResponse_ListSecurityChecks
	//	*RpcResponse_ConfigAudit
	//	*RpcResponse_ListConfigAuditors
	//	*RpcResponse_PluginCall
	Payload       isRpcResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcResponse) Reset() {
	*x = RpcResponse{}
	mi := &file_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcResponse) ProtoMessage() {}

func (x *RpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcResponse.ProtoReflect.Descriptor instead.
func (*RpcResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RpcResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RpcResponse) GetPayload() isRpcResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RpcResponse) GetExec() *ExecResponse {
	if x != nil {
		if x, ok := x.Payload.(*RpcResponse_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *RpcResponse) GetListDir() *ListDirResponse {
	if x != nil {
		if x, ok := x.Payload.(*RpcResponse_ListDir); ok {
			return x.ListDir
		}
	}
	return nil
}

func (x *RpcResponse) GetStat() *StatResponse {
	if x != nil {
		if x, ok := x.Payload.(*RpcResponse_Stat); ok {
			return x.Stat
		}
	}
	return nil
}

func (x *RpcResponse) GetDelete() *DeleteResponse {
	if x != nil {
		if x, ok := x.Payload.(*RpcResponse_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *RpcResponse) GetRename() *RenameResponse {
	if x != nil {
		if x, ok := x.Payload.(*RpcResponse_Rename); ok {
			return x.Rename
		}
	}
	return nil
}

func (x *RpcResponse) GetMkdir() *MkdirResponse {
	if x != nil {
		if x, ok := x.Payload.(*RpcResponse_Mkdir); ok {
			return x.Mkdir
		}
	}
	return nil
}

func (x *RpcResponse) GetChmod() *ChmodResponse {
	if x != nil {
		if x, ok := x.Payload.(*RpcResponse_Chmod); ok {
			return x.Chmod
		}
	}
	return nil
}

func (x *RpcResponse) GetSysInfo() *SysInfoResponse {
	if x != nil {
		if x, ok := x.Payload.(*RpcResponse_SysInfo); ok {
			return x.SysInfo
		}
	}
	return nil
}

func (x *RpcResponse) GetProcessList() *ProcessListResponse {
	if x != nil {
		if x, ok := x.Payload.(*RpcResponse_ProcessList); ok {
			return x.ProcessList
		}
	}
	return nil
}

func (x *RpcResponse) GetSecurityScan() *SecurityScanResponse {
	if x != nil {
		if x, ok := x.Payload.(*RpcResponse_SecurityScan); ok {
			return x.SecurityScan
		}
	}
	return nil
}

func (x *RpcResponse) GetListSecurityChecks() *ListSecurityChecksResponse {
	if x != nil {
		if x, ok := x.Payload.(*RpcResponse_ListSecurityChecks); ok {
			return x.ListSecurityChecks
		}
	}
	return nil
}

func (x *RpcResponse) GetConfigAudit() *ConfigAuditResponse {
	if x != nil {
		if x, ok := x.Payload.(*RpcResponse_ConfigAudit); ok {
			return x.ConfigAudit
		}
	}
	return nil
}

func (x *RpcResponse) GetListConfigAuditors() *ListConfigAuditorsResponse {
	if x != nil {
		if x, ok := x.Payload.(*RpcResponse_ListConfigAuditors); ok {
			return x.ListConfigAuditors
		}
	}
	return nil
}

func (x *RpcResponse) GetPluginCall() *PluginCallResponse {
	if x != nil {
		if x, ok := x.Payload.(*RpcResponse_PluginCall); ok {
			return x.PluginCall
		}
	}
	return nil
}

type isRpcResponse_Payload interface {
	isRpcResponse_Payload()
}

type RpcResponse_Exec struct {
	Exec *ExecResponse `protobuf:"bytes,10,opt,name=exec,proto3,oneof"`
}

type RpcResponse_ListDir struct {
	ListDir *ListDirResponse `protobuf:"bytes,20,opt,name=list_dir,json=listDir,proto3,oneof"`
}

type RpcResponse_Stat struct {
	Stat *StatResponse `protobuf:"bytes,21,opt,name=stat,proto3,oneof"`
}

type RpcResponse_Delete struct {
	Delete *DeleteResponse `protobuf:"bytes,22,opt,name=delete,proto3,oneof"`
}

type RpcResponse_Rename struct {
	Rename *RenameResponse `protobuf:"bytes,23,opt,name=rename,proto3,oneof"`
}

type RpcResponse_Mkdir struct {
	Mkdir *MkdirResponse `protobuf:"bytes,24,opt,name=mkdir,proto3,oneof"`
}

type RpcResponse_Chmod struct {
	Chmod *ChmodResponse `protobuf:"bytes,25,opt,name=chmod,proto3,oneof"`
}

type RpcResponse_SysInfo struct {
	SysInfo *SysInfoResponse `protobuf:"bytes,30,opt,name=sys_info,json=sysInfo,proto3,oneof"`
}

type RpcResponse_ProcessList struct {
	ProcessList *ProcessListResponse `protobuf:"bytes,31,opt,name=process_list,json=processList,proto3,oneof"`
}

type RpcResponse_SecurityScan struct {
	SecurityScan *SecurityScanResponse `protobuf:"bytes,32,opt,name=security_scan,json=securityScan,proto3,oneof"`
}

type RpcResponse_ListSecurityChecks struct {
	ListSecurityChecks *ListSecurityChecksResponse `protobuf:"bytes,33,opt,name=list_security_checks,json=listSecurityChecks,proto3,oneof"`
}

type RpcResponse_ConfigAudit struct {
	ConfigAudit *ConfigAuditResponse `protobuf:"bytes,34,opt,name=config_audit,json=configAudit,proto3,oneof"`
}

type RpcResponse_ListConfigAuditors struct {
	ListConfigAuditors *ListConfigAuditorsResponse `protobuf:"bytes,35,opt,name=list_config_auditors,json=listConfigAuditors,proto3,oneof"`
}

type RpcResponse_PluginCall struct {
	PluginCall *PluginCallResponse `protobuf:"bytes,100,opt,name=plugin_call,json=pluginCall,proto3,oneof"`
}

func (*RpcResponse_Exec) isRpcResponse_Payload() {}

func (*RpcResponse_ListDir) isRpcResponse_Payload() {}

func (*RpcResponse_Stat) isRpcResponse_Payload() {}

func (*RpcResponse_Delete) isRpcResponse_Payload() {}

func (*RpcResponse_Rename) isRpcResponse_Payload() {}

func (*RpcResponse_Mkdir) isRpcResponse_Payload() {}

func (*RpcResponse_Chmod) isRpcResponse_Payload() {}

func (*RpcResponse_SysInfo) isRpcResponse_Payload() {}

func (*RpcResponse_ProcessList) isRpcResponse_Payload() {}

func (*RpcResponse_SecurityScan) isRpcResponse_Payload() {}

func (*RpcResponse_ListSecurityChecks) isRpcResponse_Payload() {}

func (*RpcResponse_ConfigAudit) isRpcResponse_Payload() {}

func (*RpcResponse_ListConfigAuditors) isRpcResponse_Payload() {}

func (*RpcResponse_PluginCall) isRpcResponse_Payload() {}

// --- One-shot exec ---
type ExecRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Command string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args    []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Cwd     string                 `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Env     map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Max wait in milliseconds; 0 = no deadline beyond context.
	TimeoutMs     uint32 `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ExecRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        []byte                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *ExecResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// --- Filesystem metadata ---
type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	MtimeUnixNano int64                  `protobuf:"varint,4,opt,name=mtime_unix_nano,json=mtimeUnixNano,proto3" json:"mtime_unix_nano,omitempty"`
	SymlinkTarget string                 `protobuf:"bytes,5,opt,name=symlink_target,json=symlinkTarget,proto3" json:"symlink_target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *FileEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileEntry) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileEntry) GetMtimeUnixNano() int64 {
	if x != nil {
		return x.MtimeUnixNano
	}
	return 0
}

func (x *FileEntry) GetSymlinkTarget() string {
	if x != nil {
		return x.SymlinkTarget
	}
	return ""
}

type ListDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirRequest) Reset() {
	*x = ListDirRequest{}
	mi := &file_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirRequest) ProtoMessage() {}

func (x *ListDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirRequest.ProtoReflect.Descriptor instead.
func (*ListDirRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *ListDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FileEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirResponse) Reset() {
	*x = ListDirResponse{}
	mi := &file_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirResponse) ProtoMessage() {}

func (x *ListDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirResponse.ProtoReflect.Descriptor instead.
func (*ListDirResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *ListDirResponse) GetEntries() []*FileEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListDirResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *FileEntry             `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *StatResponse) GetEntry() *FileEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *StatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeleteRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameRequest) Reset() {
	*x = RenameRequest{}
	mi := &file_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameRequest) ProtoMessage() {}

func (x *RenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameRequest.ProtoReflect.Descriptor instead.
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *RenameRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *RenameRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type RenameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameResponse) Reset() {
	*x = RenameResponse{}
	mi := &file_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameResponse) ProtoMessage() {}

func (x *RenameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameResponse.ProtoReflect.Descriptor instead.
func (*RenameResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *RenameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Mkdirs        bool                   `protobuf:"varint,3,opt,name=mkdirs,proto3" json:"mkdirs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *MkdirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MkdirRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *MkdirRequest) GetMkdirs() bool {
	if x != nil {
		return x.Mkdirs
	}
	return false
}

type MkdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirResponse) Reset() {
	*x = MkdirResponse{}
	mi := &file_rpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirResponse) ProtoMessage() {}

func (x *MkdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirResponse.ProtoReflect.Descriptor instead.
func (*MkdirResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{14}
}

func (x *MkdirResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ChmodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChmodRequest) Reset() {
	*x = ChmodRequest{}
	mi := &file_rpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChmodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChmodRequest) ProtoMessage() {}

func (x *ChmodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChmodRequest.ProtoReflect.Descriptor instead.
func (*ChmodRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{15}
}

func (x *ChmodRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ChmodRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type ChmodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChmodResponse) Reset() {
	*x = ChmodResponse{}
	mi := &file_rpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChmodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChmodResponse) ProtoMessage() {}

func (x *ChmodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChmodResponse.ProtoReflect.Descriptor instead.
func (*ChmodResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{16}
}

func (x *ChmodResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_rpc_proto protoreflect.FileDescriptor

const file_rpc_proto_rawDesc = "" +
	"\n" +
	"\trpc.proto\x12\vplatypus.v2\x1a\fplugin.proto\x1a\x0esys_info.proto\x1a\x0fsys_procs.proto\x1a\x12sys_security.proto\x1a\x16sys_config_audit.proto\"\x8d\a\n" +
	"\n" +
	"RpcRequest\x12.\n" +
	"\x04exec\x18\n" +
	" \x01(\v2\x18.platypus.v2.ExecRequestH\x00R\x04exec\x128\n" +
	"\blist_dir\x18\x14 \x01(\v2\x1b.platypus.v2.ListDirRequestH\x00R\alistDir\x12.\n" +
	"\x04stat\x18\x15 \x01(\v2\x18.platypus.v2.StatRequestH\x00R\x04stat\x124\n" +
	"\x06delete\x18\x16 \x01(\v2\x1a.platypus.v2.DeleteRequestH\x00R\x06delete\x124\n" +
	"\x06rename\x18\x17 \x01(\v2\x1a.platypus.v2.RenameRequestH\x00R\x06rename\x121\n" +
	"\x05mkdir\x18\x18 \x01(\v2\x19.platypus.v2.MkdirRequestH\x00R\x05mkdir\x121\n" +
	"\x05chmod\x18\x19 \x01(\v2\x19.platypus.v2.ChmodRequestH\x00R\x05chmod\x128\n" +
	"\bsys_info\x18\x1e \x01(\v2\x1b.platypus.v2.SysInfoRequestH\x00R\asysInfo\x12D\n" +
	"\fprocess_list\x18\x1f \x01(\v2\x1f.platypus.v2.ProcessListRequestH\x00R\vprocessList\x12G\n" +
	"\rsecurity_scan\x18  \x01(\v2 .platypus.v2.SecurityScanRequestH\x00R\fsecurityScan\x12Z\n" +
	"\x14list_security_checks\x18! \x01(\v2&.platypus.v2.ListSecurityChecksRequestH\x00R\x12listSecurityChecks\x12D\n" +
	"\fconfig_audit\x18\" \x01(\v2\x1f.platypus.v2.ConfigAuditRequestH\x00R\vconfigAudit\x12Z\n" +
	"\x14list_config_auditors\x18# \x01(\v2&.platypus.v2.ListConfigAuditorsRequestH\x00R\x12listConfigAuditors\x12A\n" +
	"\vplugin_call\x18d \x01(\v2\x1e.platypus.v2.PluginCallRequestH\x00R\n" +
	"pluginCallB\t\n" +
	"\apayload\"\xb2\a\n" +
	"\vRpcResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12/\n" +
	"\x04exec\x18\n" +
	" \x01(\v2\x19.platypus.v2.ExecResponseH\x00R\x04exec\x129\n" +
	"\blist_dir\x18\x14 \x01(\v2\x1c.platypus.v2.ListDirResponseH\x00R\alistDir\x12/\n" +
	"\x04stat\x18\x15 \x01(\v2\x19.platypus.v2.StatResponseH\x00R\x04stat\x125\n" +
	"\x06delete\x18\x16 \x01(\v2\x1b.platypus.v2.DeleteResponseH\x00R\x06delete\x125\n" +
	"\x06rename\x18\x17 \x01(\v2\x1b.platypus.v2.RenameResponseH\x00R\x06rename\x122\n" +
	"\x05mkdir\x18\x18 \x01(\v2\x1a.platypus.v2.MkdirResponseH\x00R\x05mkdir\x122\n" +
	"\x05chmod\x18\x19 \x01(\v2\x1a.platypus.v2.ChmodResponseH\x00R\x05chmod\x129\n" +
	"\bsys_info\x18\x1e \x01(\v2\x1c.platypus.v2.SysInfoResponseH\x00R\asysInfo\x12E\n" +
	"\fprocess_list\x18\x1f \x01(\v2 .platypus.v2.ProcessListResponseH\x00R\vprocessList\x12H\n" +
	"\rsecurity_scan\x18  \x01(\v2!.platypus.v2.SecurityScanResponseH\x00R\fsecurityScan\x12[\n" +
	"\x14list_security_checks\x18! \x01(\v2'.platypus.v2.ListSecurityChecksResponseH\x00R\x12listSecurityChecks\x12E\n" +
	"\fconfig_audit\x18\" \x01(\v2 .platypus.v2.ConfigAuditResponseH\x00R\vconfigAudit\x12[\n" +
	"\x14list_config_auditors\x18# \x01(\v2'.platypus.v2.ListConfigAuditorsResponseH\x00R\x12listConfigAuditors\x12B\n" +
	"\vplugin_call\x18d \x01(\v2\x1f.platypus.v2.PluginCallResponseH\x00R\n" +
	"pluginCallB\t\n" +
	"\apayload\"\xd9\x01\n" +
	"\vExecRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x123\n" +
	"\x03env\x18\x04 \x03(\v2!.platypus.v2.ExecRequest.EnvEntryR\x03env\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\rR\ttimeoutMs\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"q\n" +
	"\fExecResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\fR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x96\x01\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12&\n" +
	"\x0fmtime_unix_nano\x18\x04 \x01(\x03R\rmtimeUnixNano\x12%\n" +
	"\x0esymlink_target\x18\x05 \x01(\tR\rsymlinkTarget\"$\n" +
	"\x0eListDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"Y\n" +
	"\x0fListDirResponse\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.platypus.v2.FileEntryR\aentries\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"!\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"R\n" +
	"\fStatResponse\x12,\n" +
	"\x05entry\x18\x01 \x01(\v2\x16.platypus.v2.FileEntryR\x05entry\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"A\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"&\n" +
	"\x0eDeleteResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"3\n" +
	"\rRenameRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"&\n" +
	"\x0eRenameResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"N\n" +
	"\fMkdirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x16\n" +
	"\x06mkdirs\x18\x03 \x01(\bR\x06mkdirs\"%\n" +
	"\rMkdirResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"6\n" +
	"\fChmodRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\"%\n" +
	"\rChmodResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05errorB2Z0github.com/WangYihang/Platypus/pkg/proto/v2;v2pbb\x06proto3"

var (
	file_rpc_proto_rawDescOnce sync.Once
	file_rpc_proto_rawDescData []byte
)

func file_rpc_proto_rawDescGZIP() []byte {
	file_rpc_proto_rawDescOnce.Do(func() {
		file_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)))
	})
	return file_rpc_proto_rawDescData
}

var file_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_rpc_proto_goTypes = []any{
	(*RpcRequest)(nil),                 // 0: platypus.v2.RpcRequest
	(*RpcResponse)(nil),                // 1: platypus.v2.RpcResponse
	(*ExecRequest)(nil),                // 2: platypus.v2.ExecRequest
	(*ExecResponse)(nil),               // 3: platypus.v2.ExecResponse
	(*FileEntry)(nil),                  // 4: platypus.v2.FileEntry
	(*ListDirRequest)(nil),             // 5: platypus.v2.ListDirRequest
	(*ListDirResponse)(nil),            // 6: platypus.v2.ListDirResponse
	(*StatRequest)(nil),                // 7: platypus.v2.StatRequest
	(*StatResponse)(nil),               // 8: platypus.v2.StatResponse
	(*DeleteRequest)(nil),              // 9: platypus.v2.DeleteRequest
	(*DeleteResponse)(nil),             // 10: platypus.v2.DeleteResponse
	(*RenameRequest)(nil),              // 11: platypus.v2.RenameRequest
	(*RenameResponse)(nil),             // 12: platypus.v2.RenameResponse
	(*MkdirRequest)(nil),               // 13: platypus.v2.MkdirRequest
	(*MkdirResponse)(nil),              // 14: platypus.v2.MkdirResponse
	(*ChmodRequest)(nil),               // 15: platypus.v2.ChmodRequest
	(*ChmodResponse)(nil),              // 16: platypus.v2.ChmodResponse
	nil,                                // 17: platypus.v2.ExecRequest.EnvEntry
	(*SysInfoRequest)(nil),             // 18: platypus.v2.SysInfoRequest
	(*ProcessListRequest)(nil),         // 19: platypus.v2.ProcessListRequest
	(*SecurityScanRequest)(nil),        // 20: platypus.v2.SecurityScanRequest
	(*ListSecurityChecksRequest)(nil),  // 21: platypus.v2.ListSecurityChecksRequest
	(*ConfigAuditRequest)(nil),         // 22: platypus.v2.ConfigAuditRequest
	(*ListConfigAuditorsRequest)(nil),  // 23: platypus.v2.ListConfigAuditorsRequest
	(*PluginCallRequest)(nil),          // 24: platypus.v2.PluginCallRequest
	(*SysInfoResponse)(nil),            // 25: platypus.v2.SysInfoResponse
	(*ProcessListResponse)(nil),        // 26: platypus.v2.ProcessListResponse
	(*SecurityScanResponse)(nil),       // 27: platypus.v2.SecurityScanResponse
	(*ListSecurityChecksResponse)(nil), // 28: platypus.v2.ListSecurityChecksResponse
	(*ConfigAuditResponse)(nil),        // 29: platypus.v2.ConfigAuditResponse
	(*ListConfigAuditorsResponse)(nil), // 30: platypus.v2.ListConfigAuditorsResponse
	(*PluginCallResponse)(nil),         // 31: platypus.v2.PluginCallResponse
}
var file_rpc_proto_depIdxs = []int32{
	2,  // 0: platypus.v2.RpcRequest.exec:type_name -> platypus.v2.ExecRequest
	5,  // 1: platypus.v2.RpcRequest.list_dir:type_name -> platypus.v2.ListDirRequest
	7,  // 2: platypus.v2.RpcRequest.stat:type_name -> platypus.v2.StatRequest
	9,  // 3: platypus.v2.RpcRequest.delete:type_name -> platypus.v2.DeleteRequest
	11, // 4: platypus.v2.RpcRequest.rename:type_name -> platypus.v2.RenameRequest
	13, // 5: platypus.v2.RpcRequest.mkdir:type_name -> platypus.v2.MkdirRequest
	15, // 6: platypus.v2.RpcRequest.chmod:type_name -> platypus.v2.ChmodRequest
	18, // 7: platypus.v2.RpcRequest.sys_info:type_name -> platypus.v2.SysInfoRequest
	19, // 8: platypus.v2.RpcRequest.process_list:type_name -> platypus.v2.ProcessListRequest
	20, // 9: platypus.v2.RpcRequest.security_scan:type_name -> platypus.v2.SecurityScanRequest
	21, // 10: platypus.v2.RpcRequest.list_security_checks:type_name -> platypus.v2.ListSecurityChecksRequest
	22, // 11: platypus.v2.RpcRequest.config_audit:type_name -> platypus.v2.ConfigAuditRequest
	23, // 12: platypus.v2.RpcRequest.list_config_auditors:type_name -> platypus.v2.ListConfigAuditorsRequest
	24, // 13: platypus.v2.RpcRequest.plugin_call:type_name -> platypus.v2.PluginCallRequest
	3,  // 14: platypus.v2.RpcResponse.exec:type_name -> platypus.v2.ExecResponse
	6,  // 15: platypus.v2.RpcResponse.list_dir:type_name -> platypus.v2.ListDirResponse
	8,  // 16: platypus.v2.RpcResponse.stat:type_name -> platypus.v2.StatResponse
	10, // 17: platypus.v2.RpcResponse.delete:type_name -> platypus.v2.DeleteResponse
	12, // 18: platypus.v2.RpcResponse.rename:type_name -> platypus.v2.RenameResponse
	14, // 19: platypus.v2.RpcResponse.mkdir:type_name -> platypus.v2.MkdirResponse
	16, // 20: platypus.v2.RpcResponse.chmod:type_name -> platypus.v2.ChmodResponse
	25, // 21: platypus.v2.RpcResponse.sys_info:type_name -> platypus.v2.SysInfoResponse
	26, // 22: platypus.v2.RpcResponse.process_list:type_name -> platypus.v2.ProcessListResponse
	27, // 23: platypus.v2.RpcResponse.security_scan:type_name -> platypus.v2.SecurityScanResponse
	28, // 24: platypus.v2.RpcResponse.list_security_checks:type_name -> platypus.v2.ListSecurityChecksResponse
	29, // 25: platypus.v2.RpcResponse.config_audit:type_name -> platypus.v2.ConfigAuditResponse
	30, // 26: platypus.v2.RpcResponse.list_config_auditors:type_name -> platypus.v2.ListConfigAuditorsResponse
	31, // 27: platypus.v2.RpcResponse.plugin_call:type_name -> platypus.v2.PluginCallResponse
	17, // 28: platypus.v2.ExecRequest.env:type_name -> platypus.v2.ExecRequest.EnvEntry
	4,  // 29: platypus.v2.ListDirResponse.entries:type_name -> platypus.v2.FileEntry
	4,  // 30: platypus.v2.StatResponse.entry:type_name -> platypus.v2.FileEntry
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_rpc_proto_init() }
func file_rpc_proto_init() {
	if File_rpc_proto != nil {
		return
	}
	file_plugin_proto_init()
	file_sys_info_proto_init()
	file_sys_procs_proto_init()
	file_sys_security_proto_init()
	file_sys_config_audit_proto_init()
	file_rpc_proto_msgTypes[0].OneofWrappers = []any{
		(*RpcRequest_Exec)(nil),
		(*RpcRequest_ListDir)(nil),
		(*RpcRequest_Stat)(nil),
		(*RpcRequest_Delete)(nil),
		(*RpcRequest_Rename)(nil),
		(*RpcRequest_Mkdir)(nil),
		(*RpcRequest_Chmod)(nil),
		(*RpcRequest_SysInfo)(nil),
		(*RpcRequest_ProcessList)(nil),
		(*RpcRequest_SecurityScan)(nil),
		(*RpcRequest_ListSecurityChecks)(nil),
		(*RpcRequest_ConfigAudit)(nil),
		(*RpcRequest_ListConfigAuditors)(nil),
		(*RpcRequest_PluginCall)(nil),
	}
	file_rpc_proto_msgTypes[1].OneofWrappers = []any{
		(*RpcResponse_Exec)(nil),
		(*RpcResponse_ListDir)(nil),
		(*RpcResponse_Stat)(nil),
		(*RpcResponse_Delete)(nil),
		(*RpcResponse_Rename)(nil),
		(*RpcResponse_Mkdir)(nil),
		(*RpcResponse_Chmod)(nil),
		(*RpcResponse_SysInfo)(nil),
		(*RpcResponse_ProcessList)(nil),
		(*RpcResponse_SecurityScan)(nil),
		(*RpcResponse_ListSecurityChecks)(nil),
		(*RpcResponse_ConfigAudit)(nil),
		(*RpcResponse_ListConfigAuditors)(nil),
		(*RpcResponse_PluginCall)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_depIdxs,
		MessageInfos:      file_rpc_proto_msgTypes,
	}.Build()
	File_rpc_proto = out.File
	file_rpc_proto_goTypes = nil
	file_rpc_proto_depIdxs = nil
}
