// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: rpc.proto

package v2pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RpcRequest is the StreamHeader.metadata for STREAM_TYPE_RPC.
// The agent reads exactly one RpcRequest, sends exactly one
// RpcResponse, then closes the stream. Timeouts are delivered via
// context cancellation on both sides; the stream itself has no
// keepalive (short-lived by construction).
type RpcRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RpcRequest_Exec
	//	*RpcRequest_ListDir
	//	*RpcRequest_Stat
	//	*RpcRequest_Delete
	//	*RpcRequest_Rename
	//	*RpcRequest_Mkdir
	//	*RpcRequest_Chmod
	//	*RpcRequest_SysInfo
	Payload       isRpcRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcRequest) Reset() {
	*x = RpcRequest{}
	mi := &file_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRequest) ProtoMessage() {}

func (x *RpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRequest.ProtoReflect.Descriptor instead.
func (*RpcRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *RpcRequest) GetPayload() isRpcRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RpcRequest) GetExec() *ExecRequest {
	if x != nil {
		if x, ok := x.Payload.(*RpcRequest_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *RpcRequest) GetListDir() *ListDirRequest {
	if x != nil {
		if x, ok := x.Payload.(*RpcRequest_ListDir); ok {
			return x.ListDir
		}
	}
	return nil
}

func (x *RpcRequest) GetStat() *StatRequest {
	if x != nil {
		if x, ok := x.Payload.(*RpcRequest_Stat); ok {
			return x.Stat
		}
	}
	return nil
}

func (x *RpcRequest) GetDelete() *DeleteRequest {
	if x != nil {
		if x, ok := x.Payload.(*RpcRequest_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *RpcRequest) GetRename() *RenameRequest {
	if x != nil {
		if x, ok := x.Payload.(*RpcRequest_Rename); ok {
			return x.Rename
		}
	}
	return nil
}

func (x *RpcRequest) GetMkdir() *MkdirRequest {
	if x != nil {
		if x, ok := x.Payload.(*RpcRequest_Mkdir); ok {
			return x.Mkdir
		}
	}
	return nil
}

func (x *RpcRequest) GetChmod() *ChmodRequest {
	if x != nil {
		if x, ok := x.Payload.(*RpcRequest_Chmod); ok {
			return x.Chmod
		}
	}
	return nil
}

func (x *RpcRequest) GetSysInfo() *SysInfoRequest {
	if x != nil {
		if x, ok := x.Payload.(*RpcRequest_SysInfo); ok {
			return x.SysInfo
		}
	}
	return nil
}

type isRpcRequest_Payload interface {
	isRpcRequest_Payload()
}

type RpcRequest_Exec struct {
	Exec *ExecRequest `protobuf:"bytes,10,opt,name=exec,proto3,oneof"`
}

type RpcRequest_ListDir struct {
	ListDir *ListDirRequest `protobuf:"bytes,20,opt,name=list_dir,json=listDir,proto3,oneof"`
}

type RpcRequest_Stat struct {
	Stat *StatRequest `protobuf:"bytes,21,opt,name=stat,proto3,oneof"`
}

type RpcRequest_Delete struct {
	Delete *DeleteRequest `protobuf:"bytes,22,opt,name=delete,proto3,oneof"`
}

type RpcRequest_Rename struct {
	Rename *RenameRequest `protobuf:"bytes,23,opt,name=rename,proto3,oneof"`
}

type RpcRequest_Mkdir struct {
	Mkdir *MkdirRequest `protobuf:"bytes,24,opt,name=mkdir,proto3,oneof"`
}

type RpcRequest_Chmod struct {
	Chmod *ChmodRequest `protobuf:"bytes,25,opt,name=chmod,proto3,oneof"`
}

type RpcRequest_SysInfo struct {
	SysInfo *SysInfoRequest `protobuf:"bytes,30,opt,name=sys_info,json=sysInfo,proto3,oneof"`
}

func (*RpcRequest_Exec) isRpcRequest_Payload() {}

func (*RpcRequest_ListDir) isRpcRequest_Payload() {}

func (*RpcRequest_Stat) isRpcRequest_Payload() {}

func (*RpcRequest_Delete) isRpcRequest_Payload() {}

func (*RpcRequest_Rename) isRpcRequest_Payload() {}

func (*RpcRequest_Mkdir) isRpcRequest_Payload() {}

func (*RpcRequest_Chmod) isRpcRequest_Payload() {}

func (*RpcRequest_SysInfo) isRpcRequest_Payload() {}

type RpcResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Populated on transport- or framework-level errors (e.g. unknown
	// request type, agent-side panic recovered). Service-level
	// failures go in the per-payload `error` fields.
	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RpcResponse_Exec
	//	*RpcResponse_ListDir
	//	*RpcResponse_Stat
	//	*RpcResponse_Delete
	//	*RpcResponse_Rename
	//	*RpcResponse_Mkdir
	//	*RpcResponse_Chmod
	//	*RpcResponse_SysInfo
	Payload       isRpcResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcResponse) Reset() {
	*x = RpcResponse{}
	mi := &file_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcResponse) ProtoMessage() {}

func (x *RpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcResponse.ProtoReflect.Descriptor instead.
func (*RpcResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RpcResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RpcResponse) GetPayload() isRpcResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RpcResponse) GetExec() *ExecResponse {
	if x != nil {
		if x, ok := x.Payload.(*RpcResponse_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *RpcResponse) GetListDir() *ListDirResponse {
	if x != nil {
		if x, ok := x.Payload.(*RpcResponse_ListDir); ok {
			return x.ListDir
		}
	}
	return nil
}

func (x *RpcResponse) GetStat() *StatResponse {
	if x != nil {
		if x, ok := x.Payload.(*RpcResponse_Stat); ok {
			return x.Stat
		}
	}
	return nil
}

func (x *RpcResponse) GetDelete() *DeleteResponse {
	if x != nil {
		if x, ok := x.Payload.(*RpcResponse_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *RpcResponse) GetRename() *RenameResponse {
	if x != nil {
		if x, ok := x.Payload.(*RpcResponse_Rename); ok {
			return x.Rename
		}
	}
	return nil
}

func (x *RpcResponse) GetMkdir() *MkdirResponse {
	if x != nil {
		if x, ok := x.Payload.(*RpcResponse_Mkdir); ok {
			return x.Mkdir
		}
	}
	return nil
}

func (x *RpcResponse) GetChmod() *ChmodResponse {
	if x != nil {
		if x, ok := x.Payload.(*RpcResponse_Chmod); ok {
			return x.Chmod
		}
	}
	return nil
}

func (x *RpcResponse) GetSysInfo() *SysInfoResponse {
	if x != nil {
		if x, ok := x.Payload.(*RpcResponse_SysInfo); ok {
			return x.SysInfo
		}
	}
	return nil
}

type isRpcResponse_Payload interface {
	isRpcResponse_Payload()
}

type RpcResponse_Exec struct {
	Exec *ExecResponse `protobuf:"bytes,10,opt,name=exec,proto3,oneof"`
}

type RpcResponse_ListDir struct {
	ListDir *ListDirResponse `protobuf:"bytes,20,opt,name=list_dir,json=listDir,proto3,oneof"`
}

type RpcResponse_Stat struct {
	Stat *StatResponse `protobuf:"bytes,21,opt,name=stat,proto3,oneof"`
}

type RpcResponse_Delete struct {
	Delete *DeleteResponse `protobuf:"bytes,22,opt,name=delete,proto3,oneof"`
}

type RpcResponse_Rename struct {
	Rename *RenameResponse `protobuf:"bytes,23,opt,name=rename,proto3,oneof"`
}

type RpcResponse_Mkdir struct {
	Mkdir *MkdirResponse `protobuf:"bytes,24,opt,name=mkdir,proto3,oneof"`
}

type RpcResponse_Chmod struct {
	Chmod *ChmodResponse `protobuf:"bytes,25,opt,name=chmod,proto3,oneof"`
}

type RpcResponse_SysInfo struct {
	SysInfo *SysInfoResponse `protobuf:"bytes,30,opt,name=sys_info,json=sysInfo,proto3,oneof"`
}

func (*RpcResponse_Exec) isRpcResponse_Payload() {}

func (*RpcResponse_ListDir) isRpcResponse_Payload() {}

func (*RpcResponse_Stat) isRpcResponse_Payload() {}

func (*RpcResponse_Delete) isRpcResponse_Payload() {}

func (*RpcResponse_Rename) isRpcResponse_Payload() {}

func (*RpcResponse_Mkdir) isRpcResponse_Payload() {}

func (*RpcResponse_Chmod) isRpcResponse_Payload() {}

func (*RpcResponse_SysInfo) isRpcResponse_Payload() {}

// --- One-shot exec ---
type ExecRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Command string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args    []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Cwd     string                 `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Env     map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Max wait in milliseconds; 0 = no deadline beyond context.
	TimeoutMs     uint32 `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ExecRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        []byte                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *ExecResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// --- Filesystem metadata ---
type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	MtimeUnixNano int64                  `protobuf:"varint,4,opt,name=mtime_unix_nano,json=mtimeUnixNano,proto3" json:"mtime_unix_nano,omitempty"`
	SymlinkTarget string                 `protobuf:"bytes,5,opt,name=symlink_target,json=symlinkTarget,proto3" json:"symlink_target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *FileEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileEntry) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileEntry) GetMtimeUnixNano() int64 {
	if x != nil {
		return x.MtimeUnixNano
	}
	return 0
}

func (x *FileEntry) GetSymlinkTarget() string {
	if x != nil {
		return x.SymlinkTarget
	}
	return ""
}

type ListDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirRequest) Reset() {
	*x = ListDirRequest{}
	mi := &file_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirRequest) ProtoMessage() {}

func (x *ListDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirRequest.ProtoReflect.Descriptor instead.
func (*ListDirRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *ListDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FileEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirResponse) Reset() {
	*x = ListDirResponse{}
	mi := &file_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirResponse) ProtoMessage() {}

func (x *ListDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirResponse.ProtoReflect.Descriptor instead.
func (*ListDirResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *ListDirResponse) GetEntries() []*FileEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListDirResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *FileEntry             `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *StatResponse) GetEntry() *FileEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *StatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeleteRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameRequest) Reset() {
	*x = RenameRequest{}
	mi := &file_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameRequest) ProtoMessage() {}

func (x *RenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameRequest.ProtoReflect.Descriptor instead.
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *RenameRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *RenameRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type RenameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameResponse) Reset() {
	*x = RenameResponse{}
	mi := &file_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameResponse) ProtoMessage() {}

func (x *RenameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameResponse.ProtoReflect.Descriptor instead.
func (*RenameResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *RenameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Mkdirs        bool                   `protobuf:"varint,3,opt,name=mkdirs,proto3" json:"mkdirs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *MkdirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MkdirRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *MkdirRequest) GetMkdirs() bool {
	if x != nil {
		return x.Mkdirs
	}
	return false
}

type MkdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirResponse) Reset() {
	*x = MkdirResponse{}
	mi := &file_rpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirResponse) ProtoMessage() {}

func (x *MkdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirResponse.ProtoReflect.Descriptor instead.
func (*MkdirResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{14}
}

func (x *MkdirResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ChmodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChmodRequest) Reset() {
	*x = ChmodRequest{}
	mi := &file_rpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChmodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChmodRequest) ProtoMessage() {}

func (x *ChmodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChmodRequest.ProtoReflect.Descriptor instead.
func (*ChmodRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{15}
}

func (x *ChmodRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ChmodRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type ChmodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChmodResponse) Reset() {
	*x = ChmodResponse{}
	mi := &file_rpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChmodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChmodResponse) ProtoMessage() {}

func (x *ChmodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChmodResponse.ProtoReflect.Descriptor instead.
func (*ChmodResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{16}
}

func (x *ChmodResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// --- System info (one-shot; periodic push uses EVENT stream) ---
type SysInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysInfoRequest) Reset() {
	*x = SysInfoRequest{}
	mi := &file_rpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysInfoRequest) ProtoMessage() {}

func (x *SysInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysInfoRequest.ProtoReflect.Descriptor instead.
func (*SysInfoRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{17}
}

// NetworkInterface describes a single NIC as seen by the agent.
// Addresses are in CIDR form (e.g. "192.168.1.10/24"); Mac is the
// hardware address (empty on loopback / virtual); Flags mirror the
// Go net.Interface.Flags string ("up|broadcast|multicast").
type NetworkInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	Addrs         []string               `protobuf:"bytes,3,rep,name=addrs,proto3" json:"addrs,omitempty"`
	Flags         string                 `protobuf:"bytes,4,opt,name=flags,proto3" json:"flags,omitempty"`
	Mtu           uint64                 `protobuf:"varint,5,opt,name=mtu,proto3" json:"mtu,omitempty"`
	IsUp          bool                   `protobuf:"varint,6,opt,name=is_up,json=isUp,proto3" json:"is_up,omitempty"`
	IsLoopback    bool                   `protobuf:"varint,7,opt,name=is_loopback,json=isLoopback,proto3" json:"is_loopback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterface) Reset() {
	*x = NetworkInterface{}
	mi := &file_rpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterface) ProtoMessage() {}

func (x *NetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterface.ProtoReflect.Descriptor instead.
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{18}
}

func (x *NetworkInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInterface) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *NetworkInterface) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *NetworkInterface) GetFlags() string {
	if x != nil {
		return x.Flags
	}
	return ""
}

func (x *NetworkInterface) GetMtu() uint64 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *NetworkInterface) GetIsUp() bool {
	if x != nil {
		return x.IsUp
	}
	return false
}

func (x *NetworkInterface) GetIsLoopback() bool {
	if x != nil {
		return x.IsLoopback
	}
	return false
}

// DiskPartition is a single filesystem mount point. TotalBytes /
// UsedBytes reflect the underlying storage; FsType is the kernel's
// filesystem name (ext4, xfs, apfs, NTFS, ...).
type DiskPartition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Mountpoint    string                 `protobuf:"bytes,2,opt,name=mountpoint,proto3" json:"mountpoint,omitempty"`
	Fstype        string                 `protobuf:"bytes,3,opt,name=fstype,proto3" json:"fstype,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	UsedBytes     uint64                 `protobuf:"varint,5,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskPartition) Reset() {
	*x = DiskPartition{}
	mi := &file_rpc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskPartition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskPartition) ProtoMessage() {}

func (x *DiskPartition) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskPartition.ProtoReflect.Descriptor instead.
func (*DiskPartition) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{19}
}

func (x *DiskPartition) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskPartition) GetMountpoint() string {
	if x != nil {
		return x.Mountpoint
	}
	return ""
}

func (x *DiskPartition) GetFstype() string {
	if x != nil {
		return x.Fstype
	}
	return ""
}

func (x *DiskPartition) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *DiskPartition) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

// UserSession identifies a currently-logged-in user. Empty on
// platforms where the enumeration isn't available (some embedded
// systems, sandboxed containers).
type UserSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Terminal      string                 `protobuf:"bytes,2,opt,name=terminal,proto3" json:"terminal,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	StartedAt     int64                  `protobuf:"varint,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSession) Reset() {
	*x = UserSession{}
	mi := &file_rpc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSession) ProtoMessage() {}

func (x *UserSession) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSession.ProtoReflect.Descriptor instead.
func (*UserSession) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{20}
}

func (x *UserSession) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *UserSession) GetTerminal() string {
	if x != nil {
		return x.Terminal
	}
	return ""
}

func (x *UserSession) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *UserSession) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

type SysInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	KernelVersion string                 `protobuf:"bytes,4,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,5,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemTotal      uint64                 `protobuf:"varint,6,opt,name=mem_total,json=memTotal,proto3" json:"mem_total,omitempty"`
	MemUsed       uint64                 `protobuf:"varint,7,opt,name=mem_used,json=memUsed,proto3" json:"mem_used,omitempty"`
	DiskTotal     uint64                 `protobuf:"varint,8,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"`
	DiskUsed      uint64                 `protobuf:"varint,9,opt,name=disk_used,json=diskUsed,proto3" json:"disk_used,omitempty"`
	// Deprecated: prefer `interfaces`. Kept for wire compat: keyed by
	// interface name, value is a comma-separated CIDR list.
	NetworkInterfaces map[string]string `protobuf:"bytes,10,rep,name=network_interfaces,json=networkInterfaces,proto3" json:"network_interfaces,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error             string            `protobuf:"bytes,11,opt,name=error,proto3" json:"error,omitempty"`
	// Platform identification.
	Platform        string `protobuf:"bytes,20,opt,name=platform,proto3" json:"platform,omitempty"`                                      // "ubuntu", "darwin", "windows", ...
	PlatformFamily  string `protobuf:"bytes,21,opt,name=platform_family,json=platformFamily,proto3" json:"platform_family,omitempty"`    // "debian", "rhel", "bsd", ...
	PlatformVersion string `protobuf:"bytes,22,opt,name=platform_version,json=platformVersion,proto3" json:"platform_version,omitempty"` // "22.04", "14.1", "10.0.19045", ...
	Virtualization  string `protobuf:"bytes,23,opt,name=virtualization,proto3" json:"virtualization,omitempty"`                          // "kvm", "docker", "wsl", "" (bare metal)
	Timezone        string `protobuf:"bytes,24,opt,name=timezone,proto3" json:"timezone,omitempty"`                                      // IANA tz name, e.g. "Asia/Shanghai"
	// Hardware.
	NumCpu         uint32  `protobuf:"varint,30,opt,name=num_cpu,json=numCpu,proto3" json:"num_cpu,omitempty"`                           // logical CPU count
	NumCpuPhysical uint32  `protobuf:"varint,31,opt,name=num_cpu_physical,json=numCpuPhysical,proto3" json:"num_cpu_physical,omitempty"` // physical core count (0 if unknown)
	CpuModel       string  `protobuf:"bytes,32,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`                      // brand string of CPU 0
	CpuMhz         float64 `protobuf:"fixed64,33,opt,name=cpu_mhz,json=cpuMhz,proto3" json:"cpu_mhz,omitempty"`
	// Memory breakdown.
	MemAvailable uint64 `protobuf:"varint,40,opt,name=mem_available,json=memAvailable,proto3" json:"mem_available,omitempty"`
	MemFree      uint64 `protobuf:"varint,41,opt,name=mem_free,json=memFree,proto3" json:"mem_free,omitempty"`
	SwapTotal    uint64 `protobuf:"varint,42,opt,name=swap_total,json=swapTotal,proto3" json:"swap_total,omitempty"`
	SwapUsed     uint64 `protobuf:"varint,43,opt,name=swap_used,json=swapUsed,proto3" json:"swap_used,omitempty"`
	// Uptime / boot.
	BootTimeUnix  uint64 `protobuf:"varint,50,opt,name=boot_time_unix,json=bootTimeUnix,proto3" json:"boot_time_unix,omitempty"`
	UptimeSeconds uint64 `protobuf:"varint,51,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Load (Linux/macOS). Zero on Windows.
	Load1  float64 `protobuf:"fixed64,60,opt,name=load1,proto3" json:"load1,omitempty"`
	Load5  float64 `protobuf:"fixed64,61,opt,name=load5,proto3" json:"load5,omitempty"`
	Load15 float64 `protobuf:"fixed64,62,opt,name=load15,proto3" json:"load15,omitempty"`
	// Process / user session count.
	ProcessCount uint32 `protobuf:"varint,70,opt,name=process_count,json=processCount,proto3" json:"process_count,omitempty"`
	// Identity.
	CurrentUser  string `protobuf:"bytes,80,opt,name=current_user,json=currentUser,proto3" json:"current_user,omitempty"` // e.g. "ubuntu", "root", "DESKTOP\\alice"
	AgentVersion string `protobuf:"bytes,81,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	MachineId    string `protobuf:"bytes,82,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	// Networking (rich).
	DefaultGateway string              `protobuf:"bytes,90,opt,name=default_gateway,json=defaultGateway,proto3" json:"default_gateway,omitempty"`
	PrimaryIp      string              `protobuf:"bytes,91,opt,name=primary_ip,json=primaryIp,proto3" json:"primary_ip,omitempty"` // source IP chosen for an outbound route
	PrimaryMac     string              `protobuf:"bytes,92,opt,name=primary_mac,json=primaryMac,proto3" json:"primary_mac,omitempty"`
	PublicIp       string              `protobuf:"bytes,93,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"` // best-effort (resolver-based); empty if unavailable
	Interfaces     []*NetworkInterface `protobuf:"bytes,94,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	// Disks (rich).
	Disks []*DiskPartition `protobuf:"bytes,100,rep,name=disks,proto3" json:"disks,omitempty"`
	// Logged-in users.
	Users []*UserSession `protobuf:"bytes,110,rep,name=users,proto3" json:"users,omitempty"`
	// When the snapshot was captured, agent-side wall clock.
	SampledAtUnix int64 `protobuf:"varint,120,opt,name=sampled_at_unix,json=sampledAtUnix,proto3" json:"sampled_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysInfoResponse) Reset() {
	*x = SysInfoResponse{}
	mi := &file_rpc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysInfoResponse) ProtoMessage() {}

func (x *SysInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysInfoResponse.ProtoReflect.Descriptor instead.
func (*SysInfoResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{21}
}

func (x *SysInfoResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SysInfoResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *SysInfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SysInfoResponse) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *SysInfoResponse) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *SysInfoResponse) GetMemTotal() uint64 {
	if x != nil {
		return x.MemTotal
	}
	return 0
}

func (x *SysInfoResponse) GetMemUsed() uint64 {
	if x != nil {
		return x.MemUsed
	}
	return 0
}

func (x *SysInfoResponse) GetDiskTotal() uint64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

func (x *SysInfoResponse) GetDiskUsed() uint64 {
	if x != nil {
		return x.DiskUsed
	}
	return 0
}

func (x *SysInfoResponse) GetNetworkInterfaces() map[string]string {
	if x != nil {
		return x.NetworkInterfaces
	}
	return nil
}

func (x *SysInfoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SysInfoResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SysInfoResponse) GetPlatformFamily() string {
	if x != nil {
		return x.PlatformFamily
	}
	return ""
}

func (x *SysInfoResponse) GetPlatformVersion() string {
	if x != nil {
		return x.PlatformVersion
	}
	return ""
}

func (x *SysInfoResponse) GetVirtualization() string {
	if x != nil {
		return x.Virtualization
	}
	return ""
}

func (x *SysInfoResponse) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *SysInfoResponse) GetNumCpu() uint32 {
	if x != nil {
		return x.NumCpu
	}
	return 0
}

func (x *SysInfoResponse) GetNumCpuPhysical() uint32 {
	if x != nil {
		return x.NumCpuPhysical
	}
	return 0
}

func (x *SysInfoResponse) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *SysInfoResponse) GetCpuMhz() float64 {
	if x != nil {
		return x.CpuMhz
	}
	return 0
}

func (x *SysInfoResponse) GetMemAvailable() uint64 {
	if x != nil {
		return x.MemAvailable
	}
	return 0
}

func (x *SysInfoResponse) GetMemFree() uint64 {
	if x != nil {
		return x.MemFree
	}
	return 0
}

func (x *SysInfoResponse) GetSwapTotal() uint64 {
	if x != nil {
		return x.SwapTotal
	}
	return 0
}

func (x *SysInfoResponse) GetSwapUsed() uint64 {
	if x != nil {
		return x.SwapUsed
	}
	return 0
}

func (x *SysInfoResponse) GetBootTimeUnix() uint64 {
	if x != nil {
		return x.BootTimeUnix
	}
	return 0
}

func (x *SysInfoResponse) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *SysInfoResponse) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *SysInfoResponse) GetLoad5() float64 {
	if x != nil {
		return x.Load5
	}
	return 0
}

func (x *SysInfoResponse) GetLoad15() float64 {
	if x != nil {
		return x.Load15
	}
	return 0
}

func (x *SysInfoResponse) GetProcessCount() uint32 {
	if x != nil {
		return x.ProcessCount
	}
	return 0
}

func (x *SysInfoResponse) GetCurrentUser() string {
	if x != nil {
		return x.CurrentUser
	}
	return ""
}

func (x *SysInfoResponse) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *SysInfoResponse) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *SysInfoResponse) GetDefaultGateway() string {
	if x != nil {
		return x.DefaultGateway
	}
	return ""
}

func (x *SysInfoResponse) GetPrimaryIp() string {
	if x != nil {
		return x.PrimaryIp
	}
	return ""
}

func (x *SysInfoResponse) GetPrimaryMac() string {
	if x != nil {
		return x.PrimaryMac
	}
	return ""
}

func (x *SysInfoResponse) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *SysInfoResponse) GetInterfaces() []*NetworkInterface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *SysInfoResponse) GetDisks() []*DiskPartition {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *SysInfoResponse) GetUsers() []*UserSession {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *SysInfoResponse) GetSampledAtUnix() int64 {
	if x != nil {
		return x.SampledAtUnix
	}
	return 0
}

var File_rpc_proto protoreflect.FileDescriptor

const file_rpc_proto_rawDesc = "" +
	"\n" +
	"\trpc.proto\x12\vplatypus.v2\"\xbd\x03\n" +
	"\n" +
	"RpcRequest\x12.\n" +
	"\x04exec\x18\n" +
	" \x01(\v2\x18.platypus.v2.ExecRequestH\x00R\x04exec\x128\n" +
	"\blist_dir\x18\x14 \x01(\v2\x1b.platypus.v2.ListDirRequestH\x00R\alistDir\x12.\n" +
	"\x04stat\x18\x15 \x01(\v2\x18.platypus.v2.StatRequestH\x00R\x04stat\x124\n" +
	"\x06delete\x18\x16 \x01(\v2\x1a.platypus.v2.DeleteRequestH\x00R\x06delete\x124\n" +
	"\x06rename\x18\x17 \x01(\v2\x1a.platypus.v2.RenameRequestH\x00R\x06rename\x121\n" +
	"\x05mkdir\x18\x18 \x01(\v2\x19.platypus.v2.MkdirRequestH\x00R\x05mkdir\x121\n" +
	"\x05chmod\x18\x19 \x01(\v2\x19.platypus.v2.ChmodRequestH\x00R\x05chmod\x128\n" +
	"\bsys_info\x18\x1e \x01(\v2\x1b.platypus.v2.SysInfoRequestH\x00R\asysInfoB\t\n" +
	"\apayload\"\xdc\x03\n" +
	"\vRpcResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12/\n" +
	"\x04exec\x18\n" +
	" \x01(\v2\x19.platypus.v2.ExecResponseH\x00R\x04exec\x129\n" +
	"\blist_dir\x18\x14 \x01(\v2\x1c.platypus.v2.ListDirResponseH\x00R\alistDir\x12/\n" +
	"\x04stat\x18\x15 \x01(\v2\x19.platypus.v2.StatResponseH\x00R\x04stat\x125\n" +
	"\x06delete\x18\x16 \x01(\v2\x1b.platypus.v2.DeleteResponseH\x00R\x06delete\x125\n" +
	"\x06rename\x18\x17 \x01(\v2\x1b.platypus.v2.RenameResponseH\x00R\x06rename\x122\n" +
	"\x05mkdir\x18\x18 \x01(\v2\x1a.platypus.v2.MkdirResponseH\x00R\x05mkdir\x122\n" +
	"\x05chmod\x18\x19 \x01(\v2\x1a.platypus.v2.ChmodResponseH\x00R\x05chmod\x129\n" +
	"\bsys_info\x18\x1e \x01(\v2\x1c.platypus.v2.SysInfoResponseH\x00R\asysInfoB\t\n" +
	"\apayload\"\xd9\x01\n" +
	"\vExecRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x123\n" +
	"\x03env\x18\x04 \x03(\v2!.platypus.v2.ExecRequest.EnvEntryR\x03env\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\rR\ttimeoutMs\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"q\n" +
	"\fExecResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\fR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x96\x01\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12&\n" +
	"\x0fmtime_unix_nano\x18\x04 \x01(\x03R\rmtimeUnixNano\x12%\n" +
	"\x0esymlink_target\x18\x05 \x01(\tR\rsymlinkTarget\"$\n" +
	"\x0eListDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"Y\n" +
	"\x0fListDirResponse\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.platypus.v2.FileEntryR\aentries\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"!\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"R\n" +
	"\fStatResponse\x12,\n" +
	"\x05entry\x18\x01 \x01(\v2\x16.platypus.v2.FileEntryR\x05entry\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"A\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"&\n" +
	"\x0eDeleteResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"3\n" +
	"\rRenameRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"&\n" +
	"\x0eRenameResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"N\n" +
	"\fMkdirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x16\n" +
	"\x06mkdirs\x18\x03 \x01(\bR\x06mkdirs\"%\n" +
	"\rMkdirResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"6\n" +
	"\fChmodRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\"%\n" +
	"\rChmodResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x10\n" +
	"\x0eSysInfoRequest\"\xac\x01\n" +
	"\x10NetworkInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12\x14\n" +
	"\x05addrs\x18\x03 \x03(\tR\x05addrs\x12\x14\n" +
	"\x05flags\x18\x04 \x01(\tR\x05flags\x12\x10\n" +
	"\x03mtu\x18\x05 \x01(\x04R\x03mtu\x12\x13\n" +
	"\x05is_up\x18\x06 \x01(\bR\x04isUp\x12\x1f\n" +
	"\vis_loopback\x18\a \x01(\bR\n" +
	"isLoopback\"\x9f\x01\n" +
	"\rDiskPartition\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1e\n" +
	"\n" +
	"mountpoint\x18\x02 \x01(\tR\n" +
	"mountpoint\x12\x16\n" +
	"\x06fstype\x18\x03 \x01(\tR\x06fstype\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x05 \x01(\x04R\tusedBytes\"p\n" +
	"\vUserSession\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1a\n" +
	"\bterminal\x18\x02 \x01(\tR\bterminal\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\x03R\tstartedAt\"\xe2\v\n" +
	"\x0fSysInfoResponse\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12%\n" +
	"\x0ekernel_version\x18\x04 \x01(\tR\rkernelVersion\x12\x1f\n" +
	"\vcpu_percent\x18\x05 \x01(\x01R\n" +
	"cpuPercent\x12\x1b\n" +
	"\tmem_total\x18\x06 \x01(\x04R\bmemTotal\x12\x19\n" +
	"\bmem_used\x18\a \x01(\x04R\amemUsed\x12\x1d\n" +
	"\n" +
	"disk_total\x18\b \x01(\x04R\tdiskTotal\x12\x1b\n" +
	"\tdisk_used\x18\t \x01(\x04R\bdiskUsed\x12b\n" +
	"\x12network_interfaces\x18\n" +
	" \x03(\v23.platypus.v2.SysInfoResponse.NetworkInterfacesEntryR\x11networkInterfaces\x12\x14\n" +
	"\x05error\x18\v \x01(\tR\x05error\x12\x1a\n" +
	"\bplatform\x18\x14 \x01(\tR\bplatform\x12'\n" +
	"\x0fplatform_family\x18\x15 \x01(\tR\x0eplatformFamily\x12)\n" +
	"\x10platform_version\x18\x16 \x01(\tR\x0fplatformVersion\x12&\n" +
	"\x0evirtualization\x18\x17 \x01(\tR\x0evirtualization\x12\x1a\n" +
	"\btimezone\x18\x18 \x01(\tR\btimezone\x12\x17\n" +
	"\anum_cpu\x18\x1e \x01(\rR\x06numCpu\x12(\n" +
	"\x10num_cpu_physical\x18\x1f \x01(\rR\x0enumCpuPhysical\x12\x1b\n" +
	"\tcpu_model\x18  \x01(\tR\bcpuModel\x12\x17\n" +
	"\acpu_mhz\x18! \x01(\x01R\x06cpuMhz\x12#\n" +
	"\rmem_available\x18( \x01(\x04R\fmemAvailable\x12\x19\n" +
	"\bmem_free\x18) \x01(\x04R\amemFree\x12\x1d\n" +
	"\n" +
	"swap_total\x18* \x01(\x04R\tswapTotal\x12\x1b\n" +
	"\tswap_used\x18+ \x01(\x04R\bswapUsed\x12$\n" +
	"\x0eboot_time_unix\x182 \x01(\x04R\fbootTimeUnix\x12%\n" +
	"\x0euptime_seconds\x183 \x01(\x04R\ruptimeSeconds\x12\x14\n" +
	"\x05load1\x18< \x01(\x01R\x05load1\x12\x14\n" +
	"\x05load5\x18= \x01(\x01R\x05load5\x12\x16\n" +
	"\x06load15\x18> \x01(\x01R\x06load15\x12#\n" +
	"\rprocess_count\x18F \x01(\rR\fprocessCount\x12!\n" +
	"\fcurrent_user\x18P \x01(\tR\vcurrentUser\x12#\n" +
	"\ragent_version\x18Q \x01(\tR\fagentVersion\x12\x1d\n" +
	"\n" +
	"machine_id\x18R \x01(\tR\tmachineId\x12'\n" +
	"\x0fdefault_gateway\x18Z \x01(\tR\x0edefaultGateway\x12\x1d\n" +
	"\n" +
	"primary_ip\x18[ \x01(\tR\tprimaryIp\x12\x1f\n" +
	"\vprimary_mac\x18\\ \x01(\tR\n" +
	"primaryMac\x12\x1b\n" +
	"\tpublic_ip\x18] \x01(\tR\bpublicIp\x12=\n" +
	"\n" +
	"interfaces\x18^ \x03(\v2\x1d.platypus.v2.NetworkInterfaceR\n" +
	"interfaces\x120\n" +
	"\x05disks\x18d \x03(\v2\x1a.platypus.v2.DiskPartitionR\x05disks\x12.\n" +
	"\x05users\x18n \x03(\v2\x18.platypus.v2.UserSessionR\x05users\x12&\n" +
	"\x0fsampled_at_unix\x18x \x01(\x03R\rsampledAtUnix\x1aD\n" +
	"\x16NetworkInterfacesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B2Z0github.com/WangYihang/Platypus/pkg/proto/v2;v2pbb\x06proto3"

var (
	file_rpc_proto_rawDescOnce sync.Once
	file_rpc_proto_rawDescData []byte
)

func file_rpc_proto_rawDescGZIP() []byte {
	file_rpc_proto_rawDescOnce.Do(func() {
		file_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)))
	})
	return file_rpc_proto_rawDescData
}

var file_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_rpc_proto_goTypes = []any{
	(*RpcRequest)(nil),       // 0: platypus.v2.RpcRequest
	(*RpcResponse)(nil),      // 1: platypus.v2.RpcResponse
	(*ExecRequest)(nil),      // 2: platypus.v2.ExecRequest
	(*ExecResponse)(nil),     // 3: platypus.v2.ExecResponse
	(*FileEntry)(nil),        // 4: platypus.v2.FileEntry
	(*ListDirRequest)(nil),   // 5: platypus.v2.ListDirRequest
	(*ListDirResponse)(nil),  // 6: platypus.v2.ListDirResponse
	(*StatRequest)(nil),      // 7: platypus.v2.StatRequest
	(*StatResponse)(nil),     // 8: platypus.v2.StatResponse
	(*DeleteRequest)(nil),    // 9: platypus.v2.DeleteRequest
	(*DeleteResponse)(nil),   // 10: platypus.v2.DeleteResponse
	(*RenameRequest)(nil),    // 11: platypus.v2.RenameRequest
	(*RenameResponse)(nil),   // 12: platypus.v2.RenameResponse
	(*MkdirRequest)(nil),     // 13: platypus.v2.MkdirRequest
	(*MkdirResponse)(nil),    // 14: platypus.v2.MkdirResponse
	(*ChmodRequest)(nil),     // 15: platypus.v2.ChmodRequest
	(*ChmodResponse)(nil),    // 16: platypus.v2.ChmodResponse
	(*SysInfoRequest)(nil),   // 17: platypus.v2.SysInfoRequest
	(*NetworkInterface)(nil), // 18: platypus.v2.NetworkInterface
	(*DiskPartition)(nil),    // 19: platypus.v2.DiskPartition
	(*UserSession)(nil),      // 20: platypus.v2.UserSession
	(*SysInfoResponse)(nil),  // 21: platypus.v2.SysInfoResponse
	nil,                      // 22: platypus.v2.ExecRequest.EnvEntry
	nil,                      // 23: platypus.v2.SysInfoResponse.NetworkInterfacesEntry
}
var file_rpc_proto_depIdxs = []int32{
	2,  // 0: platypus.v2.RpcRequest.exec:type_name -> platypus.v2.ExecRequest
	5,  // 1: platypus.v2.RpcRequest.list_dir:type_name -> platypus.v2.ListDirRequest
	7,  // 2: platypus.v2.RpcRequest.stat:type_name -> platypus.v2.StatRequest
	9,  // 3: platypus.v2.RpcRequest.delete:type_name -> platypus.v2.DeleteRequest
	11, // 4: platypus.v2.RpcRequest.rename:type_name -> platypus.v2.RenameRequest
	13, // 5: platypus.v2.RpcRequest.mkdir:type_name -> platypus.v2.MkdirRequest
	15, // 6: platypus.v2.RpcRequest.chmod:type_name -> platypus.v2.ChmodRequest
	17, // 7: platypus.v2.RpcRequest.sys_info:type_name -> platypus.v2.SysInfoRequest
	3,  // 8: platypus.v2.RpcResponse.exec:type_name -> platypus.v2.ExecResponse
	6,  // 9: platypus.v2.RpcResponse.list_dir:type_name -> platypus.v2.ListDirResponse
	8,  // 10: platypus.v2.RpcResponse.stat:type_name -> platypus.v2.StatResponse
	10, // 11: platypus.v2.RpcResponse.delete:type_name -> platypus.v2.DeleteResponse
	12, // 12: platypus.v2.RpcResponse.rename:type_name -> platypus.v2.RenameResponse
	14, // 13: platypus.v2.RpcResponse.mkdir:type_name -> platypus.v2.MkdirResponse
	16, // 14: platypus.v2.RpcResponse.chmod:type_name -> platypus.v2.ChmodResponse
	21, // 15: platypus.v2.RpcResponse.sys_info:type_name -> platypus.v2.SysInfoResponse
	22, // 16: platypus.v2.ExecRequest.env:type_name -> platypus.v2.ExecRequest.EnvEntry
	4,  // 17: platypus.v2.ListDirResponse.entries:type_name -> platypus.v2.FileEntry
	4,  // 18: platypus.v2.StatResponse.entry:type_name -> platypus.v2.FileEntry
	23, // 19: platypus.v2.SysInfoResponse.network_interfaces:type_name -> platypus.v2.SysInfoResponse.NetworkInterfacesEntry
	18, // 20: platypus.v2.SysInfoResponse.interfaces:type_name -> platypus.v2.NetworkInterface
	19, // 21: platypus.v2.SysInfoResponse.disks:type_name -> platypus.v2.DiskPartition
	20, // 22: platypus.v2.SysInfoResponse.users:type_name -> platypus.v2.UserSession
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_rpc_proto_init() }
func file_rpc_proto_init() {
	if File_rpc_proto != nil {
		return
	}
	file_rpc_proto_msgTypes[0].OneofWrappers = []any{
		(*RpcRequest_Exec)(nil),
		(*RpcRequest_ListDir)(nil),
		(*RpcRequest_Stat)(nil),
		(*RpcRequest_Delete)(nil),
		(*RpcRequest_Rename)(nil),
		(*RpcRequest_Mkdir)(nil),
		(*RpcRequest_Chmod)(nil),
		(*RpcRequest_SysInfo)(nil),
	}
	file_rpc_proto_msgTypes[1].OneofWrappers = []any{
		(*RpcResponse_Exec)(nil),
		(*RpcResponse_ListDir)(nil),
		(*RpcResponse_Stat)(nil),
		(*RpcResponse_Delete)(nil),
		(*RpcResponse_Rename)(nil),
		(*RpcResponse_Mkdir)(nil),
		(*RpcResponse_Chmod)(nil),
		(*RpcResponse_SysInfo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_depIdxs,
		MessageInfos:      file_rpc_proto_msgTypes,
	}.Build()
	File_rpc_proto = out.File
	file_rpc_proto_goTypes = nil
	file_rpc_proto_depIdxs = nil
}
