// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sys_file_caps.proto

package v2pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileCapsListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Roots to walk. Empty = the plugin's default
	// (/usr/bin, /usr/sbin, /usr/local/bin, /usr/local/sbin,
	//
	//	/bin, /sbin, /opt). Operator can narrow to /opt for a faster
	//
	// scan, or expand to /home for a paranoid sweep.
	Roots []string `protobuf:"bytes,1,rep,name=roots,proto3" json:"roots,omitempty"`
	// Hard cap on binaries reported. 0 = no cap. The plugin always
	// walks every root in full (no early exit at the cap), so this
	// only trims the response.
	MaxResults uint32 `protobuf:"varint,2,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	// When true, allowlisted entries (ping, mtr, …) are ALSO returned
	// with `allowlisted=true`. Defaults to false: operators usually
	// want only the outliers.
	IncludeAllowlisted bool `protobuf:"varint,3,opt,name=include_allowlisted,json=includeAllowlisted,proto3" json:"include_allowlisted,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FileCapsListRequest) Reset() {
	*x = FileCapsListRequest{}
	mi := &file_sys_file_caps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileCapsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCapsListRequest) ProtoMessage() {}

func (x *FileCapsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_file_caps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCapsListRequest.ProtoReflect.Descriptor instead.
func (*FileCapsListRequest) Descriptor() ([]byte, []int) {
	return file_sys_file_caps_proto_rawDescGZIP(), []int{0}
}

func (x *FileCapsListRequest) GetRoots() []string {
	if x != nil {
		return x.Roots
	}
	return nil
}

func (x *FileCapsListRequest) GetMaxResults() uint32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

func (x *FileCapsListRequest) GetIncludeAllowlisted() bool {
	if x != nil {
		return x.IncludeAllowlisted
	}
	return false
}

type FileCapsListResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Entries []*FileCap             `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// Set when at least one root was walked successfully. Empty
	// string indicates a hard error (getcap missing, no roots
	// accessible).
	Backend       string `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"` // "getcap" | ""
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileCapsListResponse) Reset() {
	*x = FileCapsListResponse{}
	mi := &file_sys_file_caps_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileCapsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCapsListResponse) ProtoMessage() {}

func (x *FileCapsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_file_caps_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCapsListResponse.ProtoReflect.Descriptor instead.
func (*FileCapsListResponse) Descriptor() ([]byte, []int) {
	return file_sys_file_caps_proto_rawDescGZIP(), []int{1}
}

func (x *FileCapsListResponse) GetEntries() []*FileCap {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *FileCapsListResponse) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *FileCapsListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// FileCap is one binary that carries Linux capabilities. caps is the
// raw `cap_x,cap_y=flags` string from getcap (e.g. "cap_net_raw=ep",
// "cap_dac_read_search,cap_net_admin=eip"). allowlisted=true means
// the binary's basename is on a curated list of known-OK files.
type FileCap struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Path        string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // "/usr/bin/ping"
	Caps        string                 `protobuf:"bytes,2,opt,name=caps,proto3" json:"caps,omitempty"` // "cap_net_raw=ep"
	Allowlisted bool                   `protobuf:"varint,3,opt,name=allowlisted,proto3" json:"allowlisted,omitempty"`
	// Risk classification mirroring SUID outliers' severity ladder:
	// "low" for narrow caps (cap_net_raw, cap_net_bind_service),
	// "medium" for moderately powerful (cap_net_admin, cap_sys_time),
	// "high" for near-root (cap_dac_read_search, cap_dac_override,
	// cap_sys_admin, cap_sys_module, cap_sys_ptrace).
	Risk          string `protobuf:"bytes,4,opt,name=risk,proto3" json:"risk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileCap) Reset() {
	*x = FileCap{}
	mi := &file_sys_file_caps_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileCap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCap) ProtoMessage() {}

func (x *FileCap) ProtoReflect() protoreflect.Message {
	mi := &file_sys_file_caps_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCap.ProtoReflect.Descriptor instead.
func (*FileCap) Descriptor() ([]byte, []int) {
	return file_sys_file_caps_proto_rawDescGZIP(), []int{2}
}

func (x *FileCap) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileCap) GetCaps() string {
	if x != nil {
		return x.Caps
	}
	return ""
}

func (x *FileCap) GetAllowlisted() bool {
	if x != nil {
		return x.Allowlisted
	}
	return false
}

func (x *FileCap) GetRisk() string {
	if x != nil {
		return x.Risk
	}
	return ""
}

var File_sys_file_caps_proto protoreflect.FileDescriptor

const file_sys_file_caps_proto_rawDesc = "" +
	"\n" +
	"\x13sys_file_caps.proto\x12\vplatypus.v2\"}\n" +
	"\x13FileCapsListRequest\x12\x14\n" +
	"\x05roots\x18\x01 \x03(\tR\x05roots\x12\x1f\n" +
	"\vmax_results\x18\x02 \x01(\rR\n" +
	"maxResults\x12/\n" +
	"\x13include_allowlisted\x18\x03 \x01(\bR\x12includeAllowlisted\"v\n" +
	"\x14FileCapsListResponse\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.platypus.v2.FileCapR\aentries\x12\x18\n" +
	"\abackend\x18\x02 \x01(\tR\abackend\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"g\n" +
	"\aFileCap\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04caps\x18\x02 \x01(\tR\x04caps\x12 \n" +
	"\vallowlisted\x18\x03 \x01(\bR\vallowlisted\x12\x12\n" +
	"\x04risk\x18\x04 \x01(\tR\x04riskB2Z0github.com/WangYihang/Platypus/pkg/proto/v2;v2pbb\x06proto3"

var (
	file_sys_file_caps_proto_rawDescOnce sync.Once
	file_sys_file_caps_proto_rawDescData []byte
)

func file_sys_file_caps_proto_rawDescGZIP() []byte {
	file_sys_file_caps_proto_rawDescOnce.Do(func() {
		file_sys_file_caps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sys_file_caps_proto_rawDesc), len(file_sys_file_caps_proto_rawDesc)))
	})
	return file_sys_file_caps_proto_rawDescData
}

var file_sys_file_caps_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sys_file_caps_proto_goTypes = []any{
	(*FileCapsListRequest)(nil),  // 0: platypus.v2.FileCapsListRequest
	(*FileCapsListResponse)(nil), // 1: platypus.v2.FileCapsListResponse
	(*FileCap)(nil),              // 2: platypus.v2.FileCap
}
var file_sys_file_caps_proto_depIdxs = []int32{
	2, // 0: platypus.v2.FileCapsListResponse.entries:type_name -> platypus.v2.FileCap
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sys_file_caps_proto_init() }
func file_sys_file_caps_proto_init() {
	if File_sys_file_caps_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sys_file_caps_proto_rawDesc), len(file_sys_file_caps_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sys_file_caps_proto_goTypes,
		DependencyIndexes: file_sys_file_caps_proto_depIdxs,
		MessageInfos:      file_sys_file_caps_proto_msgTypes,
	}.Build()
	File_sys_file_caps_proto = out.File
	file_sys_file_caps_proto_goTypes = nil
	file_sys_file_caps_proto_depIdxs = nil
}
