// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sys_cron.proto

package v2pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CronListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When false (default), only enabled / runnable jobs are returned.
	// When true, commented-out jobs and run-parts directory entries
	// are also included so an operator auditing for "jobs that USED to
	// run" can find them.
	IncludeDisabled bool `protobuf:"varint,1,opt,name=include_disabled,json=includeDisabled,proto3" json:"include_disabled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CronListRequest) Reset() {
	*x = CronListRequest{}
	mi := &file_sys_cron_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronListRequest) ProtoMessage() {}

func (x *CronListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_cron_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronListRequest.ProtoReflect.Descriptor instead.
func (*CronListRequest) Descriptor() ([]byte, []int) {
	return file_sys_cron_proto_rawDescGZIP(), []int{0}
}

func (x *CronListRequest) GetIncludeDisabled() bool {
	if x != nil {
		return x.IncludeDisabled
	}
	return false
}

type CronListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*CronJob             `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronListResponse) Reset() {
	*x = CronListResponse{}
	mi := &file_sys_cron_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronListResponse) ProtoMessage() {}

func (x *CronListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_cron_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronListResponse.ProtoReflect.Descriptor instead.
func (*CronListResponse) Descriptor() ([]byte, []int) {
	return file_sys_cron_proto_rawDescGZIP(), []int{1}
}

func (x *CronListResponse) GetJobs() []*CronJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *CronListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// CronJob is one scheduled-execution row. The fields cover both
// crontab-format entries and run-parts directory scripts; not every
// field applies to every kind:
//
//	kind="crontab" / "system_crontab" / "cron_d" — full schedule
//	kind="run_parts" — schedule is the directory's cadence
//	                   ("hourly"/"daily"/"weekly"/"monthly"),
//	                   command is the script path. user is "root".
//	kind="anacron" — anacrontab entry. user is "root".
type CronJob struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Where the entry came from. One of:
	//
	//	"/etc/crontab", "/etc/cron.d/<file>",
	//	"/var/spool/cron/crontabs/<user>", "/var/spool/cron/<user>",
	//	"/etc/cron.daily" (and friends),
	//	"/etc/anacrontab".
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// The user that owns the schedule. Empty when the source doesn't
	// carry a user field and we couldn't infer one.
	User string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// The schedule expression as it appears in the source. Five
	// tokens for cron format; "@reboot"/"@daily"/etc. for shorthand;
	// the directory cadence for run_parts; the period+delay for
	// anacron.
	Schedule string `protobuf:"bytes,3,opt,name=schedule,proto3" json:"schedule,omitempty"`
	// The command to run.
	Command string `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	// "crontab" | "system_crontab" | "cron_d" | "run_parts" | "anacron"
	Kind string `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	// 1-based line number within `source` (0 for run_parts).
	LineNo uint32 `protobuf:"varint,6,opt,name=line_no,json=lineNo,proto3" json:"line_no,omitempty"`
	// True when the line was uncommented in the source. Hidden by
	// default (include_disabled=false).
	Enabled       bool `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronJob) Reset() {
	*x = CronJob{}
	mi := &file_sys_cron_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronJob) ProtoMessage() {}

func (x *CronJob) ProtoReflect() protoreflect.Message {
	mi := &file_sys_cron_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronJob.ProtoReflect.Descriptor instead.
func (*CronJob) Descriptor() ([]byte, []int) {
	return file_sys_cron_proto_rawDescGZIP(), []int{2}
}

func (x *CronJob) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CronJob) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *CronJob) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *CronJob) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CronJob) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CronJob) GetLineNo() uint32 {
	if x != nil {
		return x.LineNo
	}
	return 0
}

func (x *CronJob) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

var File_sys_cron_proto protoreflect.FileDescriptor

const file_sys_cron_proto_rawDesc = "" +
	"\n" +
	"\x0esys_cron.proto\x12\vplatypus.v2\"<\n" +
	"\x0fCronListRequest\x12)\n" +
	"\x10include_disabled\x18\x01 \x01(\bR\x0fincludeDisabled\"R\n" +
	"\x10CronListResponse\x12(\n" +
	"\x04jobs\x18\x01 \x03(\v2\x14.platypus.v2.CronJobR\x04jobs\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xb2\x01\n" +
	"\aCronJob\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x1a\n" +
	"\bschedule\x18\x03 \x01(\tR\bschedule\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12\x17\n" +
	"\aline_no\x18\x06 \x01(\rR\x06lineNo\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabledB2Z0github.com/WangYihang/Platypus/pkg/proto/v2;v2pbb\x06proto3"

var (
	file_sys_cron_proto_rawDescOnce sync.Once
	file_sys_cron_proto_rawDescData []byte
)

func file_sys_cron_proto_rawDescGZIP() []byte {
	file_sys_cron_proto_rawDescOnce.Do(func() {
		file_sys_cron_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sys_cron_proto_rawDesc), len(file_sys_cron_proto_rawDesc)))
	})
	return file_sys_cron_proto_rawDescData
}

var file_sys_cron_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sys_cron_proto_goTypes = []any{
	(*CronListRequest)(nil),  // 0: platypus.v2.CronListRequest
	(*CronListResponse)(nil), // 1: platypus.v2.CronListResponse
	(*CronJob)(nil),          // 2: platypus.v2.CronJob
}
var file_sys_cron_proto_depIdxs = []int32{
	2, // 0: platypus.v2.CronListResponse.jobs:type_name -> platypus.v2.CronJob
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sys_cron_proto_init() }
func file_sys_cron_proto_init() {
	if File_sys_cron_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sys_cron_proto_rawDesc), len(file_sys_cron_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sys_cron_proto_goTypes,
		DependencyIndexes: file_sys_cron_proto_depIdxs,
		MessageInfos:      file_sys_cron_proto_msgTypes,
	}.Build()
	File_sys_cron_proto = out.File
	file_sys_cron_proto_goTypes = nil
	file_sys_cron_proto_depIdxs = nil
}
