// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sys_procs.proto

package v2pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProcessInfo is a single OS process snapshot. cmdline is truncated
// to 512 bytes agent-side to bound payload size.
type ProcessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid          uint32                 `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Cmdline       string                 `protobuf:"bytes,5,opt,name=cmdline,proto3" json:"cmdline,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // gopsutil Status() string, e.g. "S", "R"
	CpuPercent    float64                `protobuf:"fixed64,7,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent    float64                `protobuf:"fixed64,8,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	RssBytes      uint64                 `protobuf:"varint,9,opt,name=rss_bytes,json=rssBytes,proto3" json:"rss_bytes,omitempty"`
	NumThreads    uint32                 `protobuf:"varint,10,opt,name=num_threads,json=numThreads,proto3" json:"num_threads,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,11,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_sys_procs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sys_procs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_sys_procs_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessInfo) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetPpid() uint32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *ProcessInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ProcessInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessInfo) GetCmdline() string {
	if x != nil {
		return x.Cmdline
	}
	return ""
}

func (x *ProcessInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessInfo) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessInfo) GetMemPercent() float64 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *ProcessInfo) GetRssBytes() uint64 {
	if x != nil {
		return x.RssBytes
	}
	return 0
}

func (x *ProcessInfo) GetNumThreads() uint32 {
	if x != nil {
		return x.NumThreads
	}
	return 0
}

func (x *ProcessInfo) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

// ProcessListRequest selects how many processes to return and how to
// sort them. top_n=0 means "all", capped at 500 server-side to keep
// the payload bounded.
type ProcessListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopN          uint32                 `protobuf:"varint,1,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"`
	SortBy        string                 `protobuf:"bytes,2,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"` // "cpu" (default) | "mem" | "rss" | "pid"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessListRequest) Reset() {
	*x = ProcessListRequest{}
	mi := &file_sys_procs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessListRequest) ProtoMessage() {}

func (x *ProcessListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_procs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessListRequest.ProtoReflect.Descriptor instead.
func (*ProcessListRequest) Descriptor() ([]byte, []int) {
	return file_sys_procs_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessListRequest) GetTopN() uint32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

func (x *ProcessListRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

type ProcessListResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Processes []*ProcessInfo         `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	// Total process count before top_n slicing; useful for the UI to
	// show "30 of 412 processes".
	TotalCount    uint32 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessListResponse) Reset() {
	*x = ProcessListResponse{}
	mi := &file_sys_procs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessListResponse) ProtoMessage() {}

func (x *ProcessListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_procs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessListResponse.ProtoReflect.Descriptor instead.
func (*ProcessListResponse) Descriptor() ([]byte, []int) {
	return file_sys_procs_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessListResponse) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *ProcessListResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ProcessListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_sys_procs_proto protoreflect.FileDescriptor

const file_sys_procs_proto_rawDesc = "" +
	"\n" +
	"\x0fsys_procs.proto\x12\vplatypus.v2\"\xb5\x02\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x12\n" +
	"\x04ppid\x18\x02 \x01(\rR\x04ppid\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\acmdline\x18\x05 \x01(\tR\acmdline\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1f\n" +
	"\vcpu_percent\x18\a \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\b \x01(\x01R\n" +
	"memPercent\x12\x1b\n" +
	"\trss_bytes\x18\t \x01(\x04R\brssBytes\x12\x1f\n" +
	"\vnum_threads\x18\n" +
	" \x01(\rR\n" +
	"numThreads\x12&\n" +
	"\x0fcreated_at_unix\x18\v \x01(\x03R\rcreatedAtUnix\"B\n" +
	"\x12ProcessListRequest\x12\x13\n" +
	"\x05top_n\x18\x01 \x01(\rR\x04topN\x12\x17\n" +
	"\asort_by\x18\x02 \x01(\tR\x06sortBy\"\x84\x01\n" +
	"\x13ProcessListResponse\x126\n" +
	"\tprocesses\x18\x01 \x03(\v2\x18.platypus.v2.ProcessInfoR\tprocesses\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\rR\n" +
	"totalCount\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05errorB2Z0github.com/WangYihang/Platypus/pkg/proto/v2;v2pbb\x06proto3"

var (
	file_sys_procs_proto_rawDescOnce sync.Once
	file_sys_procs_proto_rawDescData []byte
)

func file_sys_procs_proto_rawDescGZIP() []byte {
	file_sys_procs_proto_rawDescOnce.Do(func() {
		file_sys_procs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sys_procs_proto_rawDesc), len(file_sys_procs_proto_rawDesc)))
	})
	return file_sys_procs_proto_rawDescData
}

var file_sys_procs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sys_procs_proto_goTypes = []any{
	(*ProcessInfo)(nil),         // 0: platypus.v2.ProcessInfo
	(*ProcessListRequest)(nil),  // 1: platypus.v2.ProcessListRequest
	(*ProcessListResponse)(nil), // 2: platypus.v2.ProcessListResponse
}
var file_sys_procs_proto_depIdxs = []int32{
	0, // 0: platypus.v2.ProcessListResponse.processes:type_name -> platypus.v2.ProcessInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sys_procs_proto_init() }
func file_sys_procs_proto_init() {
	if File_sys_procs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sys_procs_proto_rawDesc), len(file_sys_procs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sys_procs_proto_goTypes,
		DependencyIndexes: file_sys_procs_proto_depIdxs,
		MessageInfos:      file_sys_procs_proto_msgTypes,
	}.Build()
	File_sys_procs_proto = out.File
	file_sys_procs_proto_goTypes = nil
	file_sys_procs_proto_depIdxs = nil
}
