// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: tunnel.proto

package v2pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Socks5CtlRequest_Action int32

const (
	Socks5CtlRequest_ACTION_UNSPECIFIED Socks5CtlRequest_Action = 0
	Socks5CtlRequest_ACTION_START       Socks5CtlRequest_Action = 1
	Socks5CtlRequest_ACTION_STOP        Socks5CtlRequest_Action = 2
)

// Enum value maps for Socks5CtlRequest_Action.
var (
	Socks5CtlRequest_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_START",
		2: "ACTION_STOP",
	}
	Socks5CtlRequest_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_START":       1,
		"ACTION_STOP":        2,
	}
)

func (x Socks5CtlRequest_Action) Enum() *Socks5CtlRequest_Action {
	p := new(Socks5CtlRequest_Action)
	*p = x
	return p
}

func (x Socks5CtlRequest_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Socks5CtlRequest_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_tunnel_proto_enumTypes[0].Descriptor()
}

func (Socks5CtlRequest_Action) Type() protoreflect.EnumType {
	return &file_tunnel_proto_enumTypes[0]
}

func (x Socks5CtlRequest_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Socks5CtlRequest_Action.Descriptor instead.
func (Socks5CtlRequest_Action) EnumDescriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{4, 0}
}

// TunnelPullRequest opens a local-to-remote tunnel (server->agent).
// The agent dials `target` from its own network; after ack the
// stream carries raw TCP bytes bidirectionally.
type TunnelPullRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// "host:port" dialable from the agent's network.
	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// Dial timeout in milliseconds. 0 = 10s default.
	DialTimeoutMs uint32 `protobuf:"varint,2,opt,name=dial_timeout_ms,json=dialTimeoutMs,proto3" json:"dial_timeout_ms,omitempty"`
}

func (x *TunnelPullRequest) Reset() {
	*x = TunnelPullRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tunnel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TunnelPullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelPullRequest) ProtoMessage() {}

func (x *TunnelPullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelPullRequest.ProtoReflect.Descriptor instead.
func (*TunnelPullRequest) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *TunnelPullRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *TunnelPullRequest) GetDialTimeoutMs() uint32 {
	if x != nil {
		return x.DialTimeoutMs
	}
	return 0
}

type TunnelPullResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Local address the agent actually dialed (after resolution);
	// useful for audit logs. Empty on non-TCP or unsupported.
	ResolvedAddr string `protobuf:"bytes,1,opt,name=resolved_addr,json=resolvedAddr,proto3" json:"resolved_addr,omitempty"`
	// Populated when the agent could not establish the connection
	// (DNS failure, refused, timeout). When non-empty the stream
	// closes immediately after this frame; no byte stream follows.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *TunnelPullResponse) Reset() {
	*x = TunnelPullResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tunnel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TunnelPullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelPullResponse) ProtoMessage() {}

func (x *TunnelPullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelPullResponse.ProtoReflect.Descriptor instead.
func (*TunnelPullResponse) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *TunnelPullResponse) GetResolvedAddr() string {
	if x != nil {
		return x.ResolvedAddr
	}
	return ""
}

func (x *TunnelPullResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// TunnelPushRequest opens a remote-to-local tunnel (agent->server).
// The agent has already accepted an inbound TCP conn on the
// operator-configured listen address; the server must dial the
// pre-configured local_target and splice both ends.
type TunnelPushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Opaque listen-config identifier (previously "address" in v1).
	// The server looks this up in its push-tunnel config map.
	ListenConfigId string `protobuf:"bytes,1,opt,name=listen_config_id,json=listenConfigId,proto3" json:"listen_config_id,omitempty"`
	// Remote peer address observed by the agent. Advisory only.
	PeerAddr string `protobuf:"bytes,2,opt,name=peer_addr,json=peerAddr,proto3" json:"peer_addr,omitempty"`
}

func (x *TunnelPushRequest) Reset() {
	*x = TunnelPushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tunnel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TunnelPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelPushRequest) ProtoMessage() {}

func (x *TunnelPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelPushRequest.ProtoReflect.Descriptor instead.
func (*TunnelPushRequest) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *TunnelPushRequest) GetListenConfigId() string {
	if x != nil {
		return x.ListenConfigId
	}
	return ""
}

func (x *TunnelPushRequest) GetPeerAddr() string {
	if x != nil {
		return x.PeerAddr
	}
	return ""
}

type TunnelPushResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Address the server dialed locally, for audit.
	ResolvedAddr string `protobuf:"bytes,1,opt,name=resolved_addr,json=resolvedAddr,proto3" json:"resolved_addr,omitempty"`
	// Populated when the server could not dial its pre-configured
	// local target (config id missing, connect refused). Agent
	// closes the stream after this frame.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *TunnelPushResponse) Reset() {
	*x = TunnelPushResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tunnel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TunnelPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelPushResponse) ProtoMessage() {}

func (x *TunnelPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelPushResponse.ProtoReflect.Descriptor instead.
func (*TunnelPushResponse) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *TunnelPushResponse) GetResolvedAddr() string {
	if x != nil {
		return x.ResolvedAddr
	}
	return ""
}

func (x *TunnelPushResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Socks5CtlRequest is the STREAM_TYPE_SOCKS5_CTL header metadata.
// This is a short-lived control RPC; the stream closes after the
// agent confirms start or stop.
type Socks5CtlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action Socks5CtlRequest_Action `protobuf:"varint,1,opt,name=action,proto3,enum=platypus.v2.Socks5CtlRequest_Action" json:"action,omitempty"`
	// Logical tunnel id (operator-assigned). On ACTION_START, agent
	// tracks by this id; on ACTION_STOP, agent tears down the
	// listener with this id.
	TunnelId string `protobuf:"bytes,2,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	// Bind address for ACTION_START. Usually 127.0.0.1:0 to let the
	// agent pick a port; the chosen port comes back in the response.
	BindAddr string `protobuf:"bytes,3,opt,name=bind_addr,json=bindAddr,proto3" json:"bind_addr,omitempty"`
}

func (x *Socks5CtlRequest) Reset() {
	*x = Socks5CtlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tunnel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Socks5CtlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Socks5CtlRequest) ProtoMessage() {}

func (x *Socks5CtlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Socks5CtlRequest.ProtoReflect.Descriptor instead.
func (*Socks5CtlRequest) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *Socks5CtlRequest) GetAction() Socks5CtlRequest_Action {
	if x != nil {
		return x.Action
	}
	return Socks5CtlRequest_ACTION_UNSPECIFIED
}

func (x *Socks5CtlRequest) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *Socks5CtlRequest) GetBindAddr() string {
	if x != nil {
		return x.BindAddr
	}
	return ""
}

type Socks5CtlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoundAddr string `protobuf:"bytes,1,opt,name=bound_addr,json=boundAddr,proto3" json:"bound_addr,omitempty"`
}

func (x *Socks5CtlResponse) Reset() {
	*x = Socks5CtlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tunnel_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Socks5CtlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Socks5CtlResponse) ProtoMessage() {}

func (x *Socks5CtlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Socks5CtlResponse.ProtoReflect.Descriptor instead.
func (*Socks5CtlResponse) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{5}
}

func (x *Socks5CtlResponse) GetBoundAddr() string {
	if x != nil {
		return x.BoundAddr
	}
	return ""
}

var File_tunnel_proto protoreflect.FileDescriptor

var file_tunnel_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x70, 0x6c, 0x61, 0x74, 0x79, 0x70, 0x75, 0x73, 0x2e, 0x76, 0x32, 0x22, 0x53, 0x0a, 0x11, 0x54,
	0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x64, 0x69, 0x61, 0x6c,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0d, 0x64, 0x69, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d, 0x73,
	0x22, 0x4f, 0x0a, 0x12, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x64, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72,
	0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x41, 0x64, 0x64, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x5a, 0x0a, 0x11, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x50, 0x75, 0x73, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e,
	0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x65, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x22, 0x4f, 0x0a,
	0x12, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f,
	0x6c, 0x76, 0x65, 0x64, 0x41, 0x64, 0x64, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xcf,
	0x01, 0x0a, 0x10, 0x53, 0x6f, 0x63, 0x6b, 0x73, 0x35, 0x43, 0x74, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x79, 0x70, 0x75, 0x73, 0x2e, 0x76,
	0x32, 0x2e, 0x53, 0x6f, 0x63, 0x6b, 0x73, 0x35, 0x43, 0x74, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x62, 0x69, 0x6e, 0x64, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x62, 0x69, 0x6e, 0x64, 0x41, 0x64, 0x64, 0x72, 0x22, 0x43, 0x0a, 0x06, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x12, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x10, 0x0a,
	0x0c, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x01, 0x12,
	0x0f, 0x0a, 0x0b, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x10, 0x02,
	0x22, 0x32, 0x0a, 0x11, 0x53, 0x6f, 0x63, 0x6b, 0x73, 0x35, 0x43, 0x74, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6f, 0x75, 0x6e, 0x64,
	0x41, 0x64, 0x64, 0x72, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x57, 0x61, 0x6e, 0x67, 0x59, 0x69, 0x68, 0x61, 0x6e, 0x67, 0x2f, 0x50, 0x6c,
	0x61, 0x74, 0x79, 0x70, 0x75, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x76, 0x32, 0x3b, 0x76, 0x32, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tunnel_proto_rawDescOnce sync.Once
	file_tunnel_proto_rawDescData = file_tunnel_proto_rawDesc
)

func file_tunnel_proto_rawDescGZIP() []byte {
	file_tunnel_proto_rawDescOnce.Do(func() {
		file_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(file_tunnel_proto_rawDescData)
	})
	return file_tunnel_proto_rawDescData
}

var file_tunnel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tunnel_proto_goTypes = []interface{}{
	(Socks5CtlRequest_Action)(0), // 0: platypus.v2.Socks5CtlRequest.Action
	(*TunnelPullRequest)(nil),    // 1: platypus.v2.TunnelPullRequest
	(*TunnelPullResponse)(nil),   // 2: platypus.v2.TunnelPullResponse
	(*TunnelPushRequest)(nil),    // 3: platypus.v2.TunnelPushRequest
	(*TunnelPushResponse)(nil),   // 4: platypus.v2.TunnelPushResponse
	(*Socks5CtlRequest)(nil),     // 5: platypus.v2.Socks5CtlRequest
	(*Socks5CtlResponse)(nil),    // 6: platypus.v2.Socks5CtlResponse
}
var file_tunnel_proto_depIdxs = []int32{
	0, // 0: platypus.v2.Socks5CtlRequest.action:type_name -> platypus.v2.Socks5CtlRequest.Action
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tunnel_proto_init() }
func file_tunnel_proto_init() {
	if File_tunnel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tunnel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TunnelPullRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tunnel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TunnelPullResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tunnel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TunnelPushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tunnel_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TunnelPushResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tunnel_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Socks5CtlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tunnel_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Socks5CtlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tunnel_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tunnel_proto_goTypes,
		DependencyIndexes: file_tunnel_proto_depIdxs,
		EnumInfos:         file_tunnel_proto_enumTypes,
		MessageInfos:      file_tunnel_proto_msgTypes,
	}.Build()
	File_tunnel_proto = out.File
	file_tunnel_proto_rawDesc = nil
	file_tunnel_proto_goTypes = nil
	file_tunnel_proto_depIdxs = nil
}
