// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: upgrade.proto

package v2pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpgradeProgress_Phase int32

const (
	UpgradeProgress_PHASE_UNSPECIFIED    UpgradeProgress_Phase = 0
	UpgradeProgress_PHASE_FETCH_MANIFEST UpgradeProgress_Phase = 1
	UpgradeProgress_PHASE_VERIFY_SIG     UpgradeProgress_Phase = 2
	UpgradeProgress_PHASE_DOWNLOAD       UpgradeProgress_Phase = 3
	UpgradeProgress_PHASE_VERIFY_SHA256  UpgradeProgress_Phase = 4
	UpgradeProgress_PHASE_INSTALL        UpgradeProgress_Phase = 5 // atomic rename, .bak created
	UpgradeProgress_PHASE_EXITING        UpgradeProgress_Phase = 6 // terminal: agent will os.Exit(75)
	UpgradeProgress_PHASE_FAILED         UpgradeProgress_Phase = 7 // terminal: error populated
)

// Enum value maps for UpgradeProgress_Phase.
var (
	UpgradeProgress_Phase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PHASE_FETCH_MANIFEST",
		2: "PHASE_VERIFY_SIG",
		3: "PHASE_DOWNLOAD",
		4: "PHASE_VERIFY_SHA256",
		5: "PHASE_INSTALL",
		6: "PHASE_EXITING",
		7: "PHASE_FAILED",
	}
	UpgradeProgress_Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED":    0,
		"PHASE_FETCH_MANIFEST": 1,
		"PHASE_VERIFY_SIG":     2,
		"PHASE_DOWNLOAD":       3,
		"PHASE_VERIFY_SHA256":  4,
		"PHASE_INSTALL":        5,
		"PHASE_EXITING":        6,
		"PHASE_FAILED":         7,
	}
)

func (x UpgradeProgress_Phase) Enum() *UpgradeProgress_Phase {
	p := new(UpgradeProgress_Phase)
	*p = x
	return p
}

func (x UpgradeProgress_Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpgradeProgress_Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_upgrade_proto_enumTypes[0].Descriptor()
}

func (UpgradeProgress_Phase) Type() protoreflect.EnumType {
	return &file_upgrade_proto_enumTypes[0]
}

func (x UpgradeProgress_Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpgradeProgress_Phase.Descriptor instead.
func (UpgradeProgress_Phase) EnumDescriptor() ([]byte, []int) {
	return file_upgrade_proto_rawDescGZIP(), []int{1, 0}
}

type AgentUpgradeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Target manifest version, semver. Empty string means "current
	// head of `channel`" — useful for "always be on latest stable".
	TargetVersion string `protobuf:"bytes,1,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	// Distributor channel to pull from. Empty defaults to "stable".
	Channel string `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	// Free-form actor string written to the audit log so the host's
	// upgrade history shows who triggered it (e.g. "user:alice" or
	// "system:auto-upgrade-policy"). Server-controlled, never
	// trusted from the agent side.
	Actor string `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
}

func (x *AgentUpgradeRequest) Reset() {
	*x = AgentUpgradeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_upgrade_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentUpgradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentUpgradeRequest) ProtoMessage() {}

func (x *AgentUpgradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upgrade_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentUpgradeRequest.ProtoReflect.Descriptor instead.
func (*AgentUpgradeRequest) Descriptor() ([]byte, []int) {
	return file_upgrade_proto_rawDescGZIP(), []int{0}
}

func (x *AgentUpgradeRequest) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

func (x *AgentUpgradeRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *AgentUpgradeRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

type UpgradeProgress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phase      UpgradeProgress_Phase `protobuf:"varint,1,opt,name=phase,proto3,enum=platypus.v2.UpgradeProgress_Phase" json:"phase,omitempty"`
	BytesDone  uint64                `protobuf:"varint,2,opt,name=bytes_done,json=bytesDone,proto3" json:"bytes_done,omitempty"`
	BytesTotal uint64                `protobuf:"varint,3,opt,name=bytes_total,json=bytesTotal,proto3" json:"bytes_total,omitempty"`
	// Populated only on PHASE_FAILED. Short, machine-friendly code
	// (e.g. "signature_mismatch", "sha256_mismatch", "download_eof",
	// "rename_failed") plus a free-form message.
	ErrorCode    string `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Resolved binary identity once known (after manifest fetch).
	// Empty before PHASE_FETCH_MANIFEST completes.
	ResolvedVersion string `protobuf:"bytes,6,opt,name=resolved_version,json=resolvedVersion,proto3" json:"resolved_version,omitempty"`
	ResolvedSha256  []byte `protobuf:"bytes,7,opt,name=resolved_sha256,json=resolvedSha256,proto3" json:"resolved_sha256,omitempty"` // 32 bytes
}

func (x *UpgradeProgress) Reset() {
	*x = UpgradeProgress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_upgrade_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpgradeProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeProgress) ProtoMessage() {}

func (x *UpgradeProgress) ProtoReflect() protoreflect.Message {
	mi := &file_upgrade_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeProgress.ProtoReflect.Descriptor instead.
func (*UpgradeProgress) Descriptor() ([]byte, []int) {
	return file_upgrade_proto_rawDescGZIP(), []int{1}
}

func (x *UpgradeProgress) GetPhase() UpgradeProgress_Phase {
	if x != nil {
		return x.Phase
	}
	return UpgradeProgress_PHASE_UNSPECIFIED
}

func (x *UpgradeProgress) GetBytesDone() uint64 {
	if x != nil {
		return x.BytesDone
	}
	return 0
}

func (x *UpgradeProgress) GetBytesTotal() uint64 {
	if x != nil {
		return x.BytesTotal
	}
	return 0
}

func (x *UpgradeProgress) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *UpgradeProgress) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *UpgradeProgress) GetResolvedVersion() string {
	if x != nil {
		return x.ResolvedVersion
	}
	return ""
}

func (x *UpgradeProgress) GetResolvedSha256() []byte {
	if x != nil {
		return x.ResolvedSha256
	}
	return nil
}

var File_upgrade_proto protoreflect.FileDescriptor

var file_upgrade_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x75, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x70, 0x6c, 0x61, 0x74, 0x79, 0x70, 0x75, 0x73, 0x2e, 0x76, 0x32, 0x22, 0x6c, 0x0a, 0x13,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x22, 0xd9, 0x03, 0x0a, 0x0f, 0x55,
	0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x38,
	0x0a, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e,
	0x70, 0x6c, 0x61, 0x74, 0x79, 0x70, 0x75, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x55, 0x70, 0x67, 0x72,
	0x61, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x50, 0x68, 0x61, 0x73,
	0x65, 0x52, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x5f, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x62, 0x79,
	0x74, 0x65, 0x73, 0x44, 0x6f, 0x6e, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x79, 0x74, 0x65, 0x73,
	0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x62, 0x79,
	0x74, 0x65, 0x73, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x29, 0x0a, 0x10,
	0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x6f, 0x6c,
	0x76, 0x65, 0x64, 0x5f, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x53, 0x68, 0x61, 0x32, 0x35, 0x36,
	0x22, 0xb3, 0x01, 0x0a, 0x05, 0x50, 0x68, 0x61, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x48,
	0x41, 0x53, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x48, 0x41, 0x53, 0x45, 0x5f, 0x46, 0x45, 0x54, 0x43, 0x48,
	0x5f, 0x4d, 0x41, 0x4e, 0x49, 0x46, 0x45, 0x53, 0x54, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x50,
	0x48, 0x41, 0x53, 0x45, 0x5f, 0x56, 0x45, 0x52, 0x49, 0x46, 0x59, 0x5f, 0x53, 0x49, 0x47, 0x10,
	0x02, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x48, 0x41, 0x53, 0x45, 0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x4c,
	0x4f, 0x41, 0x44, 0x10, 0x03, 0x12, 0x17, 0x0a, 0x13, 0x50, 0x48, 0x41, 0x53, 0x45, 0x5f, 0x56,
	0x45, 0x52, 0x49, 0x46, 0x59, 0x5f, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x10, 0x04, 0x12, 0x11,
	0x0a, 0x0d, 0x50, 0x48, 0x41, 0x53, 0x45, 0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4c, 0x4c, 0x10,
	0x05, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x48, 0x41, 0x53, 0x45, 0x5f, 0x45, 0x58, 0x49, 0x54, 0x49,
	0x4e, 0x47, 0x10, 0x06, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x48, 0x41, 0x53, 0x45, 0x5f, 0x46, 0x41,
	0x49, 0x4c, 0x45, 0x44, 0x10, 0x07, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x57, 0x61, 0x6e, 0x67, 0x59, 0x69, 0x68, 0x61, 0x6e, 0x67, 0x2f,
	0x50, 0x6c, 0x61, 0x74, 0x79, 0x70, 0x75, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x76, 0x32, 0x3b, 0x76, 0x32, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_upgrade_proto_rawDescOnce sync.Once
	file_upgrade_proto_rawDescData = file_upgrade_proto_rawDesc
)

func file_upgrade_proto_rawDescGZIP() []byte {
	file_upgrade_proto_rawDescOnce.Do(func() {
		file_upgrade_proto_rawDescData = protoimpl.X.CompressGZIP(file_upgrade_proto_rawDescData)
	})
	return file_upgrade_proto_rawDescData
}

var file_upgrade_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_upgrade_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_upgrade_proto_goTypes = []interface{}{
	(UpgradeProgress_Phase)(0),  // 0: platypus.v2.UpgradeProgress.Phase
	(*AgentUpgradeRequest)(nil), // 1: platypus.v2.AgentUpgradeRequest
	(*UpgradeProgress)(nil),     // 2: platypus.v2.UpgradeProgress
}
var file_upgrade_proto_depIdxs = []int32{
	0, // 0: platypus.v2.UpgradeProgress.phase:type_name -> platypus.v2.UpgradeProgress.Phase
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_upgrade_proto_init() }
func file_upgrade_proto_init() {
	if File_upgrade_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_upgrade_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentUpgradeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_upgrade_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpgradeProgress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_upgrade_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_upgrade_proto_goTypes,
		DependencyIndexes: file_upgrade_proto_depIdxs,
		EnumInfos:         file_upgrade_proto_enumTypes,
		MessageInfos:      file_upgrade_proto_msgTypes,
	}.Build()
	File_upgrade_proto = out.File
	file_upgrade_proto_rawDesc = nil
	file_upgrade_proto_goTypes = nil
	file_upgrade_proto_depIdxs = nil
}
