// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: upgrade.proto

package v2pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpgradeProgress_Phase int32

const (
	UpgradeProgress_PHASE_UNSPECIFIED    UpgradeProgress_Phase = 0
	UpgradeProgress_PHASE_FETCH_MANIFEST UpgradeProgress_Phase = 1
	UpgradeProgress_PHASE_VERIFY_SIG     UpgradeProgress_Phase = 2
	UpgradeProgress_PHASE_DOWNLOAD       UpgradeProgress_Phase = 3
	UpgradeProgress_PHASE_VERIFY_SHA256  UpgradeProgress_Phase = 4
	UpgradeProgress_PHASE_INSTALL        UpgradeProgress_Phase = 5 // atomic rename, .bak created
	UpgradeProgress_PHASE_EXITING        UpgradeProgress_Phase = 6 // terminal: agent will os.Exit(75)
	UpgradeProgress_PHASE_FAILED         UpgradeProgress_Phase = 7 // terminal: error populated
)

// Enum value maps for UpgradeProgress_Phase.
var (
	UpgradeProgress_Phase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PHASE_FETCH_MANIFEST",
		2: "PHASE_VERIFY_SIG",
		3: "PHASE_DOWNLOAD",
		4: "PHASE_VERIFY_SHA256",
		5: "PHASE_INSTALL",
		6: "PHASE_EXITING",
		7: "PHASE_FAILED",
	}
	UpgradeProgress_Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED":    0,
		"PHASE_FETCH_MANIFEST": 1,
		"PHASE_VERIFY_SIG":     2,
		"PHASE_DOWNLOAD":       3,
		"PHASE_VERIFY_SHA256":  4,
		"PHASE_INSTALL":        5,
		"PHASE_EXITING":        6,
		"PHASE_FAILED":         7,
	}
)

func (x UpgradeProgress_Phase) Enum() *UpgradeProgress_Phase {
	p := new(UpgradeProgress_Phase)
	*p = x
	return p
}

func (x UpgradeProgress_Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpgradeProgress_Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_upgrade_proto_enumTypes[0].Descriptor()
}

func (UpgradeProgress_Phase) Type() protoreflect.EnumType {
	return &file_upgrade_proto_enumTypes[0]
}

func (x UpgradeProgress_Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpgradeProgress_Phase.Descriptor instead.
func (UpgradeProgress_Phase) EnumDescriptor() ([]byte, []int) {
	return file_upgrade_proto_rawDescGZIP(), []int{1, 0}
}

type AgentUpgradeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target manifest version, semver. Empty string means "current
	// head of `channel`" — useful for "always be on latest stable".
	TargetVersion string `protobuf:"bytes,1,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	// Distributor channel to pull from. Empty defaults to "stable".
	Channel string `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	// Free-form actor string written to the audit log so the host's
	// upgrade history shows who triggered it (e.g. "user:alice" or
	// "system:auto-upgrade-policy"). Server-controlled, never
	// trusted from the agent side.
	Actor         string `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentUpgradeRequest) Reset() {
	*x = AgentUpgradeRequest{}
	mi := &file_upgrade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentUpgradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentUpgradeRequest) ProtoMessage() {}

func (x *AgentUpgradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upgrade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentUpgradeRequest.ProtoReflect.Descriptor instead.
func (*AgentUpgradeRequest) Descriptor() ([]byte, []int) {
	return file_upgrade_proto_rawDescGZIP(), []int{0}
}

func (x *AgentUpgradeRequest) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

func (x *AgentUpgradeRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *AgentUpgradeRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

type UpgradeProgress struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Phase      UpgradeProgress_Phase  `protobuf:"varint,1,opt,name=phase,proto3,enum=platypus.v2.UpgradeProgress_Phase" json:"phase,omitempty"`
	BytesDone  uint64                 `protobuf:"varint,2,opt,name=bytes_done,json=bytesDone,proto3" json:"bytes_done,omitempty"`
	BytesTotal uint64                 `protobuf:"varint,3,opt,name=bytes_total,json=bytesTotal,proto3" json:"bytes_total,omitempty"`
	// Populated only on PHASE_FAILED. Short, machine-friendly code
	// (e.g. "signature_mismatch", "sha256_mismatch", "download_eof",
	// "rename_failed") plus a free-form message.
	ErrorCode    string `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Resolved binary identity once known (after manifest fetch).
	// Empty before PHASE_FETCH_MANIFEST completes.
	ResolvedVersion string `protobuf:"bytes,6,opt,name=resolved_version,json=resolvedVersion,proto3" json:"resolved_version,omitempty"`
	ResolvedSha256  []byte `protobuf:"bytes,7,opt,name=resolved_sha256,json=resolvedSha256,proto3" json:"resolved_sha256,omitempty"` // 32 bytes
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpgradeProgress) Reset() {
	*x = UpgradeProgress{}
	mi := &file_upgrade_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeProgress) ProtoMessage() {}

func (x *UpgradeProgress) ProtoReflect() protoreflect.Message {
	mi := &file_upgrade_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeProgress.ProtoReflect.Descriptor instead.
func (*UpgradeProgress) Descriptor() ([]byte, []int) {
	return file_upgrade_proto_rawDescGZIP(), []int{1}
}

func (x *UpgradeProgress) GetPhase() UpgradeProgress_Phase {
	if x != nil {
		return x.Phase
	}
	return UpgradeProgress_PHASE_UNSPECIFIED
}

func (x *UpgradeProgress) GetBytesDone() uint64 {
	if x != nil {
		return x.BytesDone
	}
	return 0
}

func (x *UpgradeProgress) GetBytesTotal() uint64 {
	if x != nil {
		return x.BytesTotal
	}
	return 0
}

func (x *UpgradeProgress) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *UpgradeProgress) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *UpgradeProgress) GetResolvedVersion() string {
	if x != nil {
		return x.ResolvedVersion
	}
	return ""
}

func (x *UpgradeProgress) GetResolvedSha256() []byte {
	if x != nil {
		return x.ResolvedSha256
	}
	return nil
}

var File_upgrade_proto protoreflect.FileDescriptor

const file_upgrade_proto_rawDesc = "" +
	"\n" +
	"\rupgrade.proto\x12\vplatypus.v2\"l\n" +
	"\x13AgentUpgradeRequest\x12%\n" +
	"\x0etarget_version\x18\x01 \x01(\tR\rtargetVersion\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor\"\xd9\x03\n" +
	"\x0fUpgradeProgress\x128\n" +
	"\x05phase\x18\x01 \x01(\x0e2\".platypus.v2.UpgradeProgress.PhaseR\x05phase\x12\x1d\n" +
	"\n" +
	"bytes_done\x18\x02 \x01(\x04R\tbytesDone\x12\x1f\n" +
	"\vbytes_total\x18\x03 \x01(\x04R\n" +
	"bytesTotal\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12)\n" +
	"\x10resolved_version\x18\x06 \x01(\tR\x0fresolvedVersion\x12'\n" +
	"\x0fresolved_sha256\x18\a \x01(\fR\x0eresolvedSha256\"\xb3\x01\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PHASE_FETCH_MANIFEST\x10\x01\x12\x14\n" +
	"\x10PHASE_VERIFY_SIG\x10\x02\x12\x12\n" +
	"\x0ePHASE_DOWNLOAD\x10\x03\x12\x17\n" +
	"\x13PHASE_VERIFY_SHA256\x10\x04\x12\x11\n" +
	"\rPHASE_INSTALL\x10\x05\x12\x11\n" +
	"\rPHASE_EXITING\x10\x06\x12\x10\n" +
	"\fPHASE_FAILED\x10\aB2Z0github.com/WangYihang/Platypus/pkg/proto/v2;v2pbb\x06proto3"

var (
	file_upgrade_proto_rawDescOnce sync.Once
	file_upgrade_proto_rawDescData []byte
)

func file_upgrade_proto_rawDescGZIP() []byte {
	file_upgrade_proto_rawDescOnce.Do(func() {
		file_upgrade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_upgrade_proto_rawDesc), len(file_upgrade_proto_rawDesc)))
	})
	return file_upgrade_proto_rawDescData
}

var file_upgrade_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_upgrade_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_upgrade_proto_goTypes = []any{
	(UpgradeProgress_Phase)(0),  // 0: platypus.v2.UpgradeProgress.Phase
	(*AgentUpgradeRequest)(nil), // 1: platypus.v2.AgentUpgradeRequest
	(*UpgradeProgress)(nil),     // 2: platypus.v2.UpgradeProgress
}
var file_upgrade_proto_depIdxs = []int32{
	0, // 0: platypus.v2.UpgradeProgress.phase:type_name -> platypus.v2.UpgradeProgress.Phase
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_upgrade_proto_init() }
func file_upgrade_proto_init() {
	if File_upgrade_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_upgrade_proto_rawDesc), len(file_upgrade_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_upgrade_proto_goTypes,
		DependencyIndexes: file_upgrade_proto_depIdxs,
		EnumInfos:         file_upgrade_proto_enumTypes,
		MessageInfos:      file_upgrade_proto_msgTypes,
	}.Build()
	File_upgrade_proto = out.File
	file_upgrade_proto_goTypes = nil
	file_upgrade_proto_depIdxs = nil
}
