servers: 
  - host: "0.0.0.0"
    port: 13337
    # Platypus is able to use several properties as unique identifier (primirary key) of a single client.
    # All available properties are listed below:
    # `%i` IP
    # `%u` Username
    # `%m` MAC address
    # `%o` Operating System
    # `%t` Income TimeStamp
    hashFormat: "%i %u %m %o"
    encrypted: true
    disable_history: true
    public_ip: ""
    shell_path: "/bin/bash"
  - host: "0.0.0.0"
    port: 13338
    # Using TimeStamp allows us to track all connections from the same IP / Username / OS and MAC.
    hashFormat: "%i %u %m %o %t"
    disable_history: true
    public_ip: ""
    shell_path: "/bin/bash"
restful:
  # Because RESTful DO NOT support any authentication mechanism,
  # DO NOT expose the restful server into any external network.
  host: "127.0.0.1"
  port: 7331
  # `enable: true` means starting RESTful Server when Platypus starts.
  enable: true
# Termite binary distributor
distributor:
  host: "0.0.0.0"
  port: 13339
  url: "http://127.0.0.1:13339"
# Check new releases from GitHub when starting Platypus
update: true
# Open web browser to view the Web-UI on starting
openBrowser: false