package plugin

import (
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/jedisct1/go-minisign"
)

// This file implements the producer side of minisign that the upstream
// jedisct1/go-minisign library doesn't ship. We need it so:
//   - the platypus CLI can keygen and sign plugin .wasm artefacts
//     without shelling out to the minisign(1) binary
//   - integration tests can produce valid signatures inline rather
//     than checking in fixtures
//
// Wire format compatibility:
//   - Public keys produced here are byte-identical to minisign(1)'s
//     output (algo='Ed', 8-byte key id, 32-byte ed25519 pubkey, all
//     base64-encoded under a 1-line comment). They Verify cleanly with
//     minisign(1) and vice versa.
//   - Signatures use the non-prehashed Ed25519 algorithm
//     (SignatureAlgorithm = "Ed"), the same one minisign(1) writes by
//     default for short-message signing, including the trusted-comment
//     global-signature step.
//   - Secret keys use a Platypus-INTERNAL format: a single base64 blob
//     of (keyId(8) || ed25519-private(64)) under a comment line. This
//     is NOT compatible with minisign(1)'s encrypted .key format (we
//     don't implement scrypt in MVP). The CLI surfaces this difference
//     in `platypus plugin keygen --help`.

// trustedCommentPrefix is the literal string the verifier strips
// before recomputing the global-signature payload (see go-minisign
// minisign.go line 109). Keeping the constant local makes the Sign
// path symmetric with Verify.
const trustedCommentPrefix = "trusted comment: "

// SecretKey is the signer's private material. Generated by
// GenerateKeyPair; serialised via EncodeSecretKey for the CLI's
// `--key` flag.
type SecretKey struct {
	KeyID   [8]byte
	Ed25519 ed25519.PrivateKey // 64 bytes (seed || pubkey)
}

// GenerateKeyPair returns a fresh ed25519 key pair packaged in the
// minisign envelope. The 8-byte key id is random; collisions among
// random 64-bit ids are not a security concern (the ed25519 pubkey is
// the actual trust anchor) but they let operators tell two enrolled
// publishers apart at a glance.
func GenerateKeyPair() (SecretKey, minisign.PublicKey, error) {
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return SecretKey{}, minisign.PublicKey{}, fmt.Errorf("plugin: keygen: %w", err)
	}
	var keyID [8]byte
	if _, err := rand.Read(keyID[:]); err != nil {
		return SecretKey{}, minisign.PublicKey{}, fmt.Errorf("plugin: keyid rand: %w", err)
	}
	var pk minisign.PublicKey
	pk.SignatureAlgorithm = [2]byte{'E', 'd'}
	pk.KeyId = keyID
	copy(pk.PublicKey[:], pub)
	return SecretKey{KeyID: keyID, Ed25519: priv}, pk, nil
}

// Sign produces a minisign.Signature over `data`. trustedComment is the
// metadata baked into the file's third line; we prepend the
// "trusted comment: " marker if the caller didn't include it (small
// papercut to spare CLI users from the repetition).
func Sign(sk SecretKey, data []byte, trustedComment string) (minisign.Signature, error) {
	if len(sk.Ed25519) != ed25519.PrivateKeySize {
		return minisign.Signature{}, errors.New("plugin: sign: invalid private key length")
	}
	if !strings.HasPrefix(trustedComment, trustedCommentPrefix) {
		trustedComment = trustedCommentPrefix + trustedComment
	}

	sig := ed25519.Sign(sk.Ed25519, data)
	if len(sig) != ed25519.SignatureSize {
		return minisign.Signature{}, errors.New("plugin: sign: bad signature length")
	}

	// Global signature is over (signature || trustedComment-without-prefix).
	// Verify rebuilds this exact payload on the read path; staying in
	// lockstep here is what makes the produced .minisig accepted by both
	// our own VerifyWasm and the upstream minisign(1) binary.
	globalPayload := make([]byte, 0, ed25519.SignatureSize+len(trustedComment)-len(trustedCommentPrefix))
	globalPayload = append(globalPayload, sig...)
	globalPayload = append(globalPayload, []byte(trustedComment)[len(trustedCommentPrefix):]...)
	globalSig := ed25519.Sign(sk.Ed25519, globalPayload)

	out := minisign.Signature{
		UntrustedComment:   "untrusted comment: signature from platypus plugin tools",
		SignatureAlgorithm: [2]byte{'E', 'd'},
		KeyId:              sk.KeyID,
		TrustedComment:     trustedComment,
	}
	copy(out.Signature[:], sig)
	copy(out.GlobalSignature[:], globalSig)
	return out, nil
}

// DefaultTrustedComment is the comment Sign uses when the caller
// passes "". Includes the ISO 8601 timestamp + a hint at the file id
// so operators reading the .minisig file can tell at a glance when
// and what was signed.
func DefaultTrustedComment(fileLabel string) string {
	return fmt.Sprintf("%stimestamp:%d file:%s",
		trustedCommentPrefix, time.Now().Unix(), fileLabel)
}

// ---- on-disk encoders ---------------------------------------------

// EncodeSignature serialises a minisign.Signature to its file format
// (the four-line .minisig text). Reverse of go-minisign's
// DecodeSignature.
func EncodeSignature(sig minisign.Signature) string {
	header := append([]byte{}, sig.SignatureAlgorithm[:]...)
	header = append(header, sig.KeyId[:]...)
	header = append(header, sig.Signature[:]...)
	return sig.UntrustedComment + "\n" +
		base64.StdEncoding.EncodeToString(header) + "\n" +
		sig.TrustedComment + "\n" +
		base64.StdEncoding.EncodeToString(sig.GlobalSignature[:]) + "\n"
}

// EncodePublicKey serialises a minisign.PublicKey to its file format.
// The comment is filled in with the standard minisign string when
// caller passes empty.
func EncodePublicKey(pk minisign.PublicKey, comment string) string {
	if comment == "" {
		comment = "untrusted comment: minisign public key " +
			strings.ToUpper(hex.EncodeToString(pk.KeyId[:]))
	}
	body := append([]byte{}, pk.SignatureAlgorithm[:]...)
	body = append(body, pk.KeyId[:]...)
	body = append(body, pk.PublicKey[:]...)
	return comment + "\n" + base64.StdEncoding.EncodeToString(body) + "\n"
}

// EncodeSecretKey serialises a SecretKey to the Platypus-internal
// (UNencrypted) format: header line + base64(keyId(8) || priv(64)).
// Suitable for the CLI's `--key` file path; NOT compatible with
// minisign(1)'s encrypted .key files. Operators who want the upstream
// encrypted-key format should run `minisign -G` directly and import
// the resulting pubkey via `platypus plugin import-key`.
func EncodeSecretKey(sk SecretKey) string {
	body := append([]byte{}, sk.KeyID[:]...)
	body = append(body, sk.Ed25519...)
	return "untrusted comment: platypus plugin secret key " +
		strings.ToUpper(hex.EncodeToString(sk.KeyID[:])) + "\n" +
		base64.StdEncoding.EncodeToString(body) + "\n"
}

// DecodeSecretKey reverses EncodeSecretKey. Errors out on malformed
// input or wrong material length so a corrupted key file fails loudly
// rather than producing garbage signatures.
func DecodeSecretKey(s string) (SecretKey, error) {
	lines := strings.SplitN(s, "\n", 2)
	if len(lines) < 2 {
		return SecretKey{}, errors.New("plugin: decode secret key: missing body line")
	}
	raw, err := base64.StdEncoding.DecodeString(strings.TrimSpace(lines[1]))
	if err != nil {
		return SecretKey{}, fmt.Errorf("plugin: decode secret key base64: %w", err)
	}
	if len(raw) != 8+ed25519.PrivateKeySize {
		return SecretKey{}, fmt.Errorf("plugin: decode secret key: expected %d bytes, got %d",
			8+ed25519.PrivateKeySize, len(raw))
	}
	var sk SecretKey
	copy(sk.KeyID[:], raw[:8])
	sk.Ed25519 = make(ed25519.PrivateKey, ed25519.PrivateKeySize)
	copy(sk.Ed25519, raw[8:])
	return sk, nil
}
