// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/agent/v1/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TunnelMode int32

const (
	TunnelMode_TUNNEL_MODE_PULL TunnelMode = 0
	TunnelMode_TUNNEL_MODE_PUSH TunnelMode = 1
)

// Enum value maps for TunnelMode.
var (
	TunnelMode_name = map[int32]string{
		0: "TUNNEL_MODE_PULL",
		1: "TUNNEL_MODE_PUSH",
	}
	TunnelMode_value = map[string]int32{
		"TUNNEL_MODE_PULL": 0,
		"TUNNEL_MODE_PUSH": 1,
	}
)

func (x TunnelMode) Enum() *TunnelMode {
	p := new(TunnelMode)
	*p = x
	return p
}

func (x TunnelMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (TunnelMode) Type() protoreflect.EnumType {
	return &file_proto_agent_v1_agent_proto_enumTypes[0]
}

func (x TunnelMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelMode.Descriptor instead.
func (TunnelMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

// Envelope is the top-level message for all Agent <-> Server communication.
type Envelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Version   uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                     // Protocol version (current = 1)
	RequestId string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // UUID for RPC request/response correlation
	Timestamp int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // Unix nanosecond timestamp
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_GetClientInfoRequest
	//	*Envelope_ClientInfoResponse
	//	*Envelope_DuplicateClient
	//	*Envelope_UpdateRequest
	//	*Envelope_ProcessStartRequest
	//	*Envelope_ProcessStartedResponse
	//	*Envelope_ProcessStopped
	//	*Envelope_ProcessTerminateRequest
	//	*Envelope_Stdio
	//	*Envelope_WindowSize
	//	*Envelope_ExecRequest
	//	*Envelope_ExecResponse
	//	*Envelope_ReadFileRequest
	//	*Envelope_ReadFileResponse
	//	*Envelope_WriteFileRequest
	//	*Envelope_WriteFileResponse
	//	*Envelope_FileSizeRequest
	//	*Envelope_FileSizeResponse
	//	*Envelope_TunnelCreateRequest
	//	*Envelope_TunnelCreatedResponse
	//	*Envelope_TunnelCreateFailed
	//	*Envelope_TunnelData
	//	*Envelope_TunnelCloseRequest
	//	*Envelope_TunnelClosed
	//	*Envelope_TunnelConnectRequest
	//	*Envelope_TunnelConnectedResponse
	//	*Envelope_TunnelConnectFailed
	//	*Envelope_TunnelDisconnected
	//	*Envelope_Socks5CreateRequest
	//	*Envelope_Socks5CreatedResponse
	//	*Envelope_Socks5CreateFailed
	//	*Envelope_Socks5DestroyRequest
	//	*Envelope_Socks5DestroyedResponse
	//	*Envelope_Socks5DestroyFailed
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Envelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Envelope) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetGetClientInfoRequest() *GetClientInfoRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_GetClientInfoRequest); ok {
			return x.GetClientInfoRequest
		}
	}
	return nil
}

func (x *Envelope) GetClientInfoResponse() *ClientInfoResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ClientInfoResponse); ok {
			return x.ClientInfoResponse
		}
	}
	return nil
}

func (x *Envelope) GetDuplicateClient() *DuplicateClientNotice {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_DuplicateClient); ok {
			return x.DuplicateClient
		}
	}
	return nil
}

func (x *Envelope) GetUpdateRequest() *UpdateRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_UpdateRequest); ok {
			return x.UpdateRequest
		}
	}
	return nil
}

func (x *Envelope) GetProcessStartRequest() *ProcessStartRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ProcessStartRequest); ok {
			return x.ProcessStartRequest
		}
	}
	return nil
}

func (x *Envelope) GetProcessStartedResponse() *ProcessStartedResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ProcessStartedResponse); ok {
			return x.ProcessStartedResponse
		}
	}
	return nil
}

func (x *Envelope) GetProcessStopped() *ProcessStoppedNotice {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ProcessStopped); ok {
			return x.ProcessStopped
		}
	}
	return nil
}

func (x *Envelope) GetProcessTerminateRequest() *ProcessTerminateRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ProcessTerminateRequest); ok {
			return x.ProcessTerminateRequest
		}
	}
	return nil
}

func (x *Envelope) GetStdio() *StdioData {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Stdio); ok {
			return x.Stdio
		}
	}
	return nil
}

func (x *Envelope) GetWindowSize() *WindowSizeUpdate {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_WindowSize); ok {
			return x.WindowSize
		}
	}
	return nil
}

func (x *Envelope) GetExecRequest() *ExecRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ExecRequest); ok {
			return x.ExecRequest
		}
	}
	return nil
}

func (x *Envelope) GetExecResponse() *ExecResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ExecResponse); ok {
			return x.ExecResponse
		}
	}
	return nil
}

func (x *Envelope) GetReadFileRequest() *ReadFileRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ReadFileRequest); ok {
			return x.ReadFileRequest
		}
	}
	return nil
}

func (x *Envelope) GetReadFileResponse() *ReadFileResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ReadFileResponse); ok {
			return x.ReadFileResponse
		}
	}
	return nil
}

func (x *Envelope) GetWriteFileRequest() *WriteFileRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_WriteFileRequest); ok {
			return x.WriteFileRequest
		}
	}
	return nil
}

func (x *Envelope) GetWriteFileResponse() *WriteFileResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_WriteFileResponse); ok {
			return x.WriteFileResponse
		}
	}
	return nil
}

func (x *Envelope) GetFileSizeRequest() *FileSizeRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_FileSizeRequest); ok {
			return x.FileSizeRequest
		}
	}
	return nil
}

func (x *Envelope) GetFileSizeResponse() *FileSizeResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_FileSizeResponse); ok {
			return x.FileSizeResponse
		}
	}
	return nil
}

func (x *Envelope) GetTunnelCreateRequest() *TunnelCreateRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_TunnelCreateRequest); ok {
			return x.TunnelCreateRequest
		}
	}
	return nil
}

func (x *Envelope) GetTunnelCreatedResponse() *TunnelCreatedResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_TunnelCreatedResponse); ok {
			return x.TunnelCreatedResponse
		}
	}
	return nil
}

func (x *Envelope) GetTunnelCreateFailed() *TunnelCreateFailed {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_TunnelCreateFailed); ok {
			return x.TunnelCreateFailed
		}
	}
	return nil
}

func (x *Envelope) GetTunnelData() *TunnelData {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_TunnelData); ok {
			return x.TunnelData
		}
	}
	return nil
}

func (x *Envelope) GetTunnelCloseRequest() *TunnelCloseRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_TunnelCloseRequest); ok {
			return x.TunnelCloseRequest
		}
	}
	return nil
}

func (x *Envelope) GetTunnelClosed() *TunnelClosedNotice {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_TunnelClosed); ok {
			return x.TunnelClosed
		}
	}
	return nil
}

func (x *Envelope) GetTunnelConnectRequest() *TunnelConnectRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_TunnelConnectRequest); ok {
			return x.TunnelConnectRequest
		}
	}
	return nil
}

func (x *Envelope) GetTunnelConnectedResponse() *TunnelConnectedResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_TunnelConnectedResponse); ok {
			return x.TunnelConnectedResponse
		}
	}
	return nil
}

func (x *Envelope) GetTunnelConnectFailed() *TunnelConnectFailed {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_TunnelConnectFailed); ok {
			return x.TunnelConnectFailed
		}
	}
	return nil
}

func (x *Envelope) GetTunnelDisconnected() *TunnelDisconnectedNotice {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_TunnelDisconnected); ok {
			return x.TunnelDisconnected
		}
	}
	return nil
}

func (x *Envelope) GetSocks5CreateRequest() *Socks5CreateRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Socks5CreateRequest); ok {
			return x.Socks5CreateRequest
		}
	}
	return nil
}

func (x *Envelope) GetSocks5CreatedResponse() *Socks5CreatedResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Socks5CreatedResponse); ok {
			return x.Socks5CreatedResponse
		}
	}
	return nil
}

func (x *Envelope) GetSocks5CreateFailed() *Socks5CreateFailed {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Socks5CreateFailed); ok {
			return x.Socks5CreateFailed
		}
	}
	return nil
}

func (x *Envelope) GetSocks5DestroyRequest() *Socks5DestroyRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Socks5DestroyRequest); ok {
			return x.Socks5DestroyRequest
		}
	}
	return nil
}

func (x *Envelope) GetSocks5DestroyedResponse() *Socks5DestroyedResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Socks5DestroyedResponse); ok {
			return x.Socks5DestroyedResponse
		}
	}
	return nil
}

func (x *Envelope) GetSocks5DestroyFailed() *Socks5DestroyFailed {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Socks5DestroyFailed); ok {
			return x.Socks5DestroyFailed
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_GetClientInfoRequest struct {
	// Connection lifecycle
	GetClientInfoRequest *GetClientInfoRequest `protobuf:"bytes,10,opt,name=get_client_info_request,json=getClientInfoRequest,proto3,oneof"`
}

type Envelope_ClientInfoResponse struct {
	ClientInfoResponse *ClientInfoResponse `protobuf:"bytes,11,opt,name=client_info_response,json=clientInfoResponse,proto3,oneof"`
}

type Envelope_DuplicateClient struct {
	DuplicateClient *DuplicateClientNotice `protobuf:"bytes,12,opt,name=duplicate_client,json=duplicateClient,proto3,oneof"`
}

type Envelope_UpdateRequest struct {
	UpdateRequest *UpdateRequest `protobuf:"bytes,13,opt,name=update_request,json=updateRequest,proto3,oneof"`
}

type Envelope_ProcessStartRequest struct {
	// Process management
	ProcessStartRequest *ProcessStartRequest `protobuf:"bytes,20,opt,name=process_start_request,json=processStartRequest,proto3,oneof"`
}

type Envelope_ProcessStartedResponse struct {
	ProcessStartedResponse *ProcessStartedResponse `protobuf:"bytes,21,opt,name=process_started_response,json=processStartedResponse,proto3,oneof"`
}

type Envelope_ProcessStopped struct {
	ProcessStopped *ProcessStoppedNotice `protobuf:"bytes,22,opt,name=process_stopped,json=processStopped,proto3,oneof"`
}

type Envelope_ProcessTerminateRequest struct {
	ProcessTerminateRequest *ProcessTerminateRequest `protobuf:"bytes,23,opt,name=process_terminate_request,json=processTerminateRequest,proto3,oneof"`
}

type Envelope_Stdio struct {
	Stdio *StdioData `protobuf:"bytes,24,opt,name=stdio,proto3,oneof"`
}

type Envelope_WindowSize struct {
	WindowSize *WindowSizeUpdate `protobuf:"bytes,25,opt,name=window_size,json=windowSize,proto3,oneof"`
}

type Envelope_ExecRequest struct {
	// RPC: command execution
	ExecRequest *ExecRequest `protobuf:"bytes,30,opt,name=exec_request,json=execRequest,proto3,oneof"`
}

type Envelope_ExecResponse struct {
	ExecResponse *ExecResponse `protobuf:"bytes,31,opt,name=exec_response,json=execResponse,proto3,oneof"`
}

type Envelope_ReadFileRequest struct {
	// RPC: file operations
	ReadFileRequest *ReadFileRequest `protobuf:"bytes,32,opt,name=read_file_request,json=readFileRequest,proto3,oneof"`
}

type Envelope_ReadFileResponse struct {
	ReadFileResponse *ReadFileResponse `protobuf:"bytes,33,opt,name=read_file_response,json=readFileResponse,proto3,oneof"`
}

type Envelope_WriteFileRequest struct {
	WriteFileRequest *WriteFileRequest `protobuf:"bytes,34,opt,name=write_file_request,json=writeFileRequest,proto3,oneof"`
}

type Envelope_WriteFileResponse struct {
	WriteFileResponse *WriteFileResponse `protobuf:"bytes,35,opt,name=write_file_response,json=writeFileResponse,proto3,oneof"`
}

type Envelope_FileSizeRequest struct {
	FileSizeRequest *FileSizeRequest `protobuf:"bytes,36,opt,name=file_size_request,json=fileSizeRequest,proto3,oneof"`
}

type Envelope_FileSizeResponse struct {
	FileSizeResponse *FileSizeResponse `protobuf:"bytes,37,opt,name=file_size_response,json=fileSizeResponse,proto3,oneof"`
}

type Envelope_TunnelCreateRequest struct {
	// Tunneling
	TunnelCreateRequest *TunnelCreateRequest `protobuf:"bytes,40,opt,name=tunnel_create_request,json=tunnelCreateRequest,proto3,oneof"`
}

type Envelope_TunnelCreatedResponse struct {
	TunnelCreatedResponse *TunnelCreatedResponse `protobuf:"bytes,41,opt,name=tunnel_created_response,json=tunnelCreatedResponse,proto3,oneof"`
}

type Envelope_TunnelCreateFailed struct {
	TunnelCreateFailed *TunnelCreateFailed `protobuf:"bytes,42,opt,name=tunnel_create_failed,json=tunnelCreateFailed,proto3,oneof"`
}

type Envelope_TunnelData struct {
	TunnelData *TunnelData `protobuf:"bytes,43,opt,name=tunnel_data,json=tunnelData,proto3,oneof"`
}

type Envelope_TunnelCloseRequest struct {
	TunnelCloseRequest *TunnelCloseRequest `protobuf:"bytes,44,opt,name=tunnel_close_request,json=tunnelCloseRequest,proto3,oneof"`
}

type Envelope_TunnelClosed struct {
	TunnelClosed *TunnelClosedNotice `protobuf:"bytes,45,opt,name=tunnel_closed,json=tunnelClosed,proto3,oneof"`
}

type Envelope_TunnelConnectRequest struct {
	TunnelConnectRequest *TunnelConnectRequest `protobuf:"bytes,46,opt,name=tunnel_connect_request,json=tunnelConnectRequest,proto3,oneof"`
}

type Envelope_TunnelConnectedResponse struct {
	TunnelConnectedResponse *TunnelConnectedResponse `protobuf:"bytes,47,opt,name=tunnel_connected_response,json=tunnelConnectedResponse,proto3,oneof"`
}

type Envelope_TunnelConnectFailed struct {
	TunnelConnectFailed *TunnelConnectFailed `protobuf:"bytes,48,opt,name=tunnel_connect_failed,json=tunnelConnectFailed,proto3,oneof"`
}

type Envelope_TunnelDisconnected struct {
	TunnelDisconnected *TunnelDisconnectedNotice `protobuf:"bytes,49,opt,name=tunnel_disconnected,json=tunnelDisconnected,proto3,oneof"`
}

type Envelope_Socks5CreateRequest struct {
	// SOCKS5
	Socks5CreateRequest *Socks5CreateRequest `protobuf:"bytes,50,opt,name=socks5_create_request,json=socks5CreateRequest,proto3,oneof"`
}

type Envelope_Socks5CreatedResponse struct {
	Socks5CreatedResponse *Socks5CreatedResponse `protobuf:"bytes,51,opt,name=socks5_created_response,json=socks5CreatedResponse,proto3,oneof"`
}

type Envelope_Socks5CreateFailed struct {
	Socks5CreateFailed *Socks5CreateFailed `protobuf:"bytes,52,opt,name=socks5_create_failed,json=socks5CreateFailed,proto3,oneof"`
}

type Envelope_Socks5DestroyRequest struct {
	Socks5DestroyRequest *Socks5DestroyRequest `protobuf:"bytes,53,opt,name=socks5_destroy_request,json=socks5DestroyRequest,proto3,oneof"`
}

type Envelope_Socks5DestroyedResponse struct {
	Socks5DestroyedResponse *Socks5DestroyedResponse `protobuf:"bytes,54,opt,name=socks5_destroyed_response,json=socks5DestroyedResponse,proto3,oneof"`
}

type Envelope_Socks5DestroyFailed struct {
	Socks5DestroyFailed *Socks5DestroyFailed `protobuf:"bytes,55,opt,name=socks5_destroy_failed,json=socks5DestroyFailed,proto3,oneof"`
}

func (*Envelope_GetClientInfoRequest) isEnvelope_Payload() {}

func (*Envelope_ClientInfoResponse) isEnvelope_Payload() {}

func (*Envelope_DuplicateClient) isEnvelope_Payload() {}

func (*Envelope_UpdateRequest) isEnvelope_Payload() {}

func (*Envelope_ProcessStartRequest) isEnvelope_Payload() {}

func (*Envelope_ProcessStartedResponse) isEnvelope_Payload() {}

func (*Envelope_ProcessStopped) isEnvelope_Payload() {}

func (*Envelope_ProcessTerminateRequest) isEnvelope_Payload() {}

func (*Envelope_Stdio) isEnvelope_Payload() {}

func (*Envelope_WindowSize) isEnvelope_Payload() {}

func (*Envelope_ExecRequest) isEnvelope_Payload() {}

func (*Envelope_ExecResponse) isEnvelope_Payload() {}

func (*Envelope_ReadFileRequest) isEnvelope_Payload() {}

func (*Envelope_ReadFileResponse) isEnvelope_Payload() {}

func (*Envelope_WriteFileRequest) isEnvelope_Payload() {}

func (*Envelope_WriteFileResponse) isEnvelope_Payload() {}

func (*Envelope_FileSizeRequest) isEnvelope_Payload() {}

func (*Envelope_FileSizeResponse) isEnvelope_Payload() {}

func (*Envelope_TunnelCreateRequest) isEnvelope_Payload() {}

func (*Envelope_TunnelCreatedResponse) isEnvelope_Payload() {}

func (*Envelope_TunnelCreateFailed) isEnvelope_Payload() {}

func (*Envelope_TunnelData) isEnvelope_Payload() {}

func (*Envelope_TunnelCloseRequest) isEnvelope_Payload() {}

func (*Envelope_TunnelClosed) isEnvelope_Payload() {}

func (*Envelope_TunnelConnectRequest) isEnvelope_Payload() {}

func (*Envelope_TunnelConnectedResponse) isEnvelope_Payload() {}

func (*Envelope_TunnelConnectFailed) isEnvelope_Payload() {}

func (*Envelope_TunnelDisconnected) isEnvelope_Payload() {}

func (*Envelope_Socks5CreateRequest) isEnvelope_Payload() {}

func (*Envelope_Socks5CreatedResponse) isEnvelope_Payload() {}

func (*Envelope_Socks5CreateFailed) isEnvelope_Payload() {}

func (*Envelope_Socks5DestroyRequest) isEnvelope_Payload() {}

func (*Envelope_Socks5DestroyedResponse) isEnvelope_Payload() {}

func (*Envelope_Socks5DestroyFailed) isEnvelope_Payload() {}

type GetClientInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientInfoRequest) Reset() {
	*x = GetClientInfoRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientInfoRequest) ProtoMessage() {}

func (x *GetClientInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientInfoRequest.ProtoReflect.Descriptor instead.
func (*GetClientInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

type ClientInfoResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Version            string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Os                 string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch               string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	User               string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Hostname           string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	NetworkInterfaces  map[string]string      `protobuf:"bytes,6,rep,name=network_interfaces,json=networkInterfaces,proto3" json:"network_interfaces,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AvailableLanguages []string               `protobuf:"bytes,7,rep,name=available_languages,json=availableLanguages,proto3" json:"available_languages,omitempty"` // e.g. ["python2", "python3", "perl"]
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClientInfoResponse) Reset() {
	*x = ClientInfoResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfoResponse) ProtoMessage() {}

func (x *ClientInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfoResponse.ProtoReflect.Descriptor instead.
func (*ClientInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ClientInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ClientInfoResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *ClientInfoResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *ClientInfoResponse) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ClientInfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ClientInfoResponse) GetNetworkInterfaces() map[string]string {
	if x != nil {
		return x.NetworkInterfaces
	}
	return nil
}

func (x *ClientInfoResponse) GetAvailableLanguages() []string {
	if x != nil {
		return x.AvailableLanguages
	}
	return nil
}

type DuplicateClientNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DuplicateClientNotice) Reset() {
	*x = DuplicateClientNotice{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DuplicateClientNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DuplicateClientNotice) ProtoMessage() {}

func (x *DuplicateClientNotice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DuplicateClientNotice.ProtoReflect.Descriptor instead.
func (*DuplicateClientNotice) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

type UpdateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DistributorUrl string                 `protobuf:"bytes,1,opt,name=distributor_url,json=distributorUrl,proto3" json:"distributor_url,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRequest) GetDistributorUrl() string {
	if x != nil {
		return x.DistributorUrl
	}
	return ""
}

func (x *UpdateRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ProcessStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	WindowColumns int32                  `protobuf:"varint,3,opt,name=window_columns,json=windowColumns,proto3" json:"window_columns,omitempty"`
	WindowRows    int32                  `protobuf:"varint,4,opt,name=window_rows,json=windowRows,proto3" json:"window_rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessStartRequest) Reset() {
	*x = ProcessStartRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessStartRequest) ProtoMessage() {}

func (x *ProcessStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessStartRequest.ProtoReflect.Descriptor instead.
func (*ProcessStartRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessStartRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ProcessStartRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProcessStartRequest) GetWindowColumns() int32 {
	if x != nil {
		return x.WindowColumns
	}
	return 0
}

func (x *ProcessStartRequest) GetWindowRows() int32 {
	if x != nil {
		return x.WindowRows
	}
	return 0
}

type ProcessStartedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessStartedResponse) Reset() {
	*x = ProcessStartedResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessStartedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessStartedResponse) ProtoMessage() {}

func (x *ProcessStartedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessStartedResponse.ProtoReflect.Descriptor instead.
func (*ProcessStartedResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessStartedResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ProcessStartedResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type ProcessStoppedNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessStoppedNotice) Reset() {
	*x = ProcessStoppedNotice{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessStoppedNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessStoppedNotice) ProtoMessage() {}

func (x *ProcessStoppedNotice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessStoppedNotice.ProtoReflect.Descriptor instead.
func (*ProcessStoppedNotice) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ProcessStoppedNotice) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ProcessStoppedNotice) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type ProcessTerminateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessTerminateRequest) Reset() {
	*x = ProcessTerminateRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessTerminateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessTerminateRequest) ProtoMessage() {}

func (x *ProcessTerminateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessTerminateRequest.ProtoReflect.Descriptor instead.
func (*ProcessTerminateRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessTerminateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type StdioData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StdioData) Reset() {
	*x = StdioData{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdioData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdioData) ProtoMessage() {}

func (x *StdioData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdioData.ProtoReflect.Descriptor instead.
func (*StdioData) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *StdioData) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StdioData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WindowSizeUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Columns       int32                  `protobuf:"varint,2,opt,name=columns,proto3" json:"columns,omitempty"`
	Rows          int32                  `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowSizeUpdate) Reset() {
	*x = WindowSizeUpdate{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowSizeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowSizeUpdate) ProtoMessage() {}

func (x *WindowSizeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowSizeUpdate.ProtoReflect.Descriptor instead.
func (*WindowSizeUpdate) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *WindowSizeUpdate) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WindowSizeUpdate) GetColumns() int32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

func (x *WindowSizeUpdate) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []byte                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ExecResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // 0 = from start
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`     // 0 = read all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadFileRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadFileRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ReadFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Append        bool                   `protobuf:"varint,3,opt,name=append,proto3" json:"append,omitempty"` // true = append, false = overwrite
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WriteFileRequest) GetAppend() bool {
	if x != nil {
		return x.Append
	}
	return false
}

type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  int64                  `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *WriteFileResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *WriteFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FileSizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSizeRequest) Reset() {
	*x = FileSizeRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSizeRequest) ProtoMessage() {}

func (x *FileSizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSizeRequest.ProtoReflect.Descriptor instead.
func (*FileSizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *FileSizeRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileSizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSizeResponse) Reset() {
	*x = FileSizeResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSizeResponse) ProtoMessage() {}

func (x *FileSizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSizeResponse.ProtoReflect.Descriptor instead.
func (*FileSizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *FileSizeResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileSizeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TunnelCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Mode          TunnelMode             `protobuf:"varint,2,opt,name=mode,proto3,enum=platypus.agent.v1.TunnelMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelCreateRequest) Reset() {
	*x = TunnelCreateRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelCreateRequest) ProtoMessage() {}

func (x *TunnelCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelCreateRequest.ProtoReflect.Descriptor instead.
func (*TunnelCreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{19}
}

func (x *TunnelCreateRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TunnelCreateRequest) GetMode() TunnelMode {
	if x != nil {
		return x.Mode
	}
	return TunnelMode_TUNNEL_MODE_PULL
}

type TunnelCreatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelCreatedResponse) Reset() {
	*x = TunnelCreatedResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelCreatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelCreatedResponse) ProtoMessage() {}

func (x *TunnelCreatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelCreatedResponse.ProtoReflect.Descriptor instead.
func (*TunnelCreatedResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{20}
}

func (x *TunnelCreatedResponse) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *TunnelCreatedResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type TunnelCreateFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelCreateFailed) Reset() {
	*x = TunnelCreateFailed{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelCreateFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelCreateFailed) ProtoMessage() {}

func (x *TunnelCreateFailed) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelCreateFailed.ProtoReflect.Descriptor instead.
func (*TunnelCreateFailed) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{21}
}

func (x *TunnelCreateFailed) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TunnelCreateFailed) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TunnelConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelConnectRequest) Reset() {
	*x = TunnelConnectRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelConnectRequest) ProtoMessage() {}

func (x *TunnelConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelConnectRequest.ProtoReflect.Descriptor instead.
func (*TunnelConnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{22}
}

func (x *TunnelConnectRequest) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *TunnelConnectRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type TunnelConnectedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelConnectedResponse) Reset() {
	*x = TunnelConnectedResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelConnectedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelConnectedResponse) ProtoMessage() {}

func (x *TunnelConnectedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelConnectedResponse.ProtoReflect.Descriptor instead.
func (*TunnelConnectedResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{23}
}

func (x *TunnelConnectedResponse) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

type TunnelConnectFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelConnectFailed) Reset() {
	*x = TunnelConnectFailed{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelConnectFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelConnectFailed) ProtoMessage() {}

func (x *TunnelConnectFailed) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelConnectFailed.ProtoReflect.Descriptor instead.
func (*TunnelConnectFailed) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{24}
}

func (x *TunnelConnectFailed) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *TunnelConnectFailed) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TunnelData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelData) Reset() {
	*x = TunnelData{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelData) ProtoMessage() {}

func (x *TunnelData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelData.ProtoReflect.Descriptor instead.
func (*TunnelData) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{25}
}

func (x *TunnelData) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *TunnelData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TunnelCloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelCloseRequest) Reset() {
	*x = TunnelCloseRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelCloseRequest) ProtoMessage() {}

func (x *TunnelCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelCloseRequest.ProtoReflect.Descriptor instead.
func (*TunnelCloseRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{26}
}

func (x *TunnelCloseRequest) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

type TunnelClosedNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelClosedNotice) Reset() {
	*x = TunnelClosedNotice{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelClosedNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelClosedNotice) ProtoMessage() {}

func (x *TunnelClosedNotice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelClosedNotice.ProtoReflect.Descriptor instead.
func (*TunnelClosedNotice) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{27}
}

func (x *TunnelClosedNotice) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

type TunnelDisconnectedNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelDisconnectedNotice) Reset() {
	*x = TunnelDisconnectedNotice{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelDisconnectedNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelDisconnectedNotice) ProtoMessage() {}

func (x *TunnelDisconnectedNotice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelDisconnectedNotice.ProtoReflect.Descriptor instead.
func (*TunnelDisconnectedNotice) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{28}
}

func (x *TunnelDisconnectedNotice) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *TunnelDisconnectedNotice) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Socks5CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Socks5CreateRequest) Reset() {
	*x = Socks5CreateRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Socks5CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Socks5CreateRequest) ProtoMessage() {}

func (x *Socks5CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Socks5CreateRequest.ProtoReflect.Descriptor instead.
func (*Socks5CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{29}
}

type Socks5CreatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Socks5CreatedResponse) Reset() {
	*x = Socks5CreatedResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Socks5CreatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Socks5CreatedResponse) ProtoMessage() {}

func (x *Socks5CreatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Socks5CreatedResponse.ProtoReflect.Descriptor instead.
func (*Socks5CreatedResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{30}
}

func (x *Socks5CreatedResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Socks5CreateFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Socks5CreateFailed) Reset() {
	*x = Socks5CreateFailed{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Socks5CreateFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Socks5CreateFailed) ProtoMessage() {}

func (x *Socks5CreateFailed) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Socks5CreateFailed.ProtoReflect.Descriptor instead.
func (*Socks5CreateFailed) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{31}
}

func (x *Socks5CreateFailed) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Socks5DestroyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Socks5DestroyRequest) Reset() {
	*x = Socks5DestroyRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Socks5DestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Socks5DestroyRequest) ProtoMessage() {}

func (x *Socks5DestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Socks5DestroyRequest.ProtoReflect.Descriptor instead.
func (*Socks5DestroyRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{32}
}

type Socks5DestroyedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Socks5DestroyedResponse) Reset() {
	*x = Socks5DestroyedResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Socks5DestroyedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Socks5DestroyedResponse) ProtoMessage() {}

func (x *Socks5DestroyedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Socks5DestroyedResponse.ProtoReflect.Descriptor instead.
func (*Socks5DestroyedResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{33}
}

type Socks5DestroyFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Socks5DestroyFailed) Reset() {
	*x = Socks5DestroyFailed{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Socks5DestroyFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Socks5DestroyFailed) ProtoMessage() {}

func (x *Socks5DestroyFailed) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Socks5DestroyFailed.ProtoReflect.Descriptor instead.
func (*Socks5DestroyFailed) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{34}
}

func (x *Socks5DestroyFailed) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_agent_v1_agent_proto protoreflect.FileDescriptor

const file_proto_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/agent/v1/agent.proto\x12\x11platypus.agent.v1\"\xab\x18\n" +
	"\bEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12`\n" +
	"\x17get_client_info_request\x18\n" +
	" \x01(\v2'.platypus.agent.v1.GetClientInfoRequestH\x00R\x14getClientInfoRequest\x12Y\n" +
	"\x14client_info_response\x18\v \x01(\v2%.platypus.agent.v1.ClientInfoResponseH\x00R\x12clientInfoResponse\x12U\n" +
	"\x10duplicate_client\x18\f \x01(\v2(.platypus.agent.v1.DuplicateClientNoticeH\x00R\x0fduplicateClient\x12I\n" +
	"\x0eupdate_request\x18\r \x01(\v2 .platypus.agent.v1.UpdateRequestH\x00R\rupdateRequest\x12\\\n" +
	"\x15process_start_request\x18\x14 \x01(\v2&.platypus.agent.v1.ProcessStartRequestH\x00R\x13processStartRequest\x12e\n" +
	"\x18process_started_response\x18\x15 \x01(\v2).platypus.agent.v1.ProcessStartedResponseH\x00R\x16processStartedResponse\x12R\n" +
	"\x0fprocess_stopped\x18\x16 \x01(\v2'.platypus.agent.v1.ProcessStoppedNoticeH\x00R\x0eprocessStopped\x12h\n" +
	"\x19process_terminate_request\x18\x17 \x01(\v2*.platypus.agent.v1.ProcessTerminateRequestH\x00R\x17processTerminateRequest\x124\n" +
	"\x05stdio\x18\x18 \x01(\v2\x1c.platypus.agent.v1.StdioDataH\x00R\x05stdio\x12F\n" +
	"\vwindow_size\x18\x19 \x01(\v2#.platypus.agent.v1.WindowSizeUpdateH\x00R\n" +
	"windowSize\x12C\n" +
	"\fexec_request\x18\x1e \x01(\v2\x1e.platypus.agent.v1.ExecRequestH\x00R\vexecRequest\x12F\n" +
	"\rexec_response\x18\x1f \x01(\v2\x1f.platypus.agent.v1.ExecResponseH\x00R\fexecResponse\x12P\n" +
	"\x11read_file_request\x18  \x01(\v2\".platypus.agent.v1.ReadFileRequestH\x00R\x0freadFileRequest\x12S\n" +
	"\x12read_file_response\x18! \x01(\v2#.platypus.agent.v1.ReadFileResponseH\x00R\x10readFileResponse\x12S\n" +
	"\x12write_file_request\x18\" \x01(\v2#.platypus.agent.v1.WriteFileRequestH\x00R\x10writeFileRequest\x12V\n" +
	"\x13write_file_response\x18# \x01(\v2$.platypus.agent.v1.WriteFileResponseH\x00R\x11writeFileResponse\x12P\n" +
	"\x11file_size_request\x18$ \x01(\v2\".platypus.agent.v1.FileSizeRequestH\x00R\x0ffileSizeRequest\x12S\n" +
	"\x12file_size_response\x18% \x01(\v2#.platypus.agent.v1.FileSizeResponseH\x00R\x10fileSizeResponse\x12\\\n" +
	"\x15tunnel_create_request\x18( \x01(\v2&.platypus.agent.v1.TunnelCreateRequestH\x00R\x13tunnelCreateRequest\x12b\n" +
	"\x17tunnel_created_response\x18) \x01(\v2(.platypus.agent.v1.TunnelCreatedResponseH\x00R\x15tunnelCreatedResponse\x12Y\n" +
	"\x14tunnel_create_failed\x18* \x01(\v2%.platypus.agent.v1.TunnelCreateFailedH\x00R\x12tunnelCreateFailed\x12@\n" +
	"\vtunnel_data\x18+ \x01(\v2\x1d.platypus.agent.v1.TunnelDataH\x00R\n" +
	"tunnelData\x12Y\n" +
	"\x14tunnel_close_request\x18, \x01(\v2%.platypus.agent.v1.TunnelCloseRequestH\x00R\x12tunnelCloseRequest\x12L\n" +
	"\rtunnel_closed\x18- \x01(\v2%.platypus.agent.v1.TunnelClosedNoticeH\x00R\ftunnelClosed\x12_\n" +
	"\x16tunnel_connect_request\x18. \x01(\v2'.platypus.agent.v1.TunnelConnectRequestH\x00R\x14tunnelConnectRequest\x12h\n" +
	"\x19tunnel_connected_response\x18/ \x01(\v2*.platypus.agent.v1.TunnelConnectedResponseH\x00R\x17tunnelConnectedResponse\x12\\\n" +
	"\x15tunnel_connect_failed\x180 \x01(\v2&.platypus.agent.v1.TunnelConnectFailedH\x00R\x13tunnelConnectFailed\x12^\n" +
	"\x13tunnel_disconnected\x181 \x01(\v2+.platypus.agent.v1.TunnelDisconnectedNoticeH\x00R\x12tunnelDisconnected\x12\\\n" +
	"\x15socks5_create_request\x182 \x01(\v2&.platypus.agent.v1.Socks5CreateRequestH\x00R\x13socks5CreateRequest\x12b\n" +
	"\x17socks5_created_response\x183 \x01(\v2(.platypus.agent.v1.Socks5CreatedResponseH\x00R\x15socks5CreatedResponse\x12Y\n" +
	"\x14socks5_create_failed\x184 \x01(\v2%.platypus.agent.v1.Socks5CreateFailedH\x00R\x12socks5CreateFailed\x12_\n" +
	"\x16socks5_destroy_request\x185 \x01(\v2'.platypus.agent.v1.Socks5DestroyRequestH\x00R\x14socks5DestroyRequest\x12h\n" +
	"\x19socks5_destroyed_response\x186 \x01(\v2*.platypus.agent.v1.Socks5DestroyedResponseH\x00R\x17socks5DestroyedResponse\x12\\\n" +
	"\x15socks5_destroy_failed\x187 \x01(\v2&.platypus.agent.v1.Socks5DestroyFailedH\x00R\x13socks5DestroyFailedB\t\n" +
	"\apayload\"\x16\n" +
	"\x14GetClientInfoRequest\"\xe6\x02\n" +
	"\x12ClientInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\x12k\n" +
	"\x12network_interfaces\x18\x06 \x03(\v2<.platypus.agent.v1.ClientInfoResponse.NetworkInterfacesEntryR\x11networkInterfaces\x12/\n" +
	"\x13available_languages\x18\a \x03(\tR\x12availableLanguages\x1aD\n" +
	"\x16NetworkInterfacesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x17\n" +
	"\x15DuplicateClientNotice\"R\n" +
	"\rUpdateRequest\x12'\n" +
	"\x0fdistributor_url\x18\x01 \x01(\tR\x0edistributorUrl\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x83\x01\n" +
	"\x13ProcessStartRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12%\n" +
	"\x0ewindow_columns\x18\x03 \x01(\x05R\rwindowColumns\x12\x1f\n" +
	"\vwindow_rows\x18\x04 \x01(\x05R\n" +
	"windowRows\"<\n" +
	"\x16ProcessStartedResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\"E\n" +
	"\x14ProcessStoppedNotice\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\"+\n" +
	"\x17ProcessTerminateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"1\n" +
	"\tStdioData\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"R\n" +
	"\x10WindowSizeUpdate\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\acolumns\x18\x02 \x01(\x05R\acolumns\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\x05R\x04rows\"'\n" +
	"\vExecRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"Y\n" +
	"\fExecResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\fR\x06output\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"Q\n" +
	"\x0fReadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"<\n" +
	"\x10ReadFileResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"R\n" +
	"\x10WriteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x16\n" +
	"\x06append\x18\x03 \x01(\bR\x06append\"N\n" +
	"\x11WriteFileResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"%\n" +
	"\x0fFileSizeRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"<\n" +
	"\x10FileSizeResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"b\n" +
	"\x13TunnelCreateRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x121\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x1d.platypus.agent.v1.TunnelModeR\x04mode\"N\n" +
	"\x15TunnelCreatedResponse\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"F\n" +
	"\x12TunnelCreateFailed\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"M\n" +
	"\x14TunnelConnectRequest\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"6\n" +
	"\x17TunnelConnectedResponse\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\"J\n" +
	"\x13TunnelConnectFailed\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"=\n" +
	"\n" +
	"TunnelData\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"1\n" +
	"\x12TunnelCloseRequest\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\"1\n" +
	"\x12TunnelClosedNotice\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\"O\n" +
	"\x18TunnelDisconnectedNotice\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x15\n" +
	"\x13Socks5CreateRequest\"+\n" +
	"\x15Socks5CreatedResponse\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\",\n" +
	"\x12Socks5CreateFailed\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x16\n" +
	"\x14Socks5DestroyRequest\"\x19\n" +
	"\x17Socks5DestroyedResponse\"-\n" +
	"\x13Socks5DestroyFailed\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason*8\n" +
	"\n" +
	"TunnelMode\x12\x14\n" +
	"\x10TUNNEL_MODE_PULL\x10\x00\x12\x14\n" +
	"\x10TUNNEL_MODE_PUSH\x10\x01B;Z9github.com/WangYihang/Platypus/pkg/proto/agent/v1;agentpbb\x06proto3"

var (
	file_proto_agent_v1_agent_proto_rawDescOnce sync.Once
	file_proto_agent_v1_agent_proto_rawDescData []byte
)

func file_proto_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_v1_agent_proto_rawDesc), len(file_proto_agent_v1_agent_proto_rawDesc)))
	})
	return file_proto_agent_v1_agent_proto_rawDescData
}

var file_proto_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_proto_agent_v1_agent_proto_goTypes = []any{
	(TunnelMode)(0),                  // 0: platypus.agent.v1.TunnelMode
	(*Envelope)(nil),                 // 1: platypus.agent.v1.Envelope
	(*GetClientInfoRequest)(nil),     // 2: platypus.agent.v1.GetClientInfoRequest
	(*ClientInfoResponse)(nil),       // 3: platypus.agent.v1.ClientInfoResponse
	(*DuplicateClientNotice)(nil),    // 4: platypus.agent.v1.DuplicateClientNotice
	(*UpdateRequest)(nil),            // 5: platypus.agent.v1.UpdateRequest
	(*ProcessStartRequest)(nil),      // 6: platypus.agent.v1.ProcessStartRequest
	(*ProcessStartedResponse)(nil),   // 7: platypus.agent.v1.ProcessStartedResponse
	(*ProcessStoppedNotice)(nil),     // 8: platypus.agent.v1.ProcessStoppedNotice
	(*ProcessTerminateRequest)(nil),  // 9: platypus.agent.v1.ProcessTerminateRequest
	(*StdioData)(nil),                // 10: platypus.agent.v1.StdioData
	(*WindowSizeUpdate)(nil),         // 11: platypus.agent.v1.WindowSizeUpdate
	(*ExecRequest)(nil),              // 12: platypus.agent.v1.ExecRequest
	(*ExecResponse)(nil),             // 13: platypus.agent.v1.ExecResponse
	(*ReadFileRequest)(nil),          // 14: platypus.agent.v1.ReadFileRequest
	(*ReadFileResponse)(nil),         // 15: platypus.agent.v1.ReadFileResponse
	(*WriteFileRequest)(nil),         // 16: platypus.agent.v1.WriteFileRequest
	(*WriteFileResponse)(nil),        // 17: platypus.agent.v1.WriteFileResponse
	(*FileSizeRequest)(nil),          // 18: platypus.agent.v1.FileSizeRequest
	(*FileSizeResponse)(nil),         // 19: platypus.agent.v1.FileSizeResponse
	(*TunnelCreateRequest)(nil),      // 20: platypus.agent.v1.TunnelCreateRequest
	(*TunnelCreatedResponse)(nil),    // 21: platypus.agent.v1.TunnelCreatedResponse
	(*TunnelCreateFailed)(nil),       // 22: platypus.agent.v1.TunnelCreateFailed
	(*TunnelConnectRequest)(nil),     // 23: platypus.agent.v1.TunnelConnectRequest
	(*TunnelConnectedResponse)(nil),  // 24: platypus.agent.v1.TunnelConnectedResponse
	(*TunnelConnectFailed)(nil),      // 25: platypus.agent.v1.TunnelConnectFailed
	(*TunnelData)(nil),               // 26: platypus.agent.v1.TunnelData
	(*TunnelCloseRequest)(nil),       // 27: platypus.agent.v1.TunnelCloseRequest
	(*TunnelClosedNotice)(nil),       // 28: platypus.agent.v1.TunnelClosedNotice
	(*TunnelDisconnectedNotice)(nil), // 29: platypus.agent.v1.TunnelDisconnectedNotice
	(*Socks5CreateRequest)(nil),      // 30: platypus.agent.v1.Socks5CreateRequest
	(*Socks5CreatedResponse)(nil),    // 31: platypus.agent.v1.Socks5CreatedResponse
	(*Socks5CreateFailed)(nil),       // 32: platypus.agent.v1.Socks5CreateFailed
	(*Socks5DestroyRequest)(nil),     // 33: platypus.agent.v1.Socks5DestroyRequest
	(*Socks5DestroyedResponse)(nil),  // 34: platypus.agent.v1.Socks5DestroyedResponse
	(*Socks5DestroyFailed)(nil),      // 35: platypus.agent.v1.Socks5DestroyFailed
	nil,                              // 36: platypus.agent.v1.ClientInfoResponse.NetworkInterfacesEntry
}
var file_proto_agent_v1_agent_proto_depIdxs = []int32{
	2,  // 0: platypus.agent.v1.Envelope.get_client_info_request:type_name -> platypus.agent.v1.GetClientInfoRequest
	3,  // 1: platypus.agent.v1.Envelope.client_info_response:type_name -> platypus.agent.v1.ClientInfoResponse
	4,  // 2: platypus.agent.v1.Envelope.duplicate_client:type_name -> platypus.agent.v1.DuplicateClientNotice
	5,  // 3: platypus.agent.v1.Envelope.update_request:type_name -> platypus.agent.v1.UpdateRequest
	6,  // 4: platypus.agent.v1.Envelope.process_start_request:type_name -> platypus.agent.v1.ProcessStartRequest
	7,  // 5: platypus.agent.v1.Envelope.process_started_response:type_name -> platypus.agent.v1.ProcessStartedResponse
	8,  // 6: platypus.agent.v1.Envelope.process_stopped:type_name -> platypus.agent.v1.ProcessStoppedNotice
	9,  // 7: platypus.agent.v1.Envelope.process_terminate_request:type_name -> platypus.agent.v1.ProcessTerminateRequest
	10, // 8: platypus.agent.v1.Envelope.stdio:type_name -> platypus.agent.v1.StdioData
	11, // 9: platypus.agent.v1.Envelope.window_size:type_name -> platypus.agent.v1.WindowSizeUpdate
	12, // 10: platypus.agent.v1.Envelope.exec_request:type_name -> platypus.agent.v1.ExecRequest
	13, // 11: platypus.agent.v1.Envelope.exec_response:type_name -> platypus.agent.v1.ExecResponse
	14, // 12: platypus.agent.v1.Envelope.read_file_request:type_name -> platypus.agent.v1.ReadFileRequest
	15, // 13: platypus.agent.v1.Envelope.read_file_response:type_name -> platypus.agent.v1.ReadFileResponse
	16, // 14: platypus.agent.v1.Envelope.write_file_request:type_name -> platypus.agent.v1.WriteFileRequest
	17, // 15: platypus.agent.v1.Envelope.write_file_response:type_name -> platypus.agent.v1.WriteFileResponse
	18, // 16: platypus.agent.v1.Envelope.file_size_request:type_name -> platypus.agent.v1.FileSizeRequest
	19, // 17: platypus.agent.v1.Envelope.file_size_response:type_name -> platypus.agent.v1.FileSizeResponse
	20, // 18: platypus.agent.v1.Envelope.tunnel_create_request:type_name -> platypus.agent.v1.TunnelCreateRequest
	21, // 19: platypus.agent.v1.Envelope.tunnel_created_response:type_name -> platypus.agent.v1.TunnelCreatedResponse
	22, // 20: platypus.agent.v1.Envelope.tunnel_create_failed:type_name -> platypus.agent.v1.TunnelCreateFailed
	26, // 21: platypus.agent.v1.Envelope.tunnel_data:type_name -> platypus.agent.v1.TunnelData
	27, // 22: platypus.agent.v1.Envelope.tunnel_close_request:type_name -> platypus.agent.v1.TunnelCloseRequest
	28, // 23: platypus.agent.v1.Envelope.tunnel_closed:type_name -> platypus.agent.v1.TunnelClosedNotice
	23, // 24: platypus.agent.v1.Envelope.tunnel_connect_request:type_name -> platypus.agent.v1.TunnelConnectRequest
	24, // 25: platypus.agent.v1.Envelope.tunnel_connected_response:type_name -> platypus.agent.v1.TunnelConnectedResponse
	25, // 26: platypus.agent.v1.Envelope.tunnel_connect_failed:type_name -> platypus.agent.v1.TunnelConnectFailed
	29, // 27: platypus.agent.v1.Envelope.tunnel_disconnected:type_name -> platypus.agent.v1.TunnelDisconnectedNotice
	30, // 28: platypus.agent.v1.Envelope.socks5_create_request:type_name -> platypus.agent.v1.Socks5CreateRequest
	31, // 29: platypus.agent.v1.Envelope.socks5_created_response:type_name -> platypus.agent.v1.Socks5CreatedResponse
	32, // 30: platypus.agent.v1.Envelope.socks5_create_failed:type_name -> platypus.agent.v1.Socks5CreateFailed
	33, // 31: platypus.agent.v1.Envelope.socks5_destroy_request:type_name -> platypus.agent.v1.Socks5DestroyRequest
	34, // 32: platypus.agent.v1.Envelope.socks5_destroyed_response:type_name -> platypus.agent.v1.Socks5DestroyedResponse
	35, // 33: platypus.agent.v1.Envelope.socks5_destroy_failed:type_name -> platypus.agent.v1.Socks5DestroyFailed
	36, // 34: platypus.agent.v1.ClientInfoResponse.network_interfaces:type_name -> platypus.agent.v1.ClientInfoResponse.NetworkInterfacesEntry
	0,  // 35: platypus.agent.v1.TunnelCreateRequest.mode:type_name -> platypus.agent.v1.TunnelMode
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_proto_agent_v1_agent_proto_init() }
func file_proto_agent_v1_agent_proto_init() {
	if File_proto_agent_v1_agent_proto != nil {
		return
	}
	file_proto_agent_v1_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_GetClientInfoRequest)(nil),
		(*Envelope_ClientInfoResponse)(nil),
		(*Envelope_DuplicateClient)(nil),
		(*Envelope_UpdateRequest)(nil),
		(*Envelope_ProcessStartRequest)(nil),
		(*Envelope_ProcessStartedResponse)(nil),
		(*Envelope_ProcessStopped)(nil),
		(*Envelope_ProcessTerminateRequest)(nil),
		(*Envelope_Stdio)(nil),
		(*Envelope_WindowSize)(nil),
		(*Envelope_ExecRequest)(nil),
		(*Envelope_ExecResponse)(nil),
		(*Envelope_ReadFileRequest)(nil),
		(*Envelope_ReadFileResponse)(nil),
		(*Envelope_WriteFileRequest)(nil),
		(*Envelope_WriteFileResponse)(nil),
		(*Envelope_FileSizeRequest)(nil),
		(*Envelope_FileSizeResponse)(nil),
		(*Envelope_TunnelCreateRequest)(nil),
		(*Envelope_TunnelCreatedResponse)(nil),
		(*Envelope_TunnelCreateFailed)(nil),
		(*Envelope_TunnelData)(nil),
		(*Envelope_TunnelCloseRequest)(nil),
		(*Envelope_TunnelClosed)(nil),
		(*Envelope_TunnelConnectRequest)(nil),
		(*Envelope_TunnelConnectedResponse)(nil),
		(*Envelope_TunnelConnectFailed)(nil),
		(*Envelope_TunnelDisconnected)(nil),
		(*Envelope_Socks5CreateRequest)(nil),
		(*Envelope_Socks5CreatedResponse)(nil),
		(*Envelope_Socks5CreateFailed)(nil),
		(*Envelope_Socks5DestroyRequest)(nil),
		(*Envelope_Socks5DestroyedResponse)(nil),
		(*Envelope_Socks5DestroyFailed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_v1_agent_proto_rawDesc), len(file_proto_agent_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_v1_agent_proto = out.File
	file_proto_agent_v1_agent_proto_goTypes = nil
	file_proto_agent_v1_agent_proto_depIdxs = nil
}
